/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Collection
 * Android class: COL_GlobalProcedures
 * Date: 14/09/2018 02:54:17
 * Version of wdjava.dll: 22.0.106.0
 */


package com.mycompany.qr.wdgen;


import com.mycompany.qr.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.core.application.*;
import fr.pcsoft.wdjava.xml.dino.*;
import fr.pcsoft.wdjava.core.poo.*;
import fr.pcsoft.wdjava.api.*;
import fr.pcsoft.wdjava.core.parcours.*;
import fr.pcsoft.wdjava.core.parcours.hf.*;
import fr.pcsoft.wdjava.ws.*;
import fr.pcsoft.wdjava.core.erreur.*;
import fr.pcsoft.wdjava.core.types.collection.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/



class GWDCPCOL_GlobalProcedures extends WDCollProcAndroid
{
// Nombre de Procédures : 20
static public void fWD_procesar_Xml( WDObjet vWD_sfilename , WDObjet vWD_nTipo )
{
initExecProcGlobale("Procesar_Xml");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_kfill = new WDEntier();

WDObjet vWD_sFtabla = new WDChaineU();

WDObjet vWD_sFvalorbuscar = new WDChaineU();

WDObjet vWD_gsfilename = new WDChaineU();

WDObjet vWD_s_name = new WDChaineU();

WDObjet vWD_xml1 = WDVarNonAllouee.ref;
WDObjet vWD_j1 = new WDEntier();

WDObjet vWD_k = new WDEntier();

WDObjet vWD_name_tag = new WDChaineU();



vWD_sfilename = WDParametre.traiterParametre(vWD_sfilename, 1, false, 16);

vWD_nTipo = WDParametre.traiterParametre(vWD_nTipo, 2, false, 8);


// kfill is int


// sFtabla is string


// sFvalorbuscar is string


// gsfilename is string


// s_name is string


// xml1 is xmlDocument
vWD_xml1 = new WDInstance( new WDXMLDocument() );


// IF nTipo=1 THEN
if(vWD_nTipo.opEgal(1))
{
// 	xml1 = XMLOpen(sfilename, fromFile)
vWD_xml1.setValeur(WDAPIXmlDINO.xmlOuvre(vWD_sfilename,2));

}
else
{
// 	xml1= XMLOpen(sfilename,fromString)
vWD_xml1.setValeur(WDAPIXmlDINO.xmlOuvre(vWD_sfilename,1));

}

// j1 is int 


// k is int = ArrayCount(scamposlocales)

vWD_k.setValeur(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_scamposlocales));


// name_tag is string


// IF xml1..RootNode..Occurrence<1 THEN
if(vWD_xml1.getProp(EWDPropriete.PROP_NOEUDRACINE).getOccurrence().opInf(1))
{
// 	      Info("Archivo no tiene raíz")
WDAPIDialogue.info("Archivo no tiene raíz");

}
else
{
// 	FOR EACH unRaiz OF xml1..RootNode
IWDParcours parcours1 = null;
try
{
WDObjet vWD_unRaiz = WDParcoursFactory.creerVariableParcours(vWD_xml1.getProp(EWDPropriete.PROP_NOEUDRACINE));
parcours1 = WDParcoursFactory.pourTout(vWD_xml1.getProp(EWDPropriete.PROP_NOEUDRACINE), vWD_unRaiz, null, null, null, 0x0, 0x2);
while(parcours1.testParcours())
{
// 		name_tag=unRaiz..Name
vWD_name_tag.setValeur(parcours1.getVariableParcours().getProp(EWDPropriete.PROP_NOM));

// 		FOR EACH  unXML OF unRaiz
IWDParcours parcours2 = null;
try
{
WDObjet vWD_unXML = WDParcoursFactory.creerVariableParcours(parcours1.getVariableParcours());
parcours2 = WDParcoursFactory.pourTout(parcours1.getVariableParcours(), vWD_unXML, null, null, null, 0x0, 0x2);
while(parcours2.testParcours())
{
// 			name_tag=unXML..Name
vWD_name_tag.setValeur(parcours2.getVariableParcours().getProp(EWDPropriete.PROP_NOM));

// 			FOR EACH uncampo OF unXML
IWDParcours parcours3 = null;
try
{
WDObjet vWD_uncampo = WDParcoursFactory.creerVariableParcours(parcours2.getVariableParcours());
parcours3 = WDParcoursFactory.pourTout(parcours2.getVariableParcours(), vWD_uncampo, null, null, null, 0x0, 0x2);
while(parcours3.testParcours())
{
// 				name_tag=NoCharacter(uncampo..Name,"a")
vWD_name_tag.setValeur(WDAPIChaine.sansCaractere(parcours3.getVariableParcours().getProp(EWDPropriete.PROP_NOM).getString(),"a"));

// 				j1=Val(name_tag)
vWD_j1.setValeur(WDAPIChaine.val(vWD_name_tag));

// 				IF j1>0 THEN
if(vWD_j1.opSup(0))
{
// 					s_name=uncampo..Text
vWD_s_name.setValeur(parcours3.getVariableParcours().getProp(EWDPropriete.PROP_TEXTE));

// 					gsfilename  = sfile+"."+sCampos[j1]
vWD_gsfilename.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_sCampos.get(vWD_j1)));

// 					SWITCH( sTipos[j1] )
// Délimiteur de visibilité pour ne pas étendre la visibilité de la variable temporaire _WDExpSelon
{
WDObjet _WDExpSelon0 = GWDPQR.ms_Project.vWD_sTipos.get(vWD_j1);
if(_WDExpSelon0.opEgal("S"))
{
// 							{gsfilename}=s_name
WDIndirection.get(vWD_gsfilename.getString()).setValeur(vWD_s_name);

}
else if(_WDExpSelon0.opEgal("N"))
{
// 							{gsfilename}=Val(s_name)
WDIndirection.get(vWD_gsfilename.getString()).setValeur(WDAPIChaine.val(vWD_s_name));

}
else if(_WDExpSelon0.opEgal("D"))
{
// 							{gsfilename}=StringToDate(s_name,"yyyy-mm-dd")
WDIndirection.get(vWD_gsfilename.getString()).setValeur(WDAPIDate.chaineVersDate(vWD_s_name.getString(),"yyyy-mm-dd"));

}
else if(_WDExpSelon0.opEgal("T"))
{
// 							{gsfilename}=StringToDate(s_name,"yyyy-mm-ddThh:mm:ss")
WDIndirection.get(vWD_gsfilename.getString()).setValeur(WDAPIDate.chaineVersDate(vWD_s_name.getString(),"yyyy-mm-ddThh:mm:ss"));

}

}

}

}

}
finally
{
if(parcours3 != null)
{
parcours3.finParcours();
}
}


// 			FOR j1=1 TO k
for(vWD_j1.setValeur(1);vWD_j1.opInfEgal(vWD_k);vWD_j1.opInc())
{
// 				gsfilename  = sfile+"."+scamposlocales[j1]
vWD_gsfilename.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_scamposlocales.get(vWD_j1)));

// 				SWITCH( sTiposlocales[j1] )
// Délimiteur de visibilité pour ne pas étendre la visibilité de la variable temporaire _WDExpSelon
{
WDObjet _WDExpSelon1 = GWDPQR.ms_Project.vWD_sTiposlocales.get(vWD_j1);
if(_WDExpSelon1.opEgal("S"))
{
// 						{gsfilename}=sValoreslocales[j1]
WDIndirection.get(vWD_gsfilename.getString()).setValeur(GWDPQR.ms_Project.vWD_sValoreslocales.get(vWD_j1));

}
else if(_WDExpSelon1.opEgal("N"))
{
// 						{gsfilename}=Val(sValoreslocales[j1])
WDIndirection.get(vWD_gsfilename.getString()).setValeur(WDAPIChaine.val(GWDPQR.ms_Project.vWD_sValoreslocales.get(vWD_j1)));

}
else if(_WDExpSelon1.opEgal("D"))
{
// 						{gsfilename}=StringToDate(sValoreslocales[j1])
WDIndirection.get(vWD_gsfilename.getString()).setValeur(WDAPIDate.chaineVersDate(GWDPQR.ms_Project.vWD_sValoreslocales.get(vWD_j1).getString()));

}
else if(_WDExpSelon1.opEgal("B"))
{
// 						IF sValoreslocales[j1]="0" THEN
if(GWDPQR.ms_Project.vWD_sValoreslocales.get(vWD_j1).opEgal("0"))
{
// 							{gsfilename}=False
WDIndirection.get(vWD_gsfilename.getString()).setValeur(false);

}
else
{
// 							{gsfilename}=True
WDIndirection.get(vWD_gsfilename.getString()).setValeur(true);

}

}

}

}

// 			IF ArrayCount(sFilltabla)>0 THEN
if(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sFilltabla).opSup(0))
{
// 						FOR kfill=1 TO ArrayCount(sFilltabla)
for(vWD_kfill.setValeur(1);vWD_kfill.opInfEgal(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sFilltabla));vWD_kfill.opInc())
{
// 							 sFtabla=sFilltabla[kfill]
vWD_sFtabla.setValeur(GWDPQR.ms_Project.vWD_sFilltabla.get(vWD_kfill));

// 							 sFvalorbuscar={sfile + "."+sFillcampobuscar[kfill]}
vWD_sFvalorbuscar.setValeur(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_sFillcampobuscar.get(vWD_kfill)).getString()));

// 							HSeek(sFilltabla[kfill],sFillcampobuscar[kfill],sFvalorbuscar)
WDAPIHF.hRecherche(GWDPQR.ms_Project.vWD_sFilltabla.get(vWD_kfill),GWDPQR.ms_Project.vWD_sFillcampobuscar.get(vWD_kfill),vWD_sFvalorbuscar);

// 							IF HFound(sFilltabla[kfill]) THEN
if(WDAPIHF.hTrouve(GWDPQR.ms_Project.vWD_sFilltabla.get(vWD_kfill)).getBoolean())
{
// 								HRead(sFilltabla[kfill],HRecNum(sFilltabla[kfill]))
WDAPIHF.hLit(GWDPQR.ms_Project.vWD_sFilltabla.get(vWD_kfill),WDAPIHF.hNumEnr(GWDPQR.ms_Project.vWD_sFilltabla.get(vWD_kfill)).getLong());

// 								sFtabla=sfile+"."+sFillcampollenar[kfill]
vWD_sFtabla.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_sFillcampollenar.get(vWD_kfill)));

// 								{sFtabla} = {sFilltabla[kfill]+"."+sFillcampovalor[kfill]}
WDIndirection.get(vWD_sFtabla.getString()).setValeur(WDIndirection.get(GWDPQR.ms_Project.vWD_sFilltabla.get(vWD_kfill).opPlus(".").opPlus(GWDPQR.ms_Project.vWD_sFillcampovalor.get(vWD_kfill)).getString()));

}

}

}

// 			HAdd(sfile)
WDAPIHF.hAjoute(GWDPQR.ms_Project.vWD_sfile);

}

}
finally
{
if(parcours2 != null)
{
parcours2.finParcours();
}
}


}

}
finally
{
if(parcours1 != null)
{
parcours1.finParcours();
}
}


}

// RETURN 
return;

}
finally
{
finExecProcGlobale();
}

}


//  Summary: <specify the procedure action>
//  Syntax:
// Procesar_parametros ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	None
// 
//  For instance:
//  Indicate an example.
// 
// 	sparametros (UNICODE string): <specify the role of sparametros>
static public void fWD_procesar_parametros()
{
initExecProcGlobale("Procesar_parametros");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_li = new WDEntier();

WDObjet vWD_k = new WDEntier();



// li is int


// k is int


// IF sParametros<>""  THEN
if(GWDPQR.ms_Project.vWD_sParametros.opDiff(""))
{
// 	StringToArray(sParametros,arrSParametros,"|")
WDAPITableau.chaineVersTableau(GWDPQR.ms_Project.vWD_sParametros,GWDPQR.ms_Project.vWD_arrSParametros,"|");

// 	StringToArray(sParametros,arrSValParametros,"|")
WDAPITableau.chaineVersTableau(GWDPQR.ms_Project.vWD_sParametros,GWDPQR.ms_Project.vWD_arrSValParametros,"|");

// 	k=ArrayCount(arrSParametros)
vWD_k.setValeur(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_arrSParametros));

// 	FOR li=1 TO k
for(vWD_li.setValeur(1);vWD_li.opInfEgal(vWD_k);vWD_li.opInc())
{
// 		arrSValParametros[li]={arrSParametros[li]}
GWDPQR.ms_Project.vWD_arrSValParametros.get(vWD_li).setValeur(WDIndirection.get(GWDPQR.ms_Project.vWD_arrSParametros.get(vWD_li).getString()));

}

// 	IF gsTablename<>"" AND Contains(gsTablename,"%")  THEN
if((GWDPQR.ms_Project.vWD_gsTablename.opDiff("") & WDAPIChaine.contient(GWDPQR.ms_Project.vWD_gsTablename,new WDChaineU("%")).getBoolean()))
{
// 		gsTablename = StringBuild(gsTablename,arrSValParametros)	
GWDPQR.ms_Project.vWD_gsTablename.setValeur(WDAPIChaine.chaineConstruit(GWDPQR.ms_Project.vWD_gsTablename,GWDPQR.ms_Project.vWD_arrSValParametros));

}

// 	IF sWhere<>"" AND sParametros<>"" THEN
if((GWDPQR.ms_Project.vWD_sWhere.opDiff("") & GWDPQR.ms_Project.vWD_sParametros.opDiff("")))
{
// 		sWhere = StringBuild(sWhere,arrSValParametros)
GWDPQR.ms_Project.vWD_sWhere.setValeur(WDAPIChaine.chaineConstruit(GWDPQR.ms_Project.vWD_sWhere,GWDPQR.ms_Project.vWD_arrSValParametros));

}

}

}
finally
{
finExecProcGlobale();
}

}


//  Summary: <specify the procedure action>
//  Syntax:
// [ <Result> = ] Llenar_campos (<sDestino> is string)
// 
//  Parameters:
// 	sDestino (UNICODE string):<specify the role of sDestino>
//  Return Value:
//  	boolean: // 	None
// 
//  For instance:
//  Indicate an example.
// 
// 	slocal (UNICODE string): <specify the role of slocal>
static public WDObjet fWD_llenar_campos( WDObjet vWD_sDestino )
{
initExecProcGlobale("Llenar_campos");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_sWherelocal = new WDChaineU();



vWD_sDestino = WDParametre.traiterParametre(vWD_sDestino, 1, false, 16);


// sListacampos=""
GWDPQR.ms_Project.vWD_sListacampos.setValeur("");

// sWherelocal is string = "Interface.Bdlocal='"+sfile+"' "  // and Interface.Bddestino='"+sDestino+"'"

vWD_sWherelocal.setValeur(new WDChaineU("Interface.Bdlocal='").opPlus(GWDPQR.ms_Project.vWD_sfile).opPlus("' "));


// FOR EACH Interface where sWherelocal 
IWDParcours parcours4 = null;
try
{
parcours4 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("interface"), null, vWD_sWherelocal.getString(), true);
while(parcours4.testParcours())
{
// 	IF Interface.Bdlocal=sfile AND Interface.Bddestino=sDestino  THEN
if((WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("bdlocal").opEgal(GWDPQR.ms_Project.vWD_sfile) & WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("bddestino").opEgal(vWD_sDestino)))
{
// 		Add(sCampos,Interface.campolocal)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sCampos,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campolocal"));

// 		Add(sCamposExt,Interface.campodestino)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sCamposExt,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campodestino"));

// 		sListacampos +=Interface.campodestino+","
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus(WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campodestino").opPlus(",")));

// 		Add(sTipos,Interface.Tipodedato)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sTipos,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato"));

// 		IF Interface.filltabla<>"" THEN
if(WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("filltabla").opDiff(""))
{
// 			Add(sFilltabla,Interface.filltabla)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sFilltabla,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("filltabla"));

// 			Add(sFillcampobuscar,Interface.fillcampobuscar)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sFillcampobuscar,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("fillcampobuscar"));

// 			Add(sFillcampollenar,Interface.fillcampollenar)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sFillcampollenar,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("fillcampollenar"));

// 			Add(sFillcampovalor,Interface.fillcampovalor)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sFillcampovalor,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("fillcampovalor"));

// 			Add(sFillTipos,Interface.Tipodedato)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sFillTipos,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato"));

}

}
else if(((WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("bdlocal").opEgal(GWDPQR.ms_Project.vWD_sfile) & WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("bddestino").opEgal("")) & WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("defecto").opDiff("")))
{
// 		Add(scamposlocales,Interface.campolocal)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_scamposlocales,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campolocal"));

// 		Add(sTiposlocales,Interface.Tipodedato)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sTiposlocales,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato"));

// 		Add(sValoreslocales,Interface.Defecto)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sValoreslocales,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("defecto"));

}

}
}
finally
{
if(parcours4 != null)
{
parcours4.finParcours();
}
}


// IF ArrayCount(sCampos)=0 AND ArrayCount(scamposlocales)=0 THEN
if((WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCampos).opEgal(0) & WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_scamposlocales).opEgal(0)))
{
// 	RESULT False
return new WDBooleen(false);

}

// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcGlobale();
}

}


//  Summary: <specify the procedure action>
//  Syntax:
//  Global_Leer_Tabla_comp ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	None
// 
//  For instance:
//  Indicate an example.
// 
static public void fWD_global_Leer_Tabla_comp()
{
initExecProcGlobale("Global_Leer_Tabla_comp");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_v1 = WDVarNonAllouee.ref;
WDObjet vWD_v2 = WDVarNonAllouee.ref;
WDObjet vWD_v11 = WDVarNonAllouee.ref;
WDObjet vWD_v12 = WDVarNonAllouee.ref;
WDObjet vWD_sResultado = new WDChaineU();

WDObjet vWD_sResultadoparcial = new WDChaineU();

WDObjet vWD_sName = new WDChaineU();

WDObjet vWD_sNamein = new WDChaineU();

WDObjet vWD_n = new WDEntier();

WDObjet vWD_m = new WDEntier();



// WSDataSQLService.Address=Parametros.wsutrl   //"http://186.159.215.109:591/SQLServerWebservice/SQLWebservice.asmx"
WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").get("Address").setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("wsutrl"));

// v1 is LeerTablacomp
vWD_v1 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "LeerTablacomp") );


// v2 is LeerTablacompResponse
vWD_v2 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "LeerTablacompResponse") );


// v11 is DownloadFile
vWD_v11 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "DownloadFile") );


// v12 is DownloadFileResponse
vWD_v12 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "DownloadFileResponse") );


// sResultado is string


// sResultadoparcial is string 


// sName is string


// sNamein is string


// v1.servidor=""   // se usa el de web.config ,esta version de funcion no usa instancia parametros.servidor
vWD_v1.get("servidor").setValeur("");

// v1.basededatos=Parametros.basededatos
vWD_v1.get("basededatos").setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("basededatos"));

// v1.tabla=gsTablename
vWD_v1.get("tabla").setValeur(GWDPQR.ms_Project.vWD_gsTablename);

// v1.campos=NoRightCharacter(sListacampos,",")
vWD_v1.get("campos").setValeur(WDAPIChaine.sansCaractereDroite(GWDPQR.ms_Project.vWD_sListacampos.getString(),","));

// v1.where=sWhere
vWD_v1.get("where").setValeur(GWDPQR.ms_Project.vWD_sWhere);

// v2=LeerTablacomp(v1)
vWD_v2.setValeur(WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").invoquerMethode("LeerTablacomp", new WDObjet[] {vWD_v1} ));

// n is int


// m is int


// sResultado=v2.LeerTablacompResult
vWD_sResultado.setValeur(vWD_v2.get("LeerTablacompResult"));

// IF sResultado<>"" THEN
if(vWD_sResultado.opDiff(""))
{
// 	n = Position(sResultado, "<filename>", 1, FromBeginning)
vWD_n.setValeur(WDAPIChaine.position(vWD_sResultado,new WDChaineU("<filename>"),1,0));

// 	IF n>0 THEN
if(vWD_n.opSup(0))
{
// 		m = Position(sResultado, "</filename>", 1, FromBeginning)
vWD_m.setValeur(WDAPIChaine.position(vWD_sResultado,new WDChaineU("</filename>"),1,0));

// 		sName=Middle(sResultado,n + 10, m - (n + 10))
vWD_sName.setValeur(WDAPIChaine.milieu(vWD_sResultado,vWD_n.opPlus(10).getInt(),vWD_m.opMoins(vWD_n.opPlus(10)).getInt()));

// 		v11.FName=sName
vWD_v11.get("FName").setValeur(vWD_sName);

// 		f is int
WDObjet vWD_f = new WDEntier();



// 		IF InAndroidSimulatorMode()=True THEN
if(WDAPIVM.enModeSimulateurAndroid().opEgal(true))
{
// 			sNamein = "c:\\sistemas\\wsin\\"+DateSys() + TimeSys() + ".txt"
vWD_sNamein.setValeur(new WDChaineU("c:\\sistemas\\wsin\\").opPlus(WDAPIDate.dateSys()).opPlus(WDAPIDate.heureSys()).opPlus(".txt"));

// 			f=fOpen(sNamein, foCreate)
vWD_f.setValeur(WDAPIFichier.fOuvre(vWD_sNamein.getString(),512));

}
else
{
// 			sNamein = "/sdcard/recibos/"+DateSys() + TimeSys() + ".txt"
vWD_sNamein.setValeur(new WDChaineU("/sdcard/recibos/").opPlus(WDAPIDate.dateSys()).opPlus(WDAPIDate.heureSys()).opPlus(".txt"));

// 			f=fOpen(sNamein, foCreate)
vWD_f.setValeur(WDAPIFichier.fOuvre(vWD_sNamein.getString(),512));

}

// 		IF f=-1 THEN
if(vWD_f.opEgal(-1))
{
// 			RETURN 
return;

}

// 		m=((fSize(sName) +  40000)/40000) + 1
vWD_m.setValeur(WDAPIFichier.fTaille(vWD_sName.getString()).opPlus(40000).opDiv(40000).opPlus(1));

// 		m = m *2 
vWD_m.setValeur(vWD_m.opMult(2));

// 		sResultado=""
vWD_sResultado.setValeur("");

// 		FOR n=1 TO m
for(vWD_n.setValeur(1);vWD_n.opInfEgal(vWD_m);vWD_n.opInc())
{
// 			v11.parte=NumToString(n)
vWD_v11.get("parte").setValeur(WDAPINum.numeriqueVersChaine(vWD_n));

// 			v12=DownloadFile(v11)	
vWD_v12.setValeur(WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").invoquerMethode("DownloadFile", new WDObjet[] {vWD_v11} ));

// 			sResultadoparcial = v12.DownloadFileResult
vWD_sResultadoparcial.setValeur(vWD_v12.get("DownloadFileResult"));

// 			IF fWrite(f,sResultadoparcial  )=-1 THEN RETURN 
if(WDAPIFichier.fEcrit(vWD_f.getInt(),vWD_sResultadoparcial).opEgal(-1))
{
// 			IF fWrite(f,sResultadoparcial  )=-1 THEN RETURN 
return;

}

}

// 		IF fClose(f)=-1 THEN RETURN
if(WDAPIFichier.fFerme(vWD_f.getInt()).opEgal(-1))
{
// 		IF fClose(f)=-1 THEN RETURN
return;

}

// 		Procesar_Xml(sNamein,1)
GWDCPCOL_GlobalProcedures.fWD_procesar_Xml(vWD_sNamein,new WDEntier(1));

// 		fDelete(sNamein)
WDAPIFichier.fSupprime(vWD_sNamein.getString());

}
else
{
// 		IF IniOSMode() OR IniOSEmulatorMode() OR IniOSSimulatorMode() THEN
if(((WDAPIVM.enModeiOS().getBoolean() | WDAPIVM.enModeEmulateuriOS().getBoolean()) | WDAPIVM.enModeSimulateuriOS().getBoolean()))
{
// 			Procesar_Xml_var(sResultado)
GWDCPCOL_GlobalProcedures.fWD_procesar_Xml_var(vWD_sResultado);

}
else
{
// 			Procesar_Xml(sResultado,2)
GWDCPCOL_GlobalProcedures.fWD_procesar_Xml(vWD_sResultado,new WDEntier(2));

}

}

}

// RETURN    
return;

}
finally
{
finExecProcGlobale();
}

}


static public void fWD_global_Leer_Tabla( WDObjet vWD_purl , WDObjet vWD_Pservidor , WDObjet vWD_pinstancia , WDObjet vWD_pbasededatos , WDObjet vWD_pusuario , WDObjet vWD_pclave , WDObjet vWD_ptabla , WDObjet vWD_pcampos , WDObjet vWD_pwhere , WDObjet vWD_porder )
{
initExecProcGlobale("Global_Leer_Tabla");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_v1 = WDVarNonAllouee.ref;
WDObjet vWD_v2 = WDVarNonAllouee.ref;
WDObjet vWD_v11 = WDVarNonAllouee.ref;
WDObjet vWD_v12 = WDVarNonAllouee.ref;
WDObjet vWD_sResultado = new WDChaineU();

WDObjet vWD_sResultadoparcial = new WDChaineU();

WDObjet vWD_sName = new WDChaineU();

WDObjet vWD_sNamein = new WDChaineU();

WDObjet vWD_n = new WDEntier();

WDObjet vWD_m = new WDEntier();



vWD_purl = WDParametre.traiterParametre(vWD_purl, 1, false, 16);

vWD_Pservidor = WDParametre.traiterParametre(vWD_Pservidor, 2, false, 16);

vWD_pinstancia = WDParametre.traiterParametre(vWD_pinstancia, 3, false, 16);

vWD_pbasededatos = WDParametre.traiterParametre(vWD_pbasededatos, 4, false, 16);

vWD_pusuario = WDParametre.traiterParametre(vWD_pusuario, 5, false, 16);

vWD_pclave = WDParametre.traiterParametre(vWD_pclave, 6, false, 16);

vWD_ptabla = WDParametre.traiterParametre(vWD_ptabla, 7, false, 16);

vWD_pcampos = WDParametre.traiterParametre(vWD_pcampos, 8, false, 16);

vWD_pwhere = WDParametre.traiterParametre(vWD_pwhere, 9, false, 16);

vWD_porder = WDParametre.traiterParametre(vWD_porder, 10, false, 16);


// WSDataSQLService..Address=purl
WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").setProp(EWDPropriete.PROP_ADRESSE,vWD_purl);

// v1 is LeerTabla
vWD_v1 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "LeerTabla") );


// v2 is LeerTablaResponse
vWD_v2 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "LeerTablaResponse") );


// v11 is DownloadFile
vWD_v11 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "DownloadFile") );


// v12 is DownloadFileResponse
vWD_v12 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "DownloadFileResponse") );


// sResultado is string


// sResultadoparcial is string 


// sName is string


// sNamein is string


// v1.usuario=pusuario
vWD_v1.get("usuario").setValeur(vWD_pusuario);

// v1.clave=pclave
vWD_v1.get("clave").setValeur(vWD_pclave);

// v1.servidor=Pservidor
vWD_v1.get("servidor").setValeur(vWD_Pservidor);

// v1.instancia=pinstancia
vWD_v1.get("instancia").setValeur(vWD_pinstancia);

// v1.basededatos=pbasededatos
vWD_v1.get("basededatos").setValeur(vWD_pbasededatos);

// v1.tabla=ptabla
vWD_v1.get("tabla").setValeur(vWD_ptabla);

// v1.campos=NoRightCharacter(pcampos,",")
vWD_v1.get("campos").setValeur(WDAPIChaine.sansCaractereDroite(vWD_pcampos.getString(),","));

// v1.where=pwhere
vWD_v1.get("where").setValeur(vWD_pwhere);

// v1.order=porder
vWD_v1.get("order").setValeur(vWD_porder);

// v2=LeerTabla(v1)
vWD_v2.setValeur(WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").invoquerMethode("LeerTabla", new WDObjet[] {vWD_v1} ));

// n is int


// m is int


// sResultado=v2.LeerTablaResult
vWD_sResultado.setValeur(vWD_v2.get("LeerTablaResult"));

// IF sResultado<>"" THEN
if(vWD_sResultado.opDiff(""))
{
// 	n = Position(sResultado, "<filename>", 1, FromBeginning)
vWD_n.setValeur(WDAPIChaine.position(vWD_sResultado,new WDChaineU("<filename>"),1,0));

// 	IF n>0 THEN
if(vWD_n.opSup(0))
{
// 		m = Position(sResultado, "</filename>", 1, FromBeginning)
vWD_m.setValeur(WDAPIChaine.position(vWD_sResultado,new WDChaineU("</filename>"),1,0));

// 		sName=Middle(sResultado,n + 10, m - (n + 10))
vWD_sName.setValeur(WDAPIChaine.milieu(vWD_sResultado,vWD_n.opPlus(10).getInt(),vWD_m.opMoins(vWD_n.opPlus(10)).getInt()));

// 		v11.FName=sName
vWD_v11.get("FName").setValeur(vWD_sName);

// 		f is int
WDObjet vWD_f = new WDEntier();



// 		IF InAndroidSimulatorMode()=True OR IniOSSimulatorMode() THEN
if((WDAPIVM.enModeSimulateurAndroid().opEgal(true) | WDAPIVM.enModeSimulateuriOS().getBoolean()))
{
// 			sNamein = "c:\\sistemas\\wsin\\"+DateSys() + TimeSys() + ".txt"
vWD_sNamein.setValeur(new WDChaineU("c:\\sistemas\\wsin\\").opPlus(WDAPIDate.dateSys()).opPlus(WDAPIDate.heureSys()).opPlus(".txt"));

// 			f=fOpen(sNamein, foCreate)
vWD_f.setValeur(WDAPIFichier.fOuvre(vWD_sNamein.getString(),512));

}
else if(WDAPIVM.enModeAndroid().getBoolean())
{
// 			sNamein = "/sdcard/recibo/"+DateSys() + TimeSys() + ".txt"
vWD_sNamein.setValeur(new WDChaineU("/sdcard/recibo/").opPlus(WDAPIDate.dateSys()).opPlus(WDAPIDate.heureSys()).opPlus(".txt"));

// 			f=fOpen(sNamein, foCreate)
vWD_f.setValeur(WDAPIFichier.fOuvre(vWD_sNamein.getString(),512));

}
else if(WDAPIVM.enModeiOS().getBoolean())
{
// 			sNamein = CompleteDir(fCurrentDir())+DateSys() + TimeSys() + ".txt"
vWD_sNamein.setValeur(WDAPIChaine.completeRep(WDAPIFichier.fRepEnCours().getString()).opPlus(WDAPIDate.dateSys()).opPlus(WDAPIDate.heureSys()).opPlus(".txt"));

// 			f=fOpen(sNamein, foCreate)
vWD_f.setValeur(WDAPIFichier.fOuvre(vWD_sNamein.getString(),512));

}

// 		IF f=-1 THEN
if(vWD_f.opEgal(-1))
{
// 			RETURN 
return;

}

// 		m=((fSize(sName) +  40000)/40000) + 1
vWD_m.setValeur(WDAPIFichier.fTaille(vWD_sName.getString()).opPlus(40000).opDiv(40000).opPlus(1));

// 		m = m *2 
vWD_m.setValeur(vWD_m.opMult(2));

// 		sResultado=""
vWD_sResultado.setValeur("");

// 		FOR n=1 TO m
for(vWD_n.setValeur(1);vWD_n.opInfEgal(vWD_m);vWD_n.opInc())
{
// 			v11.parte=NumToString(n)
vWD_v11.get("parte").setValeur(WDAPINum.numeriqueVersChaine(vWD_n));

// 			v12=DownloadFile(v11)	
vWD_v12.setValeur(WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").invoquerMethode("DownloadFile", new WDObjet[] {vWD_v11} ));

// 			sResultadoparcial = v12.DownloadFileResult
vWD_sResultadoparcial.setValeur(vWD_v12.get("DownloadFileResult"));

// 			IF fWrite(f,sResultadoparcial  )=-1 THEN RETURN 
if(WDAPIFichier.fEcrit(vWD_f.getInt(),vWD_sResultadoparcial).opEgal(-1))
{
// 			IF fWrite(f,sResultadoparcial  )=-1 THEN RETURN 
return;

}

}

// 		IF fClose(f)=-1 THEN RETURN
if(WDAPIFichier.fFerme(vWD_f.getInt()).opEgal(-1))
{
// 		IF fClose(f)=-1 THEN RETURN
return;

}

// 		Procesar_Xml(sNamein,1)
GWDCPCOL_GlobalProcedures.fWD_procesar_Xml(vWD_sNamein,new WDEntier(1));

// 		fDelete(sNamein)
WDAPIFichier.fSupprime(vWD_sNamein.getString());

}
else
{
// 		IF IniOSMode() OR IniOSEmulatorMode() OR IniOSSimulatorMode() THEN
if(((WDAPIVM.enModeiOS().getBoolean() | WDAPIVM.enModeEmulateuriOS().getBoolean()) | WDAPIVM.enModeSimulateuriOS().getBoolean()))
{
}
else
{
// 			Procesar_Xml(sResultado,2)
GWDCPCOL_GlobalProcedures.fWD_procesar_Xml(vWD_sResultado,new WDEntier(2));

}

}

}

// RETURN    
return;

}
finally
{
finExecProcGlobale();
}

}


static public void fWD_procesar_Xml_var( WDObjet vWD_sRes )
{
initExecProcGlobale("Procesar_Xml_var");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_res = new WDBooleen();

WDObjet vWD_gb_primerrow = new WDBooleen();

WDObjet vWD_s_name_tag = new WDChaineU();

WDObjet vWD_s_name = new WDChaineU();

WDObjet vWD_gsfilename = new WDChaineU();

WDObjet vWD_j = new WDEntier();



vWD_sRes = WDParametre.traiterParametre(vWD_sRes, 1, false, 16);


// res is boolean


// gb_primerrow is boolean


// s_name_tag is string


// s_name is string 


// gsfilename is string


// j is int


// res=XMLDocument("XML1",sRes)
vWD_res.setValeur(WDAPIXmlClassic.xmlDocument("XML1",vWD_sRes));

// res=XMLFind("XML1",Null,XMLElement+XMLChildItem,XMLStartWith)
vWD_res.setValeur(WDAPIXmlClassic.xmlRecherche("XML1",WDObjet.NULL,19,2));

// gb_primerrow=False
vWD_gb_primerrow.setValeur(false);

// WHILE XMLFound("XML1") //Para recorrer el XML
while(WDAPIXmlClassic.xmlTrouve("XML1").getBoolean())
{
// 	SWITCH XMLElementType("XML1") 
// Délimiteur de visibilité pour ne pas étendre la visibilité de la variable temporaire _WDExpSelon
{
WDObjet _WDExpSelon0 = WDAPIXmlClassic.xmlTypeElement("XML1");
if(_WDExpSelon0.opEgal(1))
{
// 			s_name_tag = XMLElementName("XML1") // vou pegar nome da tag
vWD_s_name_tag.setValeur(WDAPIXmlClassic.XMLNomElement("XML1"));

// 			IF s_name_tag="r" THEN
if(vWD_s_name_tag.opEgal("r"))
{
// 				IF gb_primerrow=False 
if(vWD_gb_primerrow.opEgal(false))
{
// 					gb_primerrow=True
vWD_gb_primerrow.setValeur(true);

}
else
{
// 					FOR j=1 TO ArrayCount(scamposlocales)
for(vWD_j.setValeur(1);vWD_j.opInfEgal(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_scamposlocales));vWD_j.opInc())
{
// 						gsfilename  = sfile+"."+scamposlocales[j]
vWD_gsfilename.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_scamposlocales.get(vWD_j)));

// 						SWITCH( sTiposlocales[j] )
// Délimiteur de visibilité pour ne pas étendre la visibilité de la variable temporaire _WDExpSelon
{
WDObjet _WDExpSelon1 = GWDPQR.ms_Project.vWD_sTiposlocales.get(vWD_j);
if(_WDExpSelon1.opEgal("S"))
{
// 								{gsfilename}=sValoreslocales[j]
WDIndirection.get(vWD_gsfilename.getString()).setValeur(GWDPQR.ms_Project.vWD_sValoreslocales.get(vWD_j));

}
else if(_WDExpSelon1.opEgal("N"))
{
// 								{gsfilename}=Val(sValoreslocales[j])
WDIndirection.get(vWD_gsfilename.getString()).setValeur(WDAPIChaine.val(GWDPQR.ms_Project.vWD_sValoreslocales.get(vWD_j)));

}
else if(_WDExpSelon1.opEgal("D"))
{
// 								{gsfilename}=StringToDate(sValoreslocales[j])
WDIndirection.get(vWD_gsfilename.getString()).setValeur(WDAPIDate.chaineVersDate(GWDPQR.ms_Project.vWD_sValoreslocales.get(vWD_j).getString()));

}
else if(_WDExpSelon1.opEgal("B"))
{
// 								IF sValoreslocales[j]="0" THEN
if(GWDPQR.ms_Project.vWD_sValoreslocales.get(vWD_j).opEgal("0"))
{
// 									{gsfilename}=False
WDIndirection.get(vWD_gsfilename.getString()).setValeur(false);

}
else
{
// 									{gsfilename}=True
WDIndirection.get(vWD_gsfilename.getString()).setValeur(true);

}

}

}

}

// 					HAdd(sfile)
WDAPIHF.hAjoute(GWDPQR.ms_Project.vWD_sfile);

}

}
else
{
// 				s_name_tag=NoCharacter(s_name_tag,"a")
vWD_s_name_tag.setValeur(WDAPIChaine.sansCaractere(vWD_s_name_tag.getString(),"a"));

// 				j=Val(s_name_tag)
vWD_j.setValeur(WDAPIChaine.val(vWD_s_name_tag));

// 				IF j>0 THEN
if(vWD_j.opSup(0))
{
// 					s_name=XMLData("XML1")
vWD_s_name.setValeur(WDAPIXmlClassic.xmlDonnee("XML1"));

// 					gsfilename  = sfile+"."+sCampos[j]
vWD_gsfilename.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_sCampos.get(vWD_j)));

// 					SWITCH( sTipos[j] )
// Délimiteur de visibilité pour ne pas étendre la visibilité de la variable temporaire _WDExpSelon
{
WDObjet _WDExpSelon2 = GWDPQR.ms_Project.vWD_sTipos.get(vWD_j);
if(_WDExpSelon2.opEgal("S"))
{
// 							{gsfilename}=s_name
WDIndirection.get(vWD_gsfilename.getString()).setValeur(vWD_s_name);

}
else if(_WDExpSelon2.opEgal("N"))
{
// 							{gsfilename}=Val(s_name)
WDIndirection.get(vWD_gsfilename.getString()).setValeur(WDAPIChaine.val(vWD_s_name));

}
else if(_WDExpSelon2.opEgal("D"))
{
// 							{gsfilename}=StringToDate(s_name,"yyyy-mm-dd")
WDIndirection.get(vWD_gsfilename.getString()).setValeur(WDAPIDate.chaineVersDate(vWD_s_name.getString(),"yyyy-mm-dd"));

}
else if(_WDExpSelon2.opEgal("T"))
{
// 							{gsfilename}=StringToDate(s_name,"yyyy-mm-ddThh:mm:ss")
WDIndirection.get(vWD_gsfilename.getString()).setValeur(WDAPIDate.chaineVersDate(vWD_s_name.getString(),"yyyy-mm-ddThh:mm:ss"));

}

}

}

}

}

}

// 	XMLNext("XML1")
WDAPIXmlClassic.xmlSuivant("XML1");

}

// XMLClose("XML1")
WDAPIXmlClassic.xmlTermine("XML1");

// IF gb_primerrow=True 
if(vWD_gb_primerrow.opEgal(true))
{
// 	HAdd(sfile)
WDAPIHF.hAjoute(GWDPQR.ms_Project.vWD_sfile);

}

}
finally
{
finExecProcGlobale();
}

}


static public void fWD_revisar_Login()
{
initExecProcGlobale("Revisar_Login");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_tHTime = new WDHeure();

WDObjet vWD_dDate = new WDDate();

WDObjet vWD_dtUltimoacceso = new WDDateHeure();

WDObjet vWD_dtAhora = new WDDateHeure();



// HRead(Parametros,1)
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("parametros"),(long)1);

// tHTime is Time = Now()

vWD_tHTime.setValeur(WDAPIDate.maintenant());


// dDate is Date = Today()

vWD_dDate.setValeur(WDAPIDate.dateDuJour());


// Erreur sur l'objet: COL_GlobalProcedures
// 	Traitement : Revisar_Login (0)
// 	Code: 403
// 	Message: fecha_acceso item not found in Parametros file.
// 	Ligne : 4, Colonne : 53
// 
// 
// Erreur sur l'objet: COL_GlobalProcedures
// 	Traitement : Revisar_Login (0)
// 	Code: 403
// 	Message: hora_acceso item not found in Parametros file.
// 	Ligne : 4, Colonne : 102
// 
// 
// Erreur sur l'objet: COL_GlobalProcedures
// 	Traitement : Revisar_Login (0)
// 	Code: 403
// 	Message: fecha_acceso item not found in Parametros file.
// 	Ligne : 4, Colonne : 53
// 
// 
// Erreur sur l'objet: COL_GlobalProcedures
// 	Traitement : Revisar_Login (0)
// 	Code: 403
// 	Message: hora_acceso item not found in Parametros file.
// 	Ligne : 4, Colonne : 102
// 
// 
WDErreurManager.erreurGeneration("Erreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 403\r\n\tMessage: fecha_acceso item not found in Parametros file.\r\n\tLigne : 4, Colonne : 53\r\n\r\n\r\nErreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 403\r\n\tMessage: hora_acceso item not found in Parametros file.\r\n\tLigne : 4, Colonne : 102\r\n\r\n\r\nErreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 403\r\n\tMessage: fecha_acceso item not found in Parametros file.\r\n\tLigne : 4, Colonne : 53\r\n\r\n\r\nErreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 403\r\n\tMessage: hora_acceso item not found in Parametros file.\r\n\tLigne : 4, Colonne : 102\r\n\r\n");


// // dtUltimoacceso is DateTime = DateToString(Parametros.fecha_acceso,"yyyymmdd")+TimeToString(Parametros.hora_acceso,"hhmmss")
// 
// vWD_dtUltimoacceso.setValeur(WDAPIDate.dateVersChaine(,"yyyymmdd").opPlus(WDAPIDate.heureVersChaine(,"hhmmss")));
// 
// 

// // dtAhora is DateTime = DateToString(dDate,"yyyymmdd")+TimeToString(tHTime,"hhmmss")
// 
// vWD_dtAhora.setValeur(WDAPIDate.dateVersChaine(vWD_dDate,"yyyymmdd").opPlus(WDAPIDate.heureVersChaine(vWD_tHTime,"hhmmss")));
// 
// 
// // Erreur sur l'objet: COL_GlobalProcedures
// // 	Traitement : Revisar_Login (0)
// // 	Code: 403
// // 	Message: fecha_acceso item not found in Parametros file.
// // 	Ligne : 7, Colonne : 29
// // 
// // 
// // Erreur sur l'objet: COL_GlobalProcedures
// // 	Traitement : Revisar_Login (0)
// // 	Code: 403
// // 	Message: fecha_acceso item not found in Parametros file.
// // 	Ligne : 7, Colonne : 29
// // 
// // 
// WDErreurManager.erreurGeneration("Erreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 403\r\n\tMessage: fecha_acceso item not found in Parametros file.\r\n\tLigne : 7, Colonne : 29\r\n\r\n\r\nErreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 403\r\n\tMessage: fecha_acceso item not found in Parametros file.\r\n\tLigne : 7, Colonne : 29\r\n\r\n");
// 
// 
// // // IF DateDifference(Parametros.fecha_acceso,dDate) > 0 THEN
// // if(WDAPIDate.dateDifference(,vWD_dDate).opSup(0))
// // {
// // // Erreur sur l'objet: COL_GlobalProcedures
// // // 	Traitement : Revisar_Login (0)
// // // 	Code: 403
// // // 	Message: usuario item not found in Parametros file.
// // // 	Ligne : 9, Colonne : 53
// // // 
// // // 
// // // Erreur sur l'objet: COL_GlobalProcedures
// // // 	Traitement : Revisar_Login (0)
// // // 	Code: 403
// // // 	Message: clave item not found in Parametros file.
// // // 	Ligne : 9, Colonne : 72
// // // 
// // // 
// // // Erreur sur l'objet: COL_GlobalProcedures
// // // 	Traitement : Revisar_Login (0)
// // // 	Code: 403
// // // 	Message: usuario item not found in Parametros file.
// // // 	Ligne : 9, Colonne : 53
// // // 
// // // 
// // // Erreur sur l'objet: COL_GlobalProcedures
// // // 	Traitement : Revisar_Login (0)
// // // 	Code: 403
// // // 	Message: clave item not found in Parametros file.
// // // 	Ligne : 9, Colonne : 72
// // // 
// // // 
// // WDErreurManager.erreurGeneration("Erreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 403\r\n\tMessage: usuario item not found in Parametros file.\r\n\tLigne : 9, Colonne : 53\r\n\r\n\r\nErreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 403\r\n\tMessage: clave item not found in Parametros file.\r\n\tLigne : 9, Colonne : 72\r\n\r\n\r\nErreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 403\r\n\tMessage: usuario item not found in Parametros file.\r\n\tLigne : 9, Colonne : 53\r\n\r\n\r\nErreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 403\r\n\tMessage: clave item not found in Parametros file.\r\n\tLigne : 9, Colonne : 72\r\n\r\n");
// // 
// // 
// // // // 	Global_Validar_usuario(Parametros.wsutrl,Parametros.usuario,Parametros.clave)
// // // GWDCPCOL_GlobalProcedures.fWD_global_Validar_usuario(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("wsutrl"),,);
// // // 
// // 
// // }
// // else
// // {
// // // Erreur sur l'objet: COL_GlobalProcedures
// // // 	Traitement : Revisar_Login (0)
// // // 	Code: 301
// // // 	Message: The identifier 'WIN_Acceso' is unknown or inaccessible.
// // // 	Ligne : 13, Colonne : 18
// // // 
// // // 
// // // Erreur sur l'objet: COL_GlobalProcedures
// // // 	Traitement : Revisar_Login (0)
// // // 	Code: 301
// // // 	Message: The identifier 'WIN_Acceso' is unknown or inaccessible.
// // // 	Ligne : 13, Colonne : 18
// // // 
// // // 
// // WDErreurManager.erreurGeneration("Erreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 301\r\n\tMessage: The identifier 'WIN_Acceso' is unknown or inaccessible.\r\n\tLigne : 13, Colonne : 18\r\n\r\n\r\nErreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Revisar_Login (0)\r\n\tCode: 301\r\n\tMessage: The identifier 'WIN_Acceso' is unknown or inaccessible.\r\n\tLigne : 13, Colonne : 18\r\n\r\n");
// // 
// // 
// // // // 	OpenMobileWindow(WIN_Acceso)
// // // WDAPIFenetre.ouvreFille();
// // // 
// // 
// // }
// // 
// 
}
finally
{
finExecProcGlobale();
}

}


static public void fWD_inicializa()
{
initExecProcGlobale("Inicializa");


try
{
// HDeleteAll(Usuarios)
WDAPIHF.hSupprimeTout(WDAPIHF.getFichierSansCasseNiAccent("usuarios"));

// ArrayDeleteAll(sCampos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCampos);

// ArrayDeleteAll(sCamposExt)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCamposExt);

// ArrayDeleteAll(sTipos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTipos);

// ArrayDeleteAll(scamposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_scamposlocales);

// ArrayDeleteAll(sValoreslocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sValoreslocales);

// ArrayDeleteAll(arrSParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSParametros);

// ArrayDeleteAll(arrSValParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSValParametros);

// Global_Borrar_datos_locales()
GWDCPCOL_GlobalProcedures.fWD_global_Borrar_datos_locales();

}
finally
{
finExecProcGlobale();
}

}


static public WDObjet fWD_global_Validar_usuario( WDObjet vWD_url , WDObjet vWD_usuario , WDObjet vWD_clave )
{
initExecProcGlobale("Global_Validar_usuario");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_cuenta = new WDEntier();

WDObjet vWD_nBr = new WDEntier();



vWD_url = WDParametre.traiterParametre(vWD_url, 1, false, 16);

vWD_usuario = WDParametre.traiterParametre(vWD_usuario, 2, false, 16);

vWD_clave = WDParametre.traiterParametre(vWD_clave, 3, false, 16);


// Inicializa()
GWDCPCOL_GlobalProcedures.fWD_inicializa();

// cuenta is int=0

vWD_cuenta.setValeur(0);


// nBr is int=0

vWD_nBr.setValeur(0);


// sfile="Usuarios"
GWDPQR.ms_Project.vWD_sfile.setValeur("Usuarios");

// gsTabla="sy_usuarios_ws"
GWDPQR.ms_Project.vWD_gsTabla.setValeur("sy_usuarios_ws");

// gsStablename=gsTabla
GWDPQR.ms_Project.vWD_gsStablename.setValeur(GWDPQR.ms_Project.vWD_gsTabla);

// sCampos=["usuario","clave","zona","idpromotor"] //,"zona"]
GWDPQR.ms_Project.vWD_sCampos.setValeur(new WDSerie(new WDObjet[]{new WDChaineU("usuario"), new WDChaineU("clave"), new WDChaineU("zona"), new WDChaineU("idpromotor")}));

// sTipos=["S","S","S","N"] //,"S"]
GWDPQR.ms_Project.vWD_sTipos.setValeur(new WDSerie(new WDObjet[]{new WDChaineU("S"), new WDChaineU("S"), new WDChaineU("S"), new WDChaineU("N")}));

// sParametros=""
GWDPQR.ms_Project.vWD_sParametros.setValeur("");

// sListacampos ="usuario,clave,zona,idpromotor" //,zona"
GWDPQR.ms_Project.vWD_sListacampos.setValeur("usuario,clave,zona,idpromotor");

// sUrl=url
GWDPQR.ms_Project.vWD_sUrl.setValeur(vWD_url);

// sservidor=Parametros.servidor
GWDPQR.ms_Project.vWD_sservidor.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("servidor"));

// sInstancia=Parametros.instancia  //EDT_instancia //proveedores.instancia
GWDPQR.ms_Project.vWD_sInstancia.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("instancia"));

// sBasededatos=Parametros.basededatos  //EDT_Basededatos //Proveedores.basededatos
GWDPQR.ms_Project.vWD_sBasededatos.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("basededatos"));

// sUsuario =usuario 
GWDPQR.ms_Project.vWD_sUsuario.setValeur(vWD_usuario);

// sClave =clave 
GWDPQR.ms_Project.vWD_sClave.setValeur(vWD_clave);

// sWhere=" usuario='"+sUsuario+"'"
GWDPQR.ms_Project.vWD_sWhere.setValeur(new WDChaineU(" usuario='").opPlus(GWDPQR.ms_Project.vWD_sUsuario).opPlus("'"));

// scamposlocales=[""]
GWDPQR.ms_Project.vWD_scamposlocales.setValeur(new WDSerie(new WDObjet[]{new WDChaineU("")}));

// sTiposlocales=[""]
GWDPQR.ms_Project.vWD_sTiposlocales.setValeur(new WDSerie(new WDObjet[]{new WDChaineU("")}));

// sorder=""
GWDPQR.ms_Project.vWD_sorder.setValeur("");

// Multitask(-1)
WDAPIVM.multitache(-1);

// Global_Leer_Tabla(sUrl,sservidor,sInstancia,sBasededatos,sUsuario,sClave, gsTabla, sListacampos,sWhere,sorder)
GWDCPCOL_GlobalProcedures.fWD_global_Leer_Tabla(GWDPQR.ms_Project.vWD_sUrl,GWDPQR.ms_Project.vWD_sservidor,GWDPQR.ms_Project.vWD_sInstancia,GWDPQR.ms_Project.vWD_sBasededatos,GWDPQR.ms_Project.vWD_sUsuario,GWDPQR.ms_Project.vWD_sClave,GWDPQR.ms_Project.vWD_gsTabla,GWDPQR.ms_Project.vWD_sListacampos,GWDPQR.ms_Project.vWD_sWhere,GWDPQR.ms_Project.vWD_sorder);

// cuenta=0
vWD_cuenta.setValeur(0);

// HFirst(Usuarios)
WDAPIHF.hPremier(WDAPIHF.getFichierSansCasseNiAccent("usuarios"));

// HRead(Usuarios,1)
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("usuarios"),(long)1);

// IF Usuarios.Usuario=usuario AND Usuarios.Clave=clave THEN
if((WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("usuario").opEgal(vWD_usuario) & WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("clave").opEgal(vWD_clave)))
{
// 	HRead(Parametros,1)
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("parametros"),(long)1);

// Erreur sur l'objet: COL_GlobalProcedures
// 	Traitement : Global_Validar_usuario (0)
// 	Code: 403
// 	Message: idpromotor item not found in Parametros file.
// 	Ligne : 35, Colonne : 12
// 
// 
WDErreurManager.erreurGeneration("Erreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Global_Validar_usuario (0)\r\n\tCode: 403\r\n\tMessage: idpromotor item not found in Parametros file.\r\n\tLigne : 35, Colonne : 12\r\n\r\n");


// // 	Parametros.idpromotor=Usuarios.idpromotor
// 

// // Erreur sur l'objet: COL_GlobalProcedures
// // 	Traitement : Global_Validar_usuario (0)
// // 	Code: 403
// // 	Message: fecha_acceso item not found in Parametros file.
// // 	Ligne : 36, Colonne : 12
// // 
// // 
// WDErreurManager.erreurGeneration("Erreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Global_Validar_usuario (0)\r\n\tCode: 403\r\n\tMessage: fecha_acceso item not found in Parametros file.\r\n\tLigne : 36, Colonne : 12\r\n\r\n");
// 
// 
// // // 	Parametros.fecha_acceso=Today()
// // 
// 
// // Erreur sur l'objet: COL_GlobalProcedures
// // 	Traitement : Global_Validar_usuario (0)
// // 	Code: 403
// // 	Message: hora_acceso item not found in Parametros file.
// // 	Ligne : 37, Colonne : 12
// // 
// // 
// WDErreurManager.erreurGeneration("Erreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Global_Validar_usuario (0)\r\n\tCode: 403\r\n\tMessage: hora_acceso item not found in Parametros file.\r\n\tLigne : 37, Colonne : 12\r\n\r\n");
// 
// 
// // // 	Parametros.hora_acceso=Now()
// // 
// 
// // 	HSave(Parametros)
// WDAPIHF.hEnregistre(WDAPIHF.getFichierSansCasseNiAccent("parametros"));
// 
// // 	IF gnaccesodatos=0 THEN
// if(GWDPQR.ms_Project.vWD_gnaccesodatos.opEgal(0))
// {
// // 		Info("")
// WDAPIDialogue.info(WDChaineMultilangue.getString("", "Tiene datos sin Enviar, proceda primero")
// );
// 
// }
// 
}
else
{
// 	Info("NO se puede validar cuentas de usuario en el Proveedor")
WDAPIDialogue.info("NO se puede validar cuentas de usuario en el Proveedor");

// 	RESULT -1
return new WDEntier(-1);

}

// RESULT 1
return new WDEntier(1);

}
finally
{
finExecProcGlobale();
}

}


static public WDObjet fWD_global_Sql_Record( WDObjet vWD_purl , WDObjet vWD_Pservidor , WDObjet vWD_pinstancia , WDObjet vWD_pbasededatos , WDObjet vWD_pusuario , WDObjet vWD_pclave , WDObjet vWD_ptabla , WDObjet vWD_ptipo , WDObjet vWD_pcampos , WDObjet vWD_pvalores , WDObjet vWD_pwhere , WDObjet vWD_pidinsert )
{
initExecProcGlobale("Global_Sql_Record");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_v1 = WDVarNonAllouee.ref;
WDObjet vWD_v2 = WDVarNonAllouee.ref;
WDObjet vWD_sResultado = new WDChaineU();

WDObjet vWD_n = new WDEntier();

WDObjet vWD_m = new WDEntier();



vWD_purl = WDParametre.traiterParametre(vWD_purl, 1, false, 16);

vWD_Pservidor = WDParametre.traiterParametre(vWD_Pservidor, 2, false, 16);

vWD_pinstancia = WDParametre.traiterParametre(vWD_pinstancia, 3, false, 16);

vWD_pbasededatos = WDParametre.traiterParametre(vWD_pbasededatos, 4, false, 16);

vWD_pusuario = WDParametre.traiterParametre(vWD_pusuario, 5, false, 16);

vWD_pclave = WDParametre.traiterParametre(vWD_pclave, 6, false, 16);

vWD_ptabla = WDParametre.traiterParametre(vWD_ptabla, 7, false, 16);

vWD_ptipo = WDParametre.traiterParametre(vWD_ptipo, 8, false, 16);

vWD_pcampos = WDParametre.traiterParametre(vWD_pcampos, 9, false, 16);

vWD_pvalores = WDParametre.traiterParametre(vWD_pvalores, 10, false, 16);

vWD_pwhere = WDParametre.traiterParametre(vWD_pwhere, 11, false, 16);

vWD_pidinsert = WDParametre.traiterParametre(vWD_pidinsert, 12, false, 16);


// WSDataSQLService..Address=purl
WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").setProp(EWDPropriete.PROP_ADRESSE,vWD_purl);

// v1 is SQLRecord
vWD_v1 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "SQLRecord") );


// v2 is SQLRecordResponse
vWD_v2 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "SQLRecordResponse") );


// sResultado is string


// v1.usuario=pusuario
vWD_v1.get("usuario").setValeur(vWD_pusuario);

// v1.clave=pclave
vWD_v1.get("clave").setValeur(vWD_pclave);

// v1.servidor=Pservidor
vWD_v1.get("servidor").setValeur(vWD_Pservidor);

// v1.instancia=pinstancia
vWD_v1.get("instancia").setValeur(vWD_pinstancia);

// v1.basededatos=pbasededatos
vWD_v1.get("basededatos").setValeur(vWD_pbasededatos);

// v1.tabla=ptabla
vWD_v1.get("tabla").setValeur(vWD_ptabla);

// v1.campos=NoRightCharacter(pcampos,",")
vWD_v1.get("campos").setValeur(WDAPIChaine.sansCaractereDroite(vWD_pcampos.getString(),","));

// v1.tipo=ptipo
vWD_v1.get("tipo").setValeur(vWD_ptipo);

// v1.valores=pvalores
vWD_v1.get("valores").setValeur(vWD_pvalores);

// v1.where=pwhere
vWD_v1.get("where").setValeur(vWD_pwhere);

// v1.id=pidinsert
vWD_v1.get("id").setValeur(vWD_pidinsert);

// v2=SQLRecord(v1)
vWD_v2.setValeur(WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").invoquerMethode("SQLRecord", new WDObjet[] {vWD_v1} ));

// n is int=0

vWD_n.setValeur(0);


// m is int=0

vWD_m.setValeur(0);


// sResultado=v2.SQLRecordResult
vWD_sResultado.setValeur(vWD_v2.get("SQLRecordResult"));

// RESULT sResultado
return vWD_sResultado;

}
finally
{
finExecProcGlobale();
}

}


static public WDObjet fWD_llenar_Where( WDObjet vWD_sDestino )
{
initExecProcGlobale("Llenar_Where");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_m = new WDEntier();

WDObjet vWD_sWherelocal = new WDChaineU();



vWD_sDestino = WDParametre.traiterParametre(vWD_sDestino, 1, false, 16);


// sParametros=""
GWDPQR.ms_Project.vWD_sParametros.setValeur("");

// gsSqlwhere=""
GWDPQR.ms_Project.vWD_gsSqlwhere.setValeur("");

// m is int=0

vWD_m.setValeur(0);


// sWherelocal is string = "Interface.Bdlocal='"+sfile+"' and Interface.Bddestino='"+sDestino+"'"

vWD_sWherelocal.setValeur(new WDChaineU("Interface.Bdlocal='").opPlus(GWDPQR.ms_Project.vWD_sfile).opPlus("' and Interface.Bddestino='").opPlus(vWD_sDestino).opPlus("'"));


// FOR EACH Interface where sWherelocal 
IWDParcours parcours5 = null;
try
{
parcours5 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("interface"), null, vWD_sWherelocal.getString(), true);
while(parcours5.testParcours())
{
// 	IF Interface.Bdlocal=sfile AND Interface.Bddestino=sDestino AND Interface.Llave=True THEN
if(((WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("bdlocal").opEgal(GWDPQR.ms_Project.vWD_sfile) & WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("bddestino").opEgal(vWD_sDestino)) & WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("llave").opEgal(true)))
{
// 		m=m + 1 
vWD_m.setValeur(vWD_m.opPlus(1));

// 		sParametros=sParametros+Interface.Bdlocal+"."+Interface.campolocal+"|"
GWDPQR.ms_Project.vWD_sParametros.setValeur(GWDPQR.ms_Project.vWD_sParametros.opPlus(WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("bdlocal")).opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campolocal")).opPlus("|"));

// 		IF gsSqlwhere<>"" THEN
if(GWDPQR.ms_Project.vWD_gsSqlwhere.opDiff(""))
{
// 			gsSqlwhere=gsSqlwhere+" and "
GWDPQR.ms_Project.vWD_gsSqlwhere.setValeur(GWDPQR.ms_Project.vWD_gsSqlwhere.opPlus(" and "));

}

// 		gsSqlwhere=gsSqlwhere+Interface.campodestino+" = "
GWDPQR.ms_Project.vWD_gsSqlwhere.setValeur(GWDPQR.ms_Project.vWD_gsSqlwhere.opPlus(WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campodestino")).opPlus(" = "));

// 		IF Interface.Tipodedato="S" OR Interface.Tipodedato="D" OR Interface.Tipodedato="T" THEN 
if(((WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato").opEgal("S") | WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato").opEgal("D")) | WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato").opEgal("T")))
{
// 			gsSqlwhere=gsSqlwhere+"'"
GWDPQR.ms_Project.vWD_gsSqlwhere.setValeur(GWDPQR.ms_Project.vWD_gsSqlwhere.opPlus("'"));

}

// 		gsSqlwhere=gsSqlwhere+"%"+NumToString(m)
GWDPQR.ms_Project.vWD_gsSqlwhere.setValeur(GWDPQR.ms_Project.vWD_gsSqlwhere.opPlus("%").opPlus(WDAPINum.numeriqueVersChaine(vWD_m)));

// 		IF Interface.Tipodedato="S" OR Interface.Tipodedato="D" OR Interface.Tipodedato="T" THEN 
if(((WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato").opEgal("S") | WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato").opEgal("D")) | WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato").opEgal("T")))
{
// 			gsSqlwhere=gsSqlwhere+"'"
GWDPQR.ms_Project.vWD_gsSqlwhere.setValeur(GWDPQR.ms_Project.vWD_gsSqlwhere.opPlus("'"));

}

// 		gsSqlwhere=gsSqlwhere+"  "
GWDPQR.ms_Project.vWD_gsSqlwhere.setValeur(GWDPQR.ms_Project.vWD_gsSqlwhere.opPlus("  "));

}

}
}
finally
{
if(parcours5 != null)
{
parcours5.finParcours();
}
}


// IF sParametros="" //ssqlwhereparam=""
if(GWDPQR.ms_Project.vWD_sParametros.opEgal(""))
{
// 	RESULT False
return new WDBooleen(false);

}

// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcGlobale();
}

}


static public void fWD_crear_campos_update()
{
initExecProcGlobale("Crear_campos_update");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_k = new WDEntier();



// k is int =ArrayCount(sCampos)

vWD_k.setValeur(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCampos));


// sListacampos = ""
GWDPQR.ms_Project.vWD_sListacampos.setValeur("");

// FOR li=1 TO k
for(WDObjet vWD_li = new WDEntier(1);vWD_li.opInfEgal(vWD_k);vWD_li.opInc())
{
// 	sListacampos= sListacampos+sCamposExt[li]+" = "
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus(GWDPQR.ms_Project.vWD_sCamposExt.get(vWD_li)).opPlus(" = "));

// 	IF sTipos[li]<>"N" THEN
if(GWDPQR.ms_Project.vWD_sTipos.get(vWD_li).opDiff("N"))
{
// 		sListacampos=sListacampos+"'"
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus("'"));

}

// 	sListacampos=sListacampos+{sfile+"."+sCampos[li]}
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_sCampos.get(vWD_li)).getString())));

// 	IF sTipos[li]<>"N" THEN
if(GWDPQR.ms_Project.vWD_sTipos.get(vWD_li).opDiff("N"))
{
// 		sListacampos=sListacampos+"'"
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus("'"));

}

// 	IF li<k THEN 
if(vWD_li.opInf(vWD_k))
{
// 		sListacampos=sListacampos+","
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus(","));

}

}

}
finally
{
finExecProcGlobale();
}

}


static public void fWD_crear_campos_insert()
{
initExecProcGlobale("Crear_campos_insert");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_k = new WDEntier();

WDObjet vWD_sfecha = new WDChaineU();

WDObjet vWD_sTime = new WDChaineU();



// k is int =ArrayCount(sCampos)

vWD_k.setValeur(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCampos));


// sListacampos = ""
GWDPQR.ms_Project.vWD_sListacampos.setValeur("");

// sListavalores=""
GWDPQR.ms_Project.vWD_sListavalores.setValeur("");

// sfecha is string=""

vWD_sfecha.setValeur("");


// sTime is string=""

vWD_sTime.setValeur("");


// FOR li=1 TO k
for(WDObjet vWD_li = new WDEntier(1);vWD_li.opInfEgal(vWD_k);vWD_li.opInc())
{
// 	sListacampos= sListacampos+sCamposExt[li]+""
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus(GWDPQR.ms_Project.vWD_sCamposExt.get(vWD_li)).opPlus(""));

// 	IF sTipos[li]<>"N" THEN
if(GWDPQR.ms_Project.vWD_sTipos.get(vWD_li).opDiff("N"))
{
// 		sListavalores=sListavalores+"'"
GWDPQR.ms_Project.vWD_sListavalores.setValeur(GWDPQR.ms_Project.vWD_sListavalores.opPlus("'"));

}

// 	IF sTipos[li]="A" THEN
if(GWDPQR.ms_Project.vWD_sTipos.get(vWD_li).opEgal("A"))
{
// 		sfecha=DateToString({sfile+"."+sCampos[li]},"YYYYMMDD")
vWD_sfecha.setValeur(WDAPIDate.dateVersChaine(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_sCampos.get(vWD_li)).getString()),"YYYYMMDD"));

// 		sTime=TimeToString({sfile+"."+sCampos[li]},"HH:MM:SS")
vWD_sTime.setValeur(WDAPIDate.heureVersChaine(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_sCampos.get(vWD_li)).getString()),"HH:MM:SS"));

// 		sListavalores= sListavalores+sfecha+" "+sTime
GWDPQR.ms_Project.vWD_sListavalores.setValeur(GWDPQR.ms_Project.vWD_sListavalores.opPlus(vWD_sfecha).opPlus(" ").opPlus(vWD_sTime));

}
else
{
// 		sListavalores= sListavalores+{sfile+"."+sCampos[li]}
GWDPQR.ms_Project.vWD_sListavalores.setValeur(GWDPQR.ms_Project.vWD_sListavalores.opPlus(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_sCampos.get(vWD_li)).getString())));

}

// 	IF sTipos[li]<>"N" THEN
if(GWDPQR.ms_Project.vWD_sTipos.get(vWD_li).opDiff("N"))
{
// 		sListavalores=sListavalores+"'"
GWDPQR.ms_Project.vWD_sListavalores.setValeur(GWDPQR.ms_Project.vWD_sListavalores.opPlus("'"));

}

// 		sListacampos=sListacampos+","
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus(","));

// 		sListavalores=sListavalores+","
GWDPQR.ms_Project.vWD_sListavalores.setValeur(GWDPQR.ms_Project.vWD_sListavalores.opPlus(","));

}

// k  =ArrayCount(scamposlocales)
vWD_k.setValeur(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_scamposlocales));

// FOR li=1 TO k
for(WDObjet vWD_li = new WDEntier(1);vWD_li.opInfEgal(vWD_k);vWD_li.opInc())
{
// 	sListacampos= sListacampos+scamposlocales[li]+""
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus(GWDPQR.ms_Project.vWD_scamposlocales.get(vWD_li)).opPlus(""));

// 	IF sTiposlocales[li]<>"N" THEN
if(GWDPQR.ms_Project.vWD_sTiposlocales.get(vWD_li).opDiff("N"))
{
// 		sListavalores=sListavalores+"'"
GWDPQR.ms_Project.vWD_sListavalores.setValeur(GWDPQR.ms_Project.vWD_sListavalores.opPlus("'"));

}

// 	sListavalores= sListavalores+sValoreslocales[li]
GWDPQR.ms_Project.vWD_sListavalores.setValeur(GWDPQR.ms_Project.vWD_sListavalores.opPlus(GWDPQR.ms_Project.vWD_sValoreslocales.get(vWD_li)));

// 	IF sTiposlocales[li]<>"N" THEN
if(GWDPQR.ms_Project.vWD_sTiposlocales.get(vWD_li).opDiff("N"))
{
// 		sListavalores=sListavalores+"'"
GWDPQR.ms_Project.vWD_sListavalores.setValeur(GWDPQR.ms_Project.vWD_sListavalores.opPlus("'"));

}

// 	sListacampos=sListacampos+","
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus(","));

// 	sListavalores=sListavalores+","
GWDPQR.ms_Project.vWD_sListavalores.setValeur(GWDPQR.ms_Project.vWD_sListavalores.opPlus(","));

}

// sListacampos=NoRightCharacter(sListacampos,",")
GWDPQR.ms_Project.vWD_sListacampos.setValeur(WDAPIChaine.sansCaractereDroite(GWDPQR.ms_Project.vWD_sListacampos.getString(),","));

// sListavalores=NoRightCharacter(sListavalores,",")
GWDPQR.ms_Project.vWD_sListavalores.setValeur(WDAPIChaine.sansCaractereDroite(GWDPQR.ms_Project.vWD_sListavalores.getString(),","));

}
finally
{
finExecProcGlobale();
}

}


static public WDObjet fWD_llenar_Campos_sin_llave( WDObjet vWD_sDestino )
{
initExecProcGlobale("Llenar_Campos_sin_llave");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_sWherelocal = new WDChaineU();



vWD_sDestino = WDParametre.traiterParametre(vWD_sDestino, 1, false, 16);


// sListacampos=""
GWDPQR.ms_Project.vWD_sListacampos.setValeur("");

// sWherelocal is string = "Interface.Bdlocal='"+sfile+"' and Interface.Bddestino='"+sDestino+"'"

vWD_sWherelocal.setValeur(new WDChaineU("Interface.Bdlocal='").opPlus(GWDPQR.ms_Project.vWD_sfile).opPlus("' and Interface.Bddestino='").opPlus(vWD_sDestino).opPlus("'"));


// FOR EACH Interface where sWherelocal 
IWDParcours parcours6 = null;
try
{
parcours6 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("interface"), null, vWD_sWherelocal.getString(), true);
while(parcours6.testParcours())
{
// 		IF  Interface.Llave=False THEN
if(WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("llave").opEgal(false))
{
// 			Add(sCampos,Interface.campolocal)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sCampos,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campolocal"));

// 			Add(sCamposExt,Interface.campodestino)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sCamposExt,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campodestino"));

// 			sListacampos +=Interface.campodestino+","
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus(WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campodestino").opPlus(",")));

// 			Add(sTipos,Interface.Tipodedato)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sTipos,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato"));

}
else if((WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campolocal").opEgal("") & WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("defecto").opDiff("")))
{
// 			Add(scamposlocales,Interface.campolocal)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_scamposlocales,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("campolocal"));

// 			Add(sTiposlocales,Interface.Tipodedato)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sTiposlocales,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("tipodedato"));

// 			Add(sValoreslocales,Interface.Defecto)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sValoreslocales,WDAPIHF.getFichierSansCasseNiAccent("interface").getRubriqueSansCasseNiAccent("defecto"));

}

}
}
finally
{
if(parcours6 != null)
{
parcours6.finParcours();
}
}


// IF ArrayCount(sCampos)=0 AND ArrayCount(scamposlocales)=0 THEN
if((WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCampos).opEgal(0) & WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_scamposlocales).opEgal(0)))
{
// 	RESULT False
return new WDBooleen(false);

}

// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcGlobale();
}

}


static public WDObjet fWD_global_Leer_Datos_Previos()
{
initExecProcGlobale("Global_Leer_Datos_Previos");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_j = new WDEntier();

WDObjet vWD_i = new WDEntier();

WDObjet vWD_res = new WDBooleen();



// j is int


// i is int 


// res is boolean


// FOR EACH Tabla_interface  where direccion="P"
IWDParcours parcours7 = null;
try
{
parcours7 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"), WDAPIHF.getRubriqueSansCasseNiAccent("direccion"), new WDChaineU("P"), 1, true);
while(parcours7.testParcours())
{
// 		sfile=Tabla_interface.Bdlocal
GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal"));

// 		res=HDeleteAll(sfile)
vWD_res.setValeur(WDAPIHF.hSupprimeTout(GWDPQR.ms_Project.vWD_sfile));

// 		i=HNbRec(sfile)
vWD_i.setValeur(WDAPIHF.hNbEnr(GWDPQR.ms_Project.vWD_sfile));

// 		ArrayDeleteAll(sCampos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCampos);

// 		ArrayDeleteAll(sCamposExt)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCamposExt);

// 		ArrayDeleteAll(sTipos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTipos);

// 		ArrayDeleteAll(scamposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_scamposlocales);

// 		ArrayDeleteAll(sTiposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTiposlocales);

// 		ArrayDeleteAll(sValoreslocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sValoreslocales);

// 		sListacampos=""
GWDPQR.ms_Project.vWD_sListacampos.setValeur("");

// 		sWhere=Tabla_interface.stwhere
GWDPQR.ms_Project.vWD_sWhere.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("stwhere"));

// 		sParametros=Tabla_interface.parametros
GWDPQR.ms_Project.vWD_sParametros.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("parametros"));

// 		gsTablename=Tabla_interface.Bddestino
GWDPQR.ms_Project.vWD_gsTablename.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bddestino"));

// 		Procesar_parametros()
GWDCPCOL_GlobalProcedures.fWD_procesar_parametros();

// 		Llenar_campos(gsTablename)
GWDCPCOL_GlobalProcedures.fWD_llenar_campos(GWDPQR.ms_Project.vWD_gsTablename);

// 		IF ArrayCount(sCampos)=0 THEN
if(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCampos).opEgal(0))
{
// 			RESULT False
return new WDBooleen(false);

}

// 		Global_Leer_Tabla_comp()
GWDCPCOL_GlobalProcedures.fWD_global_Leer_Tabla_comp();

}
}
finally
{
if(parcours7 != null)
{
parcours7.finParcours();
}
}


// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcGlobale();
}

}


static public WDObjet fWD_global_Borrar_datos_locales()
{
initExecProcGlobale("Global_Borrar_datos_locales");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_j = new WDEntier();

WDObjet vWD_b = new WDBooleen();



// j is int


// b is boolean


// b=Global_revisar_datos_sin_enviar()
vWD_b.setValeur(GWDCPCOL_GlobalProcedures.fWD_global_revisar_datos_sin_enviar());

// IF b=False THEN
if(vWD_b.opEgal(false))
{
// 	gnaccesodatos=0
GWDPQR.ms_Project.vWD_gnaccesodatos.setValeur(0);

// 	RESULT False
return new WDBooleen(false);

}
else
{
// 	gnaccesodatos=1
GWDPQR.ms_Project.vWD_gnaccesodatos.setValeur(1);

}

// FOR EACH Tabla_interface  where direccion="I"
IWDParcours parcours8 = null;
try
{
parcours8 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"), WDAPIHF.getRubriqueSansCasseNiAccent("direccion"), new WDChaineU("I"), 1, true);
while(parcours8.testParcours())
{
// 		IF Tabla_interface.borrardatos="S" THEN
if(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("borrardatos").opEgal("S"))
{
// 			sfile=Tabla_interface.Bdlocal
GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal"));

// 			HDeleteAll(sfile)  
WDAPIHF.hSupprimeTout(GWDPQR.ms_Project.vWD_sfile);

}

}
}
finally
{
if(parcours8 != null)
{
parcours8.finParcours();
}
}


// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcGlobale();
}

}


static public WDObjet fWD_global_uploadimagebase64( WDObjet vWD_philera , WDObjet vWD_pfilename )
{
initExecProcGlobale("Global_uploadimagebase64");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_v1 = WDVarNonAllouee.ref;
WDObjet vWD_v2 = WDVarNonAllouee.ref;
WDObjet vWD_sResultado = new WDChaineU();



vWD_philera = WDParametre.traiterParametre(vWD_philera, 1, false, 16);

vWD_pfilename = WDParametre.traiterParametre(vWD_pfilename, 2, false, 16);


// WSDataSQLService..Address=Parametros.wsutrl
WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").setProp(EWDPropriete.PROP_ADRESSE,WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("wsutrl"));

// v1 is UploadImageBase64
vWD_v1 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "UploadImageBase64") );


// v2 is UploadImageBase64Response
vWD_v2 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "UploadImageBase64Response") );


// sResultado is string


// Erreur sur l'objet: COL_GlobalProcedures
// 	Traitement : Global_uploadimagebase64 (0)
// 	Code: 403
// 	Message: folderimagenes item not found in Parametros file.
// 	Ligne : 7, Colonne : 19
// 
// 
WDErreurManager.erreurGeneration("Erreur sur l'objet: COL_GlobalProcedures\r\n\tTraitement : Global_uploadimagebase64 (0)\r\n\tCode: 403\r\n\tMessage: folderimagenes item not found in Parametros file.\r\n\tLigne : 7, Colonne : 19\r\n\r\n");


// // v1.path=Parametros.folderimagenes
// vWD_v1.get("path").setValeur();
// 

// // v1.ImgStr=philera
// vWD_v1.get("ImgStr").setValeur(vWD_philera);
// 
// // v1.ImageName=pfilename
// vWD_v1.get("ImageName").setValeur(vWD_pfilename);
// 
// // v2=UploadImageBase64(v1)
// vWD_v2.setValeur(WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").invoquerMethode("UploadImageBase64", new WDObjet[] {vWD_v1} ));
// 
// // RESULT sResultado
// return vWD_sResultado;
// 
return new WDVoid("fWD_global_uploadimagebase64");
}
finally
{
finExecProcGlobale();
}

}


static public WDObjet fWD_llenar_Campos_sin_llave_img( WDObjet vWD_sDestino )
{
initExecProcGlobale("Llenar_Campos_sin_llave_img");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_sWherelocal = new WDChaineU();



vWD_sDestino = WDParametre.traiterParametre(vWD_sDestino, 1, false, 16);


// sListacampos=""
GWDPQR.ms_Project.vWD_sListacampos.setValeur("");

// sWherelocal is string = "InterfaseImagen.tablalocal='"+sfile+"' "  // and Interface.Bddestino='"+sDestino+"'"

vWD_sWherelocal.setValeur(new WDChaineU("InterfaseImagen.tablalocal='").opPlus(GWDPQR.ms_Project.vWD_sfile).opPlus("' "));


// FOR EACH InterfaseImagen where sWherelocal 
IWDParcours parcours9 = null;
try
{
parcours9 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen"), null, vWD_sWherelocal.getString(), true);
while(parcours9.testParcours())
{
// 	IF InterfaseImagen.tablalocal=sfile AND InterfaseImagen.tabladestino=sDestino THEN
if((WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("tablalocal").opEgal(GWDPQR.ms_Project.vWD_sfile) & WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("tabladestino").opEgal(vWD_sDestino)))
{
// 		IF InterfaseImagen.tipodato="I" THEN
if(WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("tipodato").opEgal("I"))
{
// 			Add(sCamposimg,InterfaseImagen.campoorigen)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sCamposimg,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("campoorigen"));

// 			Add(sCamposExtimg,InterfaseImagen.campodestino)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sCamposExtimg,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("campodestino"));

// 				add(sParametrosimg,InterfaseImagen.prm_nombre_arch)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sParametrosimg,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("prm_nombre_arch"));

// 				add(sValParametrosimg,InterfaseImagen.vprm_nombre_arch)	
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sValParametrosimg,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("vprm_nombre_arch"));

// 			Add(scamposlocales,InterfaseImagen.camponombrearchivo)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_scamposlocales,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("camponombrearchivo"));

// 			Add(sTiposlocales,"S")
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sTiposlocales,new WDChaineU("S"));

// 			Add(sValoreslocales,"%"+ArrayCount(scamposimg))//InterfaseImagen.camponombrearchivo)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sValoreslocales,new WDChaineU("%").opPlus(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCamposimg)));

}
else if(((WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("llave").opEgal(false) & WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("campoorigen").opDiff("")) & WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("campodestino").opDiff("")))
{
// 			Add(sCampos,InterfaseImagen.campoORIGEN)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sCampos,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("campoorigen"));

// 			Add(sCamposExt,InterfaseImagen.campodestino)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sCamposExt,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("campodestino"));

// 			sListacampos +=InterfaseImagen.campodestino+","
GWDPQR.ms_Project.vWD_sListacampos.setValeur(GWDPQR.ms_Project.vWD_sListacampos.opPlus(WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("campodestino").opPlus(",")));

// 			Add(sTipos,InterfaseImagen.Tipodato)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sTipos,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("tipodato"));

}
else if((WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("campoorigen").opEgal("") & WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("defecto").opDiff("")))
{
// 			Add(scamposlocales,InterfaseImagen.campodestino)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_scamposlocales,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("campodestino"));

// 			Add(sTiposlocales,InterfaseImagen.Tipodato)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sTiposlocales,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("tipodato"));

// 			Add(sValoreslocales,InterfaseImagen.Defecto)
WDAPICollection.ajoute(GWDPQR.ms_Project.vWD_sValoreslocales,WDAPIHF.getFichierSansCasseNiAccent("interfaseimagen").getRubriqueSansCasseNiAccent("defecto"));

}

}

}
}
finally
{
if(parcours9 != null)
{
parcours9.finParcours();
}
}


// IF ArrayCount(sCampos)=0 AND ArrayCount(scamposlocales)=0 THEN
if((WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCampos).opEgal(0) & WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_scamposlocales).opEgal(0)))
{
// 	RESULT False
return new WDBooleen(false);

}

// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcGlobale();
}

}


static public void fWD_procesar_Parametros_var( WDObjet vWD_slista , WDObjet vWD_svalor )
{
initExecProcGlobale("Procesar_Parametros_var");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_li = new WDEntier();

WDObjet vWD_k = new WDEntier();



vWD_slista = WDParametre.traiterParametre(vWD_slista, 1, false, 16);

vWD_svalor = WDParametre.traiterParametre(vWD_svalor, 2, false, 16);


// li is int


// k is int


// IF slista<>"" AND Contains(slista,"%")  THEN
if((vWD_slista.opDiff("") & WDAPIChaine.contient(vWD_slista,new WDChaineU("%")).getBoolean()))
{
// 	slista=StringBuild(slista, svalor)
vWD_slista.setValeur(WDAPIChaine.chaineConstruit(vWD_slista,vWD_svalor));

}

}
finally
{
finExecProcGlobale();
}

}


static public WDObjet fWD_global_revisar_datos_sin_enviar()
{
initExecProcGlobale("Global_revisar_datos_sin_enviar");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_j = new WDEntier();



// j is int


// for EACH Tabla_interface  WHERE direccion="O"
IWDParcours parcours10 = null;
try
{
parcours10 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"), WDAPIHF.getRubriqueSansCasseNiAccent("direccion"), new WDChaineU("O"), 1, true);
while(parcours10.testParcours())
{
// 	sfile=Tabla_interface.Bdlocal
GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal"));

// 	HSeekFirst(sfile,"esnuevo",1)
WDAPIHF.hRecherchePremier(GWDPQR.ms_Project.vWD_sfile,new WDChaineU("esnuevo"),new WDEntier(1));

// 	if hfound()=true THEN
if(WDAPIHF.hTrouve().opEgal(true))
{
// 		RESULT false
return new WDBooleen(false);

}

// 	HSeekFirst(sfile,"esmodificado",1)
WDAPIHF.hRecherchePremier(GWDPQR.ms_Project.vWD_sfile,new WDChaineU("esmodificado"),new WDEntier(1));

// 	IF HFound()=True THEN
if(WDAPIHF.hTrouve().opEgal(true))
{
// 		RESULT False
return new WDBooleen(false);

}

}
}
finally
{
if(parcours10 != null)
{
parcours10.finParcours();
}
}


// FOR EACH Tabla_InterfaseImagen  WHERE direccion="O"
IWDParcours parcours11 = null;
try
{
parcours11 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen"), WDAPIHF.getRubriqueSansCasseNiAccent("direccion"), new WDChaineU("O"), 1, true);
while(parcours11.testParcours())
{
// 	sfile=Tabla_InterfaseImagen.Bdlocal
GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("bdlocal"));

// 	HSeekFirst(sfile,"m_esnuevo",1)
WDAPIHF.hRecherchePremier(GWDPQR.ms_Project.vWD_sfile,new WDChaineU("m_esnuevo"),new WDEntier(1));

// 	IF HFound()=True THEN
if(WDAPIHF.hTrouve().opEgal(true))
{
// 		RESULT False
return new WDBooleen(false);

}

// 	HSeekFirst(sfile,"m_esmodificado",1)
WDAPIHF.hRecherchePremier(GWDPQR.ms_Project.vWD_sfile,new WDChaineU("m_esmodificado"),new WDEntier(1));

// 	IF HFound()=True THEN
if(WDAPIHF.hTrouve().opEgal(true))
{
// 		RESULT False
return new WDBooleen(false);

}

}
}
finally
{
if(parcours11 != null)
{
parcours11.finParcours();
}
}


// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcGlobale();
}

}



////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
