/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Fenêtre
 * Android class: WIN_Enviar_Datos
 * Date: 14/09/2018 02:54:17
 * Version of wdjava.dll: 22.0.106.0
 */


package com.mycompany.qr.wdgen;


import com.mycompany.qr.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.ui.champs.fenetre.*;
import fr.pcsoft.wdjava.ui.champs.jauge.*;
import fr.pcsoft.wdjava.ui.cadre.*;
import fr.pcsoft.wdjava.ui.champs.bouton.*;
import fr.pcsoft.wdjava.api.*;
import fr.pcsoft.wdjava.core.erreur.*;
import fr.pcsoft.wdjava.core.parcours.*;
import fr.pcsoft.wdjava.core.parcours.hf.*;
import fr.pcsoft.wdjava.core.types.collection.tableau.*;
import fr.pcsoft.wdjava.core.application.*;
import fr.pcsoft.wdjava.ui.actionbar.*;
import fr.pcsoft.wdjava.ui.activite.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/



public class GWDFWIN_Enviar_Datos extends WDFenetre
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs de WIN_Enviar_Datos
////////////////////////////////////////////////////////////////////////////

/**
 * PROGBAR_Subire
 */
class GWDPROGBAR_Subire extends WDJaugeInfinie
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°1 de WIN_Enviar_Datos.PROGBAR_Subire
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(3082667185778312432l);

super.setChecksum("869950385");

super.setNom("PROGBAR_Subire");

super.setType(113);

super.setLibelle("Progress bar");

super.setNote("", "");

super.setEtatInitial(0);

super.setPositionInitiale(141, 29);

super.setTailleInitiale(41, 40);

super.setPlan(0);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(false);

super.setAltitude(1);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setTauxParallaxe(0, 0);

super.setPresenceLibelle(false);

super.setStyleLibelle(0x0, creerPolice_GEN("MS Shell Dlg", -11.000000, 0), -1, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xF1000000, 0xF3000000, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
protected int getTypeJauge()
{
return 1;
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDPROGBAR_Subire mWD_PROGBAR_Subire;

/**
 * BTN_Subir1
 */
class GWDBTN_Subir1 extends WDBouton
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°2 de WIN_Enviar_Datos.BTN_Subir1
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(3082667185778377968l);

super.setChecksum("869966217");

super.setNom("BTN_Subir1");

super.setType(4);

super.setLibelle("Enviar");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(27, 34);

super.setTailleInitiale(101, 35);

super.setPlan(0);

super.setImageEtat(1);

super.setImageFondEtat(5);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(2);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setNumTab(2);

super.setLettreAppel(65535);

super.setTypeBouton(0);

super.setTypeActionPredefinie(0);

super.setBoutonOnOff(false);

super.setTauxParallaxe(0, 0);

super.setLibelleVAlign(1);

super.setLibelleHAlign(4);

super.setPresenceLibelle(true);

super.setImage("", 0, 2, 1, null, null, null);

super.setStyleLibelleRepos(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleSurvol(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleEnfonce(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setCadreRepos(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xE6E6E6, 4, 4, 1, 1));

super.setCadreSurvol(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xE6E6E6, 4, 4, 1, 1));

super.setCadreEnfonce(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xE6E6E6, 4, 4, 1, 1));

super.setImageFond9Images(new int[] {1,4,1,2,2,2,1,4,1}, 10, 10, 8, 8);

super.setImageFond("", 1, 0, 1, 1);

activerEcoute();
super.terminerInitialisation();
}

/**
 * Traitement: Click BTN_Subir1
 */
public void clicSurBoutonGauche()
// 
// iFont sUserOptions:sServerName ="" then
// 	Error("Debe tener opciones de configuración")
// 	return 
// END
// 
// 
{
super.clicSurBoutonGauche();


////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_bPasos = new WDBooleen();

WDObjet vWD_i = new WDEntier();



// HRead(Parametros,1)
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("parametros"),(long)1);

// PROGBAR_Subire..Visible = True
mWD_PROGBAR_Subire.setVisible(true);

// bPasos is boolean =true

vWD_bPasos.setValeur(true);


// i is int=0

vWD_i.setValeur(0);


// bPasos=Enviar_Datos_WS()
vWD_bPasos.setValeur(fWD_enviar_Datos_WS());

// IF bPasos=False THEN 
if(vWD_bPasos.opEgal(false))
{
// 	Regresar()
fWD_regresar();

// 	RETURN 
return;

}

// bPasos=Enviar_imagenes_ws()
vWD_bPasos.setValeur(fWD_enviar_imagenes_ws());

// IF bPasos=False THEN 
if(vWD_bPasos.opEgal(false))
{
// 	Regresar()
fWD_regresar();

// 	RETURN 
return;

}

// bPasos=Global_revisar_datos_sin_enviar()
vWD_bPasos.setValeur(GWDCPCOL_GlobalProcedures.fWD_global_revisar_datos_sin_enviar());

// if gnaccesodatos=1 then
if(GWDPQR.ms_Project.vWD_gnaccesodatos.opEgal(1))
{
// Erreur sur l'objet: WIN_Enviar_Datos.BTN_Subir1
// 	Traitement : Click BTN_Subir1 (18)
// 	Code: 403
// 	Message: fecha_acceso item not found in Parametros file.
// 	Ligne : 29, Colonne : 12
// 
// 
WDErreurManager.erreurGeneration("Erreur sur l'objet: WIN_Enviar_Datos.BTN_Subir1\r\n\tTraitement : Click BTN_Subir1 (18)\r\n\tCode: 403\r\n\tMessage: fecha_acceso item not found in Parametros file.\r\n\tLigne : 29, Colonne : 12\r\n\r\n");


// // 	Parametros.fecha_acceso=Today()
// 

// // Erreur sur l'objet: WIN_Enviar_Datos.BTN_Subir1
// // 	Traitement : Click BTN_Subir1 (18)
// // 	Code: 403
// // 	Message: hora_acceso item not found in Parametros file.
// // 	Ligne : 30, Colonne : 12
// // 
// // 
// WDErreurManager.erreurGeneration("Erreur sur l'objet: WIN_Enviar_Datos.BTN_Subir1\r\n\tTraitement : Click BTN_Subir1 (18)\r\n\tCode: 403\r\n\tMessage: hora_acceso item not found in Parametros file.\r\n\tLigne : 30, Colonne : 12\r\n\r\n");
// 
// 
// // // 	Parametros.hora_acceso=Now()
// // 
// 
// // 	hsave(Parametros)
// WDAPIHF.hEnregistre(WDAPIHF.getFichierSansCasseNiAccent("parametros"));
// 
}

// Regresar()
fWD_regresar();

// ToastDisplay("Proceso finalizado")
WDAPIToast.toastAffiche("Proceso finalizado");

// close()
WDAPIFenetre.ferme();

}




// Activation des écouteurs: 
public void activerEcoute()
{
super.activerEcouteurClic();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDBTN_Subir1 mWD_BTN_Subir1;

/**
 * BTN_Cancelar
 */
class GWDBTN_Cancelar extends WDBouton
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°3 de WIN_Enviar_Datos.BTN_Cancelar
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(3082667185778443504l);

super.setChecksum("870031753");

super.setNom("BTN_Cancelar");

super.setType(4);

super.setLibelle("Cancelar");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(193, 33);

super.setTailleInitiale(117, 36);

super.setPlan(0);

super.setImageEtat(5);

super.setImageFondEtat(5);

super.setTailleMin(0, 0);

super.setTailleMax(134217727, 134217727);

super.setVisibleInitial(true);

super.setAltitude(3);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setNumTab(1);

super.setLettreAppel(65535);

super.setTypeBouton(3);

super.setTypeActionPredefinie(0);

super.setBoutonOnOff(false);

super.setTauxParallaxe(0, 0);

super.setLibelleVAlign(1);

super.setLibelleHAlign(5);

super.setPresenceLibelle(true);

super.setImage("C:\\My Mobile Projects\\QR\\Templates\\WM\\200 ActivAndroid 5\\ActivAndroid 5_Pict_Cancel_16_5.png?E5", 0, 1, 5, null, null, null);

super.setStyleLibelleRepos(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleSurvol(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleEnfonce(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setCadreRepos(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xD4BC00, 4, 4, 1, 1));

super.setCadreSurvol(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xE8C6B0, 4, 4, 1, 1));

super.setCadreEnfonce(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xD4BC00, 4, 4, 1, 1));

super.setImageFond9Images(new int[] {1,2,1,2,2,2,1,2,1}, 8, 8, 8, 8);

super.setImageFond("C:\\My Mobile Projects\\QR\\Templates\\WM\\200 ActivAndroid 5\\ActivAndroid 5_BTN_Cancel.png?E5_3NP_8_8_8_8", 1, 0, 1, 1);

activerEcoute();
super.terminerInitialisation();
}

/**
 * Traitement: Click BTN_Cancelar
 */
public void clicSurBoutonGauche()
{
super.clicSurBoutonGauche();

// Close()
WDAPIFenetre.ferme();

}




// Activation des écouteurs: 
public void activerEcoute()
{
super.activerEcouteurClic();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDBTN_Cancelar mWD_BTN_Cancelar;


////////////////////////////////////////////////////////////////////////////
// Procédures utilisateur de WIN_Enviar_Datos
////////////////////////////////////////////////////////////////////////////
//  Summary: <specify the procedure action>
//  Syntax:
//  Regresar ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	None
// 
//  For instance:
//  Indicate an example.
// 
public void fWD_regresar()
{
initExecProcLocale("Regresar");


try
{
// HDeactivateFilter(Tabla_interface)
WDAPIHF.hDesactiveFiltre(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"));

// HDeactivateFilter(Interface)
WDAPIHF.hDesactiveFiltre(WDAPIHF.getFichierSansCasseNiAccent("interface"));

// PROGBAR_Subire..Visible = False 
mWD_PROGBAR_Subire.setVisible(false);

}
finally
{
finExecProcLocale();
}

}



//  Summary: <specify the procedure action>
//  Syntax:
// [ <Result> = ] Leer_Datos_WS ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	boolean: // 	None
// 
//  For instance:
//  Indicate an example.
// 
public WDObjet fWD_leer_Datos_WS()
{
initExecProcLocale("Leer_Datos_WS");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_j = new WDEntier();

WDObjet vWD_sFiledestino = new WDChaineU();



// 	j is int


// 	sFiledestino is string


// FOR j=1 _TO_ HNbRec( Tabla_interface )
// Délimiteur de visibilité pour ne pas étendre la visibilité des variables temporaires _WDExpBorneMax et _WDExpPas
{
WDObjet _WDExpBorneMax0 = new WDEntier8(WDAPIHF.hNbEnr(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface")));
for(vWD_j.setValeur(1);vWD_j.opInfEgal(_WDExpBorneMax0);vWD_j.opInc())
{
// HRead(Tabla_interface,j)	
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"),vWD_j.getLong());

// IF Tabla_interface.direccion="I" THEN
if(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("direccion").opEgal("I"))
{
// 	sfile=Tabla_interface.Bdlocal
GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal"));

// 	ToastDisplay("Paso 2."+j)
WDAPIToast.toastAffiche(new WDChaineU("Paso 2.").opPlus(vWD_j).getString());

// 	ArrayDeleteAll(sCampos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCampos);

// 	ArrayDeleteAll(sCamposExt)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCamposExt);

// 	ArrayDeleteAll(sTipos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTipos);

// 	ArrayDeleteAll(scamposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_scamposlocales);

// 	ArrayDeleteAll(sTiposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTiposlocales);

// 	ArrayDeleteAll(sValoreslocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sValoreslocales);

// 		ArrayDeleteAll(arrSParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSParametros);

// 		ArrayDeleteAll(arrSValParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSValParametros);

// 	gsTablename=Tabla_interface.Bddestino
GWDPQR.ms_Project.vWD_gsTablename.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bddestino"));

// 	sFiledestino=gsTablename
vWD_sFiledestino.setValeur(GWDPQR.ms_Project.vWD_gsTablename);

// 	sWhere=Tabla_interface.stwhere
GWDPQR.ms_Project.vWD_sWhere.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("stwhere"));

// 	sparametros=Tabla_interface.parametros
GWDPQR.ms_Project.vWD_sParametros.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("parametros"));

// 	Procesar_parametros()
GWDCPCOL_GlobalProcedures.fWD_procesar_parametros();

// 	Llenar_campos(sFiledestino)
GWDCPCOL_GlobalProcedures.fWD_llenar_campos(vWD_sFiledestino);

// 	IF ArrayCount(sCampos)=0 THEN
if(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCampos).opEgal(0))
{
// 		RESULT False
return new WDBooleen(false);

}

// 		Global_Leer_Tabla_comp()
GWDCPCOL_GlobalProcedures.fWD_global_Leer_Tabla_comp();

}

}
}

// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcLocale();
}

}



public WDObjet fWD_enviar_Datos_WS()
{
initExecProcLocale("Enviar_Datos_WS");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_j = new WDEntier();

WDObjet vWD_k = new WDEntier();

WDObjet vWD_nVals = new WDEntier();

WDObjet vWD_sFiledestino = new WDChaineU();

WDObjet vWD_sllavelocal = new WDChaineU();

WDObjet vWD_sllavedestino = new WDChaineU();

WDObjet vWD_sEsmodificado = new WDChaineU();

WDObjet vWD_sEsnuevo = new WDChaineU();

WDObjet vWD_sResultado = new WDChaineU();

WDObjet vWD_sIdinsert = new WDChaineU();

WDObjet vWD_sHijo = new WDChaineU();

WDObjet vWD_sWherelocal = new WDChaineU();



// j is int


// k is int=0

vWD_k.setValeur(0);


// nVals is int 


// sFiledestino is string


// sllavelocal is string


// sllavedestino is string


// sEsmodificado is string


// sEsnuevo is string


// sResultado is string 


// sIdinsert is string =""

vWD_sIdinsert.setValeur("");


// sHijo is string=""

vWD_sHijo.setValeur("");


// hread(Parametros,1)
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("parametros"),(long)1);

// hread(Usuarios,1)
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("usuarios"),(long)1);

// surl=parametros.wsutrl
GWDPQR.ms_Project.vWD_sUrl.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("wsutrl"));

// sservidor=parametros.servidor
GWDPQR.ms_Project.vWD_sservidor.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("servidor"));

// sInstancia=parametros.instancia
GWDPQR.ms_Project.vWD_sInstancia.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("instancia"));

// sBasededatos=Parametros.basededatos
GWDPQR.ms_Project.vWD_sBasededatos.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("basededatos"));

// sUsuario=usuarios.usuario //Parametros.usuarioacceso
GWDPQR.ms_Project.vWD_sUsuario.setValeur(WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("usuario"));

// sclave=usuarios.clave //Parametros.claveacceso
GWDPQR.ms_Project.vWD_sClave.setValeur(WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("clave"));

// sWherelocal is string =""

vWD_sWherelocal.setValeur("");


// for EACH Tabla_interface  where tabla_interface.direccion="O"
IWDParcours parcours1 = null;
try
{
parcours1 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"), WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("direccion"), new WDChaineU("O"), 1, true);
while(parcours1.testParcours())
{
// 		sfile=Tabla_interface.Bdlocal
GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal"));

// 		gsTablename=Tabla_interface.Bddestino
GWDPQR.ms_Project.vWD_gsTablename.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bddestino"));

// 		sFiledestino=gsTablename
vWD_sFiledestino.setValeur(GWDPQR.ms_Project.vWD_gsTablename);

// 		sllavelocal=sfile+"."+Tabla_interface.idlocal
vWD_sllavelocal.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("idlocal")));

// 		sllavedestino=sFiledestino+"."+Tabla_interface.id
vWD_sllavedestino.setValeur(vWD_sFiledestino.opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("id")));

// 		sEsnuevo=sfile+".esnuevo"
vWD_sEsnuevo.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".esnuevo"));

// 		sEsmodificado=sfile+".esmodificado"
vWD_sEsmodificado.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".esmodificado"));

// 		ArrayDeleteAll(sCampos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCampos);

// 		ArrayDeleteAll(sCamposExt)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCamposExt);

// 		ArrayDeleteAll(sTipos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTipos);

// 		ArrayDeleteAll(scamposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_scamposlocales);

// 		ArrayDeleteAll(sTiposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTiposlocales);

// 		ArrayDeleteAll(sValoreslocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sValoreslocales);

// 		ArrayDeleteAll(arrSParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSParametros);

// 		ArrayDeleteAll(arrSValParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSValParametros);

// 		Llenar_campos_sin_llave(sFiledestino)  //regresa los locales en scampos y los de destino en scamposext 
GWDCPCOL_GlobalProcedures.fWD_llenar_Campos_sin_llave(vWD_sFiledestino);

// 		Llenar_Where(sFiledestino)
GWDCPCOL_GlobalProcedures.fWD_llenar_Where(vWD_sFiledestino);

// 		ArrayDeleteAll(arrSParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSParametros);

// 		ArrayDeleteAll(arrSValParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSValParametros);

// 		StringToArray(sParametros,arrSParametros,"|")
WDAPITableau.chaineVersTableau(GWDPQR.ms_Project.vWD_sParametros,GWDPQR.ms_Project.vWD_arrSParametros,"|");

// 		StringToArray(sParametros,arrSValParametros,"|")
WDAPITableau.chaineVersTableau(GWDPQR.ms_Project.vWD_sParametros,GWDPQR.ms_Project.vWD_arrSValParametros,"|");

// 		sWherelocal= "( "+ {sfile}+".esmodificado=1  or "+ {sfile}+".esnuevo = 1  )"
vWD_sWherelocal.setValeur(new WDChaineU("( ").opPlus(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.getString())).opPlus(".esmodificado=1  or ").opPlus(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.getString())).opPlus(".esnuevo = 1  )"));

// 		FOR EACH {sFile} where sWherelocal //where {sEsmodificado}=true or {sEsnuevo}=true no funciona el where por {indireccion}
IWDParcours parcours2 = null;
try
{
parcours2 = WDParcoursFichier.pourTout(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.getString()), null, vWD_sWherelocal.getString(), true);
while(parcours2.testParcours())
{
// 			if {sEsmodificado}=true and {sEsnuevo}=False then 
if((WDIndirection.get(vWD_sEsmodificado.getString()).opEgal(true) & WDIndirection.get(vWD_sEsnuevo.getString()).opEgal(false)))
{
// 				if sParametros<>"" then
if(GWDPQR.ms_Project.vWD_sParametros.opDiff(""))
{
// 					k=ArrayCount(arrSParametros)
vWD_k.setValeur(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_arrSParametros));

// 					FOR li=1 TO k
for(WDObjet vWD_li = new WDEntier(1);vWD_li.opInfEgal(vWD_k);vWD_li.opInc())
{
// 						if arrSParametros[li]<>"" then
if(GWDPQR.ms_Project.vWD_arrSParametros.get(vWD_li).opDiff(""))
{
// 							arrSValParametros[li]={arrSParametros[li]}
GWDPQR.ms_Project.vWD_arrSValParametros.get(vWD_li).setValeur(WDIndirection.get(GWDPQR.ms_Project.vWD_arrSParametros.get(vWD_li).getString()));

}

}

// 					sWhere = StringBuild(gssqlWhere,arrSValParametros)
GWDPQR.ms_Project.vWD_sWhere.setValeur(WDAPIChaine.chaineConstruit(GWDPQR.ms_Project.vWD_gsSqlwhere,GWDPQR.ms_Project.vWD_arrSValParametros));

// 					crear_campos_update()
GWDCPCOL_GlobalProcedures.fWD_crear_campos_update();

// 					sResultado=Global_Sql_Record(surl,sservidor,sinstancia,sbasededatos,susuario,sclave,sFiledestino,"U",sListacampos,"",swhere,"")
vWD_sResultado.setValeur(GWDCPCOL_GlobalProcedures.fWD_global_Sql_Record(GWDPQR.ms_Project.vWD_sUrl,GWDPQR.ms_Project.vWD_sservidor,GWDPQR.ms_Project.vWD_sInstancia,GWDPQR.ms_Project.vWD_sBasededatos,GWDPQR.ms_Project.vWD_sUsuario,GWDPQR.ms_Project.vWD_sClave,vWD_sFiledestino,new WDChaineU("U"),GWDPQR.ms_Project.vWD_sListacampos,new WDChaineU(""),GWDPQR.ms_Project.vWD_sWhere,new WDChaineU("")));

// 					if sResultado="ok" then
if(vWD_sResultado.opEgal("ok"))
{
// 						{sEsmodificado}=false
WDIndirection.get(vWD_sEsmodificado.getString()).setValeur(false);

// 						hmodify(sfile)
WDAPIHF.hModifie(GWDPQR.ms_Project.vWD_sfile);

}

}

}

// 			IF {sEsnuevo}=True THEN
if(WDIndirection.get(vWD_sEsnuevo.getString()).opEgal(true))
{
// 				Crear_campos_insert()
GWDCPCOL_GlobalProcedures.fWD_crear_campos_insert();

// 				IF Tabla_interface.id<>"" THEN
if(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("id").opDiff(""))
{
// 					sIdinsert=Tabla_interface.id
vWD_sIdinsert.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("id"));

}

// 				sResultado=Global_Sql_Record(sUrl,sservidor,sInstancia,sBasededatos,sUsuario,sClave,sFiledestino,"I",sListacampos,sListavalores,"",sIdinsert)
vWD_sResultado.setValeur(GWDCPCOL_GlobalProcedures.fWD_global_Sql_Record(GWDPQR.ms_Project.vWD_sUrl,GWDPQR.ms_Project.vWD_sservidor,GWDPQR.ms_Project.vWD_sInstancia,GWDPQR.ms_Project.vWD_sBasededatos,GWDPQR.ms_Project.vWD_sUsuario,GWDPQR.ms_Project.vWD_sClave,vWD_sFiledestino,new WDChaineU("I"),GWDPQR.ms_Project.vWD_sListacampos,GWDPQR.ms_Project.vWD_sListavalores,new WDChaineU(""),vWD_sIdinsert));

// 				if Tabla_interface.id<>"" then
if(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("id").opDiff(""))
{
// 					{sfile+"."+Tabla_interface.id}=sResultado
WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("id")).getString()).setValeur(vWD_sResultado);

// 					if Tabla_interface.hijo1<>"" then
if(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("hijo1").opDiff(""))
{
// 						nVals=val(sResultado)
vWD_nVals.setValeur(WDAPIChaine.val(vWD_sResultado));

// 						Procesar_los_hijos(nVals)
fWD_procesar_los_hijos(vWD_nVals);

}

}

// 				{sEsnuevo}=False
WDIndirection.get(vWD_sEsnuevo.getString()).setValeur(false);

// 				{sEsmodificado}=False
WDIndirection.get(vWD_sEsmodificado.getString()).setValeur(false);

// 				HModify(sfile)
WDAPIHF.hModifie(GWDPQR.ms_Project.vWD_sfile);

}

}
}
finally
{
if(parcours2 != null)
{
parcours2.finParcours();
}
}


}
}
finally
{
if(parcours1 != null)
{
parcours1.finParcours();
}
}


// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcLocale();
}

}



public WDObjet fWD_enviar_imagenes_ws()
{
initExecProcLocale("Enviar_imagenes_ws");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_j = new WDEntier();

WDObjet vWD_k = new WDEntier();

WDObjet vWD_sFiledestino = new WDChaineU();

WDObjet vWD_sllavelocal = new WDChaineU();

WDObjet vWD_smemolocal = new WDChaineU();

WDObjet vWD_sllavedestino = new WDChaineU();

WDObjet vWD_sLlavearchivo = new WDChaineU();

WDObjet vWD_sEsmodificado = new WDChaineU();

WDObjet vWD_sEsnuevo = new WDChaineU();

WDObjet vWD_sEsmodificado_tabla = new WDChaineU();

WDObjet vWD_sEsnuevo_tabla = new WDChaineU();

WDObjet vWD_sResultado = new WDChaineU();

WDObjet vWD_sIdinsert = new WDChaineU();

WDObjet vWD_bbuffer = new WDBuffer();

WDObjet vWD_sBuffer = new WDChaineU();

WDObjet vWD_sImagendestino = new WDChaineU();

WDObjet vWD_arrSImagendestino = WDVarNonAllouee.ref;
WDObjet vWD_swherelocal = new WDChaineU();



// j is int


// k is int=0

vWD_k.setValeur(0);


// sFiledestino is string


// sllavelocal is string


// smemolocal is string


// sllavedestino is string


// sLlavearchivo is string 


// sEsmodificado is string


// sEsnuevo is string


// sEsmodificado_tabla is string


// sEsnuevo_tabla is string


// sResultado is string =""

vWD_sResultado.setValeur("");


// sIdinsert is string =""

vWD_sIdinsert.setValeur("");


// bbuffer is buffer


// sBuffer is string=""

vWD_sBuffer.setValeur("");


// sImagendestino is string=""

vWD_sImagendestino.setValeur("");


// arrSImagendestino is ARRAY of STRING 
vWD_arrSImagendestino = new WDTableauSimple(1, new int[]{0}, 0, 16);

// swherelocal is string 


// sUrl=Parametros.wsutrl
GWDPQR.ms_Project.vWD_sUrl.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("wsutrl"));

// sservidor=Parametros.servidor
GWDPQR.ms_Project.vWD_sservidor.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("servidor"));

// sInstancia=Parametros.instancia
GWDPQR.ms_Project.vWD_sInstancia.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("instancia"));

// sBasededatos=Parametros.basededatos
GWDPQR.ms_Project.vWD_sBasededatos.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("basededatos"));

// Erreur sur l'objet: WIN_Enviar_Datos
// 	Traitement : Enviar_imagenes_ws (0)
// 	Code: 403
// 	Message: usuario item not found in Parametros file.
// 	Ligne : 24, Colonne : 20
// 
// 
WDErreurManager.erreurGeneration("Erreur sur l'objet: WIN_Enviar_Datos\r\n\tTraitement : Enviar_imagenes_ws (0)\r\n\tCode: 403\r\n\tMessage: usuario item not found in Parametros file.\r\n\tLigne : 24, Colonne : 20\r\n\r\n");


// // sUsuario=Parametros.usuario
// GWDPQR.ms_Project.vWD_sUsuario.setValeur();
// 

// // Erreur sur l'objet: WIN_Enviar_Datos
// // 	Traitement : Enviar_imagenes_ws (0)
// // 	Code: 403
// // 	Message: clave item not found in Parametros file.
// // 	Ligne : 25, Colonne : 18
// // 
// // 
// WDErreurManager.erreurGeneration("Erreur sur l'objet: WIN_Enviar_Datos\r\n\tTraitement : Enviar_imagenes_ws (0)\r\n\tCode: 403\r\n\tMessage: clave item not found in Parametros file.\r\n\tLigne : 25, Colonne : 18\r\n\r\n");
// 
// 
// // // sClave=Parametros.clave
// // GWDPQR.ms_Project.vWD_sClave.setValeur();
// // 
// 
// // for EACH Tabla_InterfaseImagen  where tabla_interfaseimagen.direccion="O" 
// IWDParcours parcours3 = null;
// try
// {
// parcours3 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen"), WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("direccion"), new WDChaineU("O"), 1, true);
// while(parcours3.testParcours())
// {
// // 		sfile=Tabla_InterfaseImagen.Bdlocal
// GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("bdlocal"));
// 
// // 		gsTablename=Tabla_InterfaseImagen.Bddestino
// GWDPQR.ms_Project.vWD_gsTablename.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("bddestino"));
// 
// // 		sFiledestino=gsTablename
// vWD_sFiledestino.setValeur(GWDPQR.ms_Project.vWD_gsTablename);
// 
// // 		sllavelocal=sfile+"."+Tabla_InterfaseImagen.clavelocal
// vWD_sllavelocal.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("clavelocal")));
// 
// // 		sllavedestino=sFiledestino+"."+Tabla_InterfaseImagen.id
// vWD_sllavedestino.setValeur(vWD_sFiledestino.opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("id")));
// 
// // 		sLlavearchivo=sFile+"."+Tabla_InterfaseImagen.clavearchivo
// vWD_sLlavearchivo.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("clavearchivo")));
// 
// // 		sEsnuevo=sfile+".m_esnuevo"
// vWD_sEsnuevo.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".m_esnuevo"));
// 
// // 		sEsmodificado=sfile+".m_esmodificado"
// vWD_sEsmodificado.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".m_esmodificado"));
// 
// // 		sEsnuevo_tabla=sfile+".esnuevo"
// vWD_sEsnuevo_tabla.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".esnuevo"));
// 
// // 		sEsmodificado_tabla=sfile+".esmodificado"
// vWD_sEsmodificado_tabla.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".esmodificado"));
// 
// // 		ArrayDeleteAll(sCampos)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCampos);
// 
// // 		ArrayDeleteAll(sCamposExt)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCamposExt);
// 
// // 		ArrayDeleteAll(sTipos)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTipos);
// 
// // 		ArrayDeleteAll(scamposlocales)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_scamposlocales);
// 
// // 		ArrayDeleteAll(sTiposlocales)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTiposlocales);
// 
// // 		ArrayDeleteAll(sValoreslocales)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sValoreslocales);
// 
// // 		ArrayDeleteAll(arrSParametros)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSParametros);
// 
// // 		ArrayDeleteAll(arrSValParametros)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSValParametros);
// 
// // 		ArrayDeleteAll(sCamposimg)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCamposimg);
// 
// // 		ArrayDeleteAll(arrSImagendestino)
// WDAPITableau.tableauSupprimeTout(vWD_arrSImagendestino);
// 
// // 		ArrayDeleteAll(sCamposExtimg)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCamposExtimg);
// 
// // 		ArrayDeleteAll(sParametrosimg)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sParametrosimg);
// 
// // 		ArrayDeleteAll(sValParametrosimg)
// WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sValParametrosimg);
// 
// // 		Llenar_Campos_sin_llave_Img(sFiledestino)  //regresa los locales en scampos y los de destino en scamposext 
// GWDCPCOL_GlobalProcedures.fWD_llenar_Campos_sin_llave_img(vWD_sFiledestino);
// 
// // 		sWherelocal= "( "+{sfile}+".m_esmodificado=1  or "+ {sfile}+".m_esnuevo=1  ) "	
// vWD_swherelocal.setValeur(new WDChaineU("( ").opPlus(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.getString())).opPlus(".m_esmodificado=1  or ").opPlus(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.getString())).opPlus(".m_esnuevo=1  ) "));
// 
// // 		FOR EACH {sfile} where sWherelocal 
// IWDParcours parcours4 = null;
// try
// {
// parcours4 = WDParcoursFichier.pourTout(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.getString()), null, vWD_swherelocal.getString(), true);
// while(parcours4.testParcours())
// {
// // 			IF {sEsnuevo}=True THEN
// if(WDIndirection.get(vWD_sEsnuevo.getString()).opEgal(true))
// {
// // 				Crear_campos_insert() 
// GWDCPCOL_GlobalProcedures.fWD_crear_campos_insert();
// 
// // 				IF Tabla_InterfaseImagen.id<>"" THEN
// if(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("id").opDiff(""))
// {
// // 					sIdinsert=Tabla_InterfaseImagen.id
// vWD_sIdinsert.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("id"));
// 
// }
// 
// // 							for k=1 to ArrayCount(sCamposimg)
// for(vWD_k.setValeur(1);vWD_k.opInfEgal(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCamposimg));vWD_k.opInc())
// {
// // 									smemolocal=sfile+"."+sCamposimg[k]
// vWD_smemolocal.setValeur(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(GWDPQR.ms_Project.vWD_sCamposimg.get(vWD_k)));
// 
// // 									bbuffer={smemolocal}
// vWD_bbuffer.setValeur(WDIndirection.get(vWD_smemolocal.getString()));
// 
// // 									sBuffer = Crypt(bbuffer , "",cryptNone,encodeBASE64)
// vWD_sBuffer.setValeur(WDAPICrypt.crypte(vWD_bbuffer,"",0,true));
// 
// // 									sResultado=Global_Sql_Record(sUrl,sservidor,sInstancia,sBasededatos,sUsuario,sClave,sFiledestino,"I",sListacampos,sListavalores,"",sIdinsert)
// vWD_sResultado.setValeur(GWDCPCOL_GlobalProcedures.fWD_global_Sql_Record(GWDPQR.ms_Project.vWD_sUrl,GWDPQR.ms_Project.vWD_sservidor,GWDPQR.ms_Project.vWD_sInstancia,GWDPQR.ms_Project.vWD_sBasededatos,GWDPQR.ms_Project.vWD_sUsuario,GWDPQR.ms_Project.vWD_sClave,vWD_sFiledestino,new WDChaineU("I"),GWDPQR.ms_Project.vWD_sListacampos,GWDPQR.ms_Project.vWD_sListavalores,new WDChaineU(""),vWD_sIdinsert));
// 
// // 									IF Tabla_interfaseimagen.id<>"" THEN
// if(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("id").opDiff(""))
// {
// // 										{sfile+"."+Tabla_InterfaseImagen.id}=sResultado
// WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("id")).getString()).setValeur(vWD_sResultado);
// 
// }
// 
// // 									sImagendestino=sCamposExtimg[k]+"_"+gsNombreaplicacion+"_"+{sfile+"."+Tabla_InterfaseImagen.id}+".jpg"
// vWD_sImagendestino.setValeur(GWDPQR.ms_Project.vWD_sCamposExtimg.get(vWD_k).opPlus("_").opPlus(GWDPQR.ms_Project.vWD_gsNombreaplicacion).opPlus("_").opPlus(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("id")).getString())).opPlus(".jpg"));
// 
// // 									sResultado=Global_uploadimagebase64(sBuffer,sImagendestino)
// vWD_sResultado.setValeur(GWDCPCOL_GlobalProcedures.fWD_global_uploadimagebase64(vWD_sBuffer,vWD_sImagendestino));
// 
// // 									swhere=sFiledestino+"."+sIdinsert+" = "+ {sfile+"."+Tabla_InterfaseImagen.id}
// GWDPQR.ms_Project.vWD_sWhere.setValeur(vWD_sFiledestino.opPlus(".").opPlus(vWD_sIdinsert).opPlus(" = ").opPlus(WDIndirection.get(GWDPQR.ms_Project.vWD_sfile.opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interfaseimagen").getRubriqueSansCasseNiAccent("id")).getString())));
// 
// // Erreur sur l'objet: WIN_Enviar_Datos
// // 	Traitement : Enviar_imagenes_ws (0)
// // 	Code: 403
// // 	Message: folderimagenes item not found in Parametros file.
// // 	Ligne : 109, Colonne : 46
// // 
// // 
// // Erreur sur l'objet: WIN_Enviar_Datos
// // 	Traitement : Enviar_imagenes_ws (0)
// // 	Code: 403
// // 	Message: folderimagenes item not found in Parametros file.
// // 	Ligne : 109, Colonne : 46
// // 
// // 
// // Erreur sur l'objet: WIN_Enviar_Datos
// // 	Traitement : Enviar_imagenes_ws (0)
// // 	Code: 403
// // 	Message: folderimagenes item not found in Parametros file.
// // 	Ligne : 109, Colonne : 46
// // 
// // 
// // Erreur sur l'objet: WIN_Enviar_Datos
// // 	Traitement : Enviar_imagenes_ws (0)
// // 	Code: 403
// // 	Message: folderimagenes item not found in Parametros file.
// // 	Ligne : 109, Colonne : 46
// // 
// // 
// // Erreur sur l'objet: WIN_Enviar_Datos
// // 	Traitement : Enviar_imagenes_ws (0)
// // 	Code: 403
// // 	Message: folderimagenes item not found in Parametros file.
// // 	Ligne : 109, Colonne : 46
// // 
// // 
// WDErreurManager.erreurGeneration("Erreur sur l'objet: WIN_Enviar_Datos\r\n\tTraitement : Enviar_imagenes_ws (0)\r\n\tCode: 403\r\n\tMessage: folderimagenes item not found in Parametros file.\r\n\tLigne : 109, Colonne : 46\r\n\r\n\r\nErreur sur l'objet: WIN_Enviar_Datos\r\n\tTraitement : Enviar_imagenes_ws (0)\r\n\tCode: 403\r\n\tMessage: folderimagenes item not found in Parametros file.\r\n\tLigne : 109, Colonne : 46\r\n\r\n\r\nErreur sur l'objet: WIN_Enviar_Datos\r\n\tTraitement : Enviar_imagenes_ws (0)\r\n\tCode: 403\r\n\tMessage: folderimagenes item not found in Parametros file.\r\n\tLigne : 109, Colonne : 46\r\n\r\n\r\nErreur sur l'objet: WIN_Enviar_Datos\r\n\tTraitement : Enviar_imagenes_ws (0)\r\n\tCode: 403\r\n\tMessage: folderimagenes item not found in Parametros file.\r\n\tLigne : 109, Colonne : 46\r\n\r\n\r\nErreur sur l'objet: WIN_Enviar_Datos\r\n\tTraitement : Enviar_imagenes_ws (0)\r\n\tCode: 403\r\n\tMessage: folderimagenes item not found in Parametros file.\r\n\tLigne : 109, Colonne : 46\r\n\r\n");
// 
// 
// // // 									slistacampos="archivo='" +Parametros.folderimagenes+" \\"+sImagendestino+"'" 
// // GWDPQR.ms_Project.vWD_sListacampos.setValeur(new WDChaineU("archivo='").opPlus().opPlus(" \\").opPlus(vWD_sImagendestino).opPlus("'"));
// // 
// 
// // // 									sListavalores=""  //sImagendestino
// // GWDPQR.ms_Project.vWD_sListavalores.setValeur("");
// // 
// // // 									sResultado=Global_Sql_Record(sUrl,sservidor,sInstancia,sBasededatos,sUsuario,sClave,sFiledestino,"U",sListacampos,sListavalores,swhere,sIdinsert)
// // vWD_sResultado.setValeur(GWDCPCOL_GlobalProcedures.fWD_global_Sql_Record(GWDPQR.ms_Project.vWD_sUrl,GWDPQR.ms_Project.vWD_sservidor,GWDPQR.ms_Project.vWD_sInstancia,GWDPQR.ms_Project.vWD_sBasededatos,GWDPQR.ms_Project.vWD_sUsuario,GWDPQR.ms_Project.vWD_sClave,vWD_sFiledestino,new WDChaineU("U"),GWDPQR.ms_Project.vWD_sListacampos,GWDPQR.ms_Project.vWD_sListavalores,GWDPQR.ms_Project.vWD_sWhere,vWD_sIdinsert));
// // 
// }
// 
// // 							{sEsnuevo}=False
// WDIndirection.get(vWD_sEsnuevo.getString()).setValeur(false);
// 
// // 							{sEsmodificado}=False
// WDIndirection.get(vWD_sEsmodificado.getString()).setValeur(false);
// 
// // 							{sEsnuevo_tabla}=false 
// WDIndirection.get(vWD_sEsnuevo_tabla.getString()).setValeur(false);
// 
// // 							{sEsmodificado_tabla}=False 
// WDIndirection.get(vWD_sEsmodificado_tabla.getString()).setValeur(false);
// 
// // 							HModify(sfile)
// WDAPIHF.hModifie(GWDPQR.ms_Project.vWD_sfile);
// 
// }
// 
// }
// }
// finally
// {
// if(parcours4 != null)
// {
// parcours4.finParcours();
// }
// }
// 
// 
// }
// }
// finally
// {
// if(parcours3 != null)
// {
// parcours3.finParcours();
// }
// }
// 
// 
// // RESULT True
// return new WDBooleen(true);
// 
return new WDVoid("fWD_enviar_imagenes_ws");
}
finally
{
finExecProcLocale();
}

}



public void fWD_procesar_hijos( WDObjet vWD_sCampohijo , WDObjet vWD_nid_master )
{
initExecProcLocale("Procesar_hijos");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_sNombretabla = new WDChaineU();

WDObjet vWD_sNombrellave = new WDChaineU();

WDObjet vWD_sllavealmaster = new WDChaineU();

WDObjet vWD_sWherelocal = new WDChaineU();



vWD_sCampohijo = WDParametre.traiterParametre(vWD_sCampohijo, 1, false, 16);

vWD_nid_master = WDParametre.traiterParametre(vWD_nid_master, 2, false, 8);


// sNombretabla is string=""

vWD_sNombretabla.setValeur("");


// sNombrellave is string=""

vWD_sNombrellave.setValeur("");


// sllavealmaster is string=""

vWD_sllavealmaster.setValeur("");


// sNombretabla=ExtractString(sCampohijo, 1,"|") 
vWD_sNombretabla.setValeur(WDAPIChaine.extraitChaine(vWD_sCampohijo,1,new WDChaineU("|")));

// sNombrellave=ExtractString(sCampohijo, 2,"|") 
vWD_sNombrellave.setValeur(WDAPIChaine.extraitChaine(vWD_sCampohijo,2,new WDChaineU("|")));

// sllavealmaster=ExtractString(sCampohijo, 3,"|") 
vWD_sllavealmaster.setValeur(WDAPIChaine.extraitChaine(vWD_sCampohijo,3,new WDChaineU("|")));

// if sNombretabla="" OR sNombrellave="" THEN
if((vWD_sNombretabla.opEgal("") | vWD_sNombrellave.opEgal("")))
{
// 	RETURN
return;

}

// sWherelocal is string =   sNombretabla+"."+sllavealmaster+" = "+{Tabla_interface.Bdlocal+"."+Tabla_interface.idlocal}

vWD_sWherelocal.setValeur(vWD_sNombretabla.opPlus(".").opPlus(vWD_sllavealmaster).opPlus(" = ").opPlus(WDIndirection.get(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal").opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("idlocal")).getString())));


// for each {sNombretabla} where  sWherelocal
IWDParcours parcours5 = null;
try
{
parcours5 = WDParcoursFichier.pourTout(WDIndirection.get(vWD_sNombretabla.getString()), null, vWD_sWherelocal.getString(), true);
while(parcours5.testParcours())
{
// 		{sNombretabla+"."+sNombrellave}=nid_master
WDIndirection.get(vWD_sNombretabla.opPlus(".").opPlus(vWD_sNombrellave).getString()).setValeur(vWD_nid_master);

// 		hmodify({sNombretabla})
WDAPIHF.hModifie(WDIndirection.get(vWD_sNombretabla.getString()));

}
}
finally
{
if(parcours5 != null)
{
parcours5.finParcours();
}
}


}
finally
{
finExecProcLocale();
}

}



public void fWD_procesar_los_hijos( WDObjet vWD_nid_master )
{
initExecProcLocale("Procesar_los_hijos");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_sWheretabla = new WDChaineU();

WDObjet vWD_sWherelocal = new WDChaineU();

WDObjet vWD_sNombretabla = new WDChaineU();

WDObjet vWD_sNombrellave = new WDChaineU();



vWD_nid_master = WDParametre.traiterParametre(vWD_nid_master, 1, false, 8);


// sWheretabla is string =" interface_hijos.Bdlocal='"+Tabla_interface.bdlocal+"' and interface_hijos.Bddestino='"+Tabla_interface.Bddestino+"'"

vWD_sWheretabla.setValeur(new WDChaineU(" interface_hijos.Bdlocal='").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal")).opPlus("' and interface_hijos.Bddestino='").opPlus(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bddestino")).opPlus("'"));


// sWherelocal is string 


// sNombretabla is string=""

vWD_sNombretabla.setValeur("");


// sNombrellave is string=""

vWD_sNombrellave.setValeur("");


// HReadFirst(interface_hijos)
WDAPIHF.hLitPremier(WDAPIHF.getFichierSansCasseNiAccent("interface_hijos"));

// for EACH interface_hijos  where sWheretabla
IWDParcours parcours6 = null;
try
{
parcours6 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("interface_hijos"), null, vWD_sWheretabla.getString(), true);
while(parcours6.testParcours())
{
// 	    sWherelocal=interface_hijos.tablahijo+"."+interface_hijos.buscarhijo+" = "+{interface_hijos.Bdlocal+"."+interface_hijos.campolocal}
vWD_sWherelocal.setValeur(WDAPIHF.getFichierSansCasseNiAccent("interface_hijos").getRubriqueSansCasseNiAccent("tablahijo").opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("interface_hijos").getRubriqueSansCasseNiAccent("buscarhijo")).opPlus(" = ").opPlus(WDIndirection.get(WDAPIHF.getFichierSansCasseNiAccent("interface_hijos").getRubriqueSansCasseNiAccent("bdlocal").opPlus(".").opPlus(WDAPIHF.getFichierSansCasseNiAccent("interface_hijos").getRubriqueSansCasseNiAccent("campolocal")).getString())));

// 	    sNombretabla=interface_hijos.tablahijo
vWD_sNombretabla.setValeur(WDAPIHF.getFichierSansCasseNiAccent("interface_hijos").getRubriqueSansCasseNiAccent("tablahijo"));

// 	    sNombrellave=interface_hijos.campohijo
vWD_sNombrellave.setValeur(WDAPIHF.getFichierSansCasseNiAccent("interface_hijos").getRubriqueSansCasseNiAccent("campohijo"));

// 		for each {sNombretabla} where sWherelocal
IWDParcours parcours7 = null;
try
{
parcours7 = WDParcoursFichier.pourTout(WDIndirection.get(vWD_sNombretabla.getString()), null, vWD_sWherelocal.getString(), true);
while(parcours7.testParcours())
{
// 			{sNombretabla+"."+sNombrellave}=nid_master
WDIndirection.get(vWD_sNombretabla.opPlus(".").opPlus(vWD_sNombrellave).getString()).setValeur(vWD_nid_master);

// 			HModify({sNombretabla})	
WDAPIHF.hModifie(WDIndirection.get(vWD_sNombretabla.getString()));

}
}
finally
{
if(parcours7 != null)
{
parcours7.finParcours();
}
}


}
}
finally
{
if(parcours6 != null)
{
parcours6.finParcours();
}
}


}
finally
{
finExecProcLocale();
}

}




/**
 * ACTB_ActionBar
 */
class GWDACTB_ActionBar extends WDActionBar
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°1 de WIN_Enviar_Datos.ACTB_ActionBar
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setNom("ACTB_ActionBar");

super.setNote("", "");

super.setParamBoutonGauche(true, 1, "", "C:\\My Mobile Projects\\QR\\LOGOEVA.jpg");

super.setParamBoutonDroit(false, 0, "", "");

super.setStyleActionBar(0xFF000001, 0xFF000001, true);

super.setImageFond("");

super.terminerInitialisation();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDACTB_ActionBar mWD_ACTB_ActionBar;

/**
 * Traitement: Global declarations of WIN_Enviar_Datos
 */
public void declarerGlobale(WDObjet[] WD_tabParam)
{
super.declarerGlobale(WD_tabParam);
int WD_ntabParamLen = 0;
if(WD_tabParam!=null) WD_ntabParamLen = WD_tabParam.length;


}




// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
// Création des champs de la fenêtre WIN_Enviar_Datos
////////////////////////////////////////////////////////////////////////////
protected void creerChamps()
{
mWD_PROGBAR_Subire = new GWDPROGBAR_Subire();
mWD_BTN_Subir1 = new GWDBTN_Subir1();
mWD_BTN_Cancelar = new GWDBTN_Cancelar();
mWD_ACTB_ActionBar = new GWDACTB_ActionBar();

}
////////////////////////////////////////////////////////////////////////////
// Initialisation de la fenêtre WIN_Enviar_Datos
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.setQuid(3082667185778246896l);

super.setChecksum("874233330");

super.setNom("WIN_Enviar_Datos");

super.setType(1);

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setCouleur(0x0);

super.setCouleurFond(0xFFFFFF);

super.setPositionInitiale(0, 0);

super.setTailleInitiale(320, 408);

super.setTitre("Enviar Datos");

super.setTailleMin(-1, -1);

super.setTailleMax(20000, 20000);

super.setVisibleInitial(true);

super.setPersistant(true);

super.setGFI(true);

super.setAnimationFenetre(0);

super.setImageFond("", 327683, 0, 1);

super.setCouleurTexteAutomatique(0xF4000000);

super.setCouleurBarreSysteme(0xFF000001);


activerEcoute();

////////////////////////////////////////////////////////////////////////////
// Initialisation des champs de WIN_Enviar_Datos
////////////////////////////////////////////////////////////////////////////
mWD_PROGBAR_Subire.initialiserObjet();
super.ajouter("PROGBAR_Subire", mWD_PROGBAR_Subire);
mWD_BTN_Subir1.initialiserObjet();
super.ajouter("BTN_Subir1", mWD_BTN_Subir1);
mWD_BTN_Cancelar.initialiserObjet();
super.ajouter("BTN_Cancelar", mWD_BTN_Cancelar);
mWD_ACTB_ActionBar.initialiserObjet();
super.ajouterActionBar(mWD_ACTB_ActionBar);

super.terminerInitialisation();
}

////////////////////////////////////////////////////////////////////////////
public boolean isUniteAffichageLogique()
{
return false;
}
/**
* Retourne le mode d'affichage de l'ActionBar de la fenêtre.
*/
public int getModeActionBar()
{
return 1;
}
/**
* Retourne vrai si la fenêtre est maximisée, faux sinon.
*/
public boolean isMaximisee()
{
return true;
}
/**
* Retourne vrai si la fenêtre a une barre de titre, faux sinon.
*/
public boolean isAvecBarreDeTitre()
{
return true;
}
/**
* Retourne le mode d'affichage de la barre système de la fenêtre.
*/
public int getModeBarreSysteme()
{
return 1;
}
/**
* Retourne vrai si la fenêtre est munie d'ascenseurs automatique, faux sinon.
*/
public boolean isAvecAscenseurAuto()
{
return false;
}
/**
* Retourne Vrai si on doit appliquer un theme "dark" (sombre) ou Faux si on doit appliquer "light" (clair) à la fenêtre.
* Ce choix se base sur la couleur du libellé par défaut dans le gabarit de la fenêtre.
*/
public boolean isThemeDark()
{
return false;
}
/**
* Retourne vrai si l'option de masquage automatique de l'ActionBar lorsqu'on scrolle dans un champ de la fenêtre a été activée.
*/
public boolean isMasquageAutomatiqueActionBar()
{
return false;
}
public static class WDActiviteFenetre extends WDActivite
{
protected WDFenetre getFenetre()
{
return GWDPQR.ms_Project.mWD_WIN_Enviar_Datos;
}
}
/**
* Retourne le nom du gabarit associée à la fenêtre.
*/
public String getNomGabarit()
{
return "200 ACTIVANDROID 5#WM";
}
}
