/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Fenêtre
 * Android class: WIN_Bajar
 * Date: 27/09/2018 02:59:08
 * Version of wdjava.dll: 22.0.106.0
 */


package com.mycompany.qr.wdgen;


import com.mycompany.qr.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.ui.champs.fenetre.*;
import fr.pcsoft.wdjava.ui.champs.bouton.*;
import fr.pcsoft.wdjava.ui.cadre.*;
import fr.pcsoft.wdjava.api.*;
import fr.pcsoft.wdjava.ui.champs.jauge.*;
import fr.pcsoft.wdjava.ui.champs.groupeoptions.*;
import fr.pcsoft.wdjava.ui.champs.libelle.*;
import fr.pcsoft.wdjava.ui.champs.saisie.*;
import fr.pcsoft.wdjava.core.parcours.*;
import fr.pcsoft.wdjava.core.parcours.hf.*;
import fr.pcsoft.wdjava.ui.actionbar.*;
import fr.pcsoft.wdjava.ui.activite.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/



public class GWDFWIN_Bajar extends WDFenetre
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs de WIN_Bajar
////////////////////////////////////////////////////////////////////////////

/**
 * BTN_Enviar
 */
class GWDBTN_Enviar extends WDBouton
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°1 de WIN_Bajar.BTN_Enviar
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(3133885963869163792l);

super.setChecksum("1182721246");

super.setNom("BTN_Enviar");

super.setType(4);

super.setLibelle("Cargar");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(33, 223);

super.setTailleInitiale(96, 38);

super.setPlan(0);

super.setImageEtat(1);

super.setImageFondEtat(5);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(1);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setNumTab(3);

super.setLettreAppel(65535);

super.setTypeBouton(0);

super.setTypeActionPredefinie(0);

super.setBoutonOnOff(false);

super.setTauxParallaxe(0, 0);

super.setLibelleVAlign(1);

super.setLibelleHAlign(1);

super.setPresenceLibelle(true);

super.setImage("", 0, 2, 1, null, null, null);

super.setStyleLibelleRepos(0xFFFFFF, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleSurvol(0xFFFFFF, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleEnfonce(0xFFFFFF, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setCadreRepos(WDCadreFactory.creerCadre_GEN(2, 0x50AF4C, 0x2F00, 0x50AF4C, 4, 4, 1, 1));

super.setCadreSurvol(WDCadreFactory.creerCadre_GEN(2, 0x50AF4C, 0x2F00, 0x50AF4C, 4, 4, 1, 1));

super.setCadreEnfonce(WDCadreFactory.creerCadre_GEN(2, 0x50AF4C, 0x2F00, 0x50AF4C, 4, 4, 1, 1));

super.setImageFond9Images(new int[] {1,2,1,2,2,2,1,2,1}, 10, 10, 10, 10);

super.setImageFond("C:\\My Mobile Projects\\QR\\Templates\\WM\\210 Material Design Green\\Material Design Green_Btn_Std@dpi160.png?E5_3NP_10_10_10_10", 1, 0, 1, 1);

activerEcoute();
super.terminerInitialisation();
}

/**
 * Traitement: Click BTN_Enviar
 */
public void clicSurBoutonGauche()
{
super.clicSurBoutonGauche();


////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_bPasos = new WDBooleen();

WDObjet vWD_i = new WDEntier();



// PROGBAR_NativeCircular..Visible= True
mWD_PROGBAR_NativeCircular.setVisible(true);

// bPasos is boolean


// bPasos=Global_Borrar_datos_locales()
vWD_bPasos.setValeur(GWDCPCOL_GlobalProcedures.fWD_global_Borrar_datos_locales());

// i is int


// gsParzonas=""
GWDPQR.ms_Project.vWD_gsParzonas.setValeur("");

// gsParzonaswhere=""
GWDPQR.ms_Project.vWD_gsParzonaswhere.setValeur("");

// gsParzonas=NoRightCharacter(gsParzonas,",")
GWDPQR.ms_Project.vWD_gsParzonas.setValeur(WDAPIChaine.sansCaractereDroite(GWDPQR.ms_Project.vWD_gsParzonas.getString(),","));

// gsParzonaswhere=NoRightCharacter(gsParzonaswhere,",")
GWDPQR.ms_Project.vWD_gsParzonaswhere.setValeur(WDAPIChaine.sansCaractereDroite(GWDPQR.ms_Project.vWD_gsParzonaswhere.getString(),","));

// bPasos=Leer_Datos_WS()
vWD_bPasos.setValeur(fWD_leer_Datos_WS());

// IF bPasos=False THEN
if(vWD_bPasos.opEgal(false))
{
// 	PROGBAR_NativeCircular..Visible= False
mWD_PROGBAR_NativeCircular.setVisible(false);

// 	RETURN 
return;

}

// PROGBAR_NativeCircular..Visible= False
mWD_PROGBAR_NativeCircular.setVisible(false);

// ToastDisplay("Proceso finalizado")
WDAPIToast.toastAffiche("Proceso finalizado");

// Close()
WDAPIFenetre.ferme();

}




// Activation des écouteurs: 
public void activerEcoute()
{
super.activerEcouteurClic();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDBTN_Enviar mWD_BTN_Enviar;

/**
 * PROGBAR_NativeCircular
 */
class GWDPROGBAR_NativeCircular extends WDJaugeInfinie
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°2 de WIN_Bajar.PROGBAR_NativeCircular
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(3133885963869294880l);

super.setChecksum("1182902038");

super.setNom("PROGBAR_NativeCircular");

super.setType(113);

super.setLibelle("Progress bar");

super.setNote("", "");

super.setEtatInitial(0);

super.setPositionInitiale(140, 219);

super.setTailleInitiale(42, 46);

super.setPlan(0);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(false);

super.setAltitude(2);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setTauxParallaxe(0, 0);

super.setPresenceLibelle(false);

super.setStyleLibelle(0x0, creerPolice_GEN("MS Shell Dlg", -11.000000, 0), -1, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xF1000000, 0xF3000000, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
protected int getTypeJauge()
{
return 1;
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDPROGBAR_NativeCircular mWD_PROGBAR_NativeCircular;

/**
 * BTN_cancelar
 */
class GWDBTN_cancelar extends WDBouton
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°3 de WIN_Bajar.BTN_cancelar
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(3133885963869425952l);

super.setChecksum("1182983406");

super.setNom("BTN_cancelar");

super.setType(4);

super.setLibelle("Cancelar");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(193, 224);

super.setTailleInitiale(96, 38);

super.setPlan(0);

super.setImageEtat(1);

super.setImageFondEtat(5);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(3);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setNumTab(4);

super.setLettreAppel(65535);

super.setTypeBouton(0);

super.setTypeActionPredefinie(0);

super.setBoutonOnOff(false);

super.setTauxParallaxe(0, 0);

super.setLibelleVAlign(1);

super.setLibelleHAlign(1);

super.setPresenceLibelle(true);

super.setImage("", 0, 2, 1, null, null, null);

super.setStyleLibelleRepos(0xFFFFFF, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleSurvol(0xFFFFFF, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleEnfonce(0xFFFFFF, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setCadreRepos(WDCadreFactory.creerCadre_GEN(2, 0x50AF4C, 0x2F00, 0x50AF4C, 4, 4, 1, 1));

super.setCadreSurvol(WDCadreFactory.creerCadre_GEN(2, 0x50AF4C, 0x2F00, 0x50AF4C, 4, 4, 1, 1));

super.setCadreEnfonce(WDCadreFactory.creerCadre_GEN(2, 0x50AF4C, 0x2F00, 0x50AF4C, 4, 4, 1, 1));

super.setImageFond9Images(new int[] {1,2,1,2,2,2,1,2,1}, 10, 10, 10, 10);

super.setImageFond("C:\\My Mobile Projects\\QR\\Templates\\WM\\210 Material Design Green\\Material Design Green_Btn_Std@dpi160.png?E5_3NP_10_10_10_10", 1, 0, 1, 1);

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDBTN_cancelar mWD_BTN_cancelar;

/**
 * CBOX_IP
 */
class GWDCBOX_IP extends WDInterrupteur
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°4 de WIN_Bajar.CBOX_IP
////////////////////////////////////////////////////////////////////////////

/**
 * CBOX_IP_Option_0
 */
class GWDCBOX_IP_Option_0 extends WDCaseACocherNatif
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°1 de WIN_Bajar.CBOX_IP.CBOX_IP_Option_0
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setLibelle("");

super.setHauteurOption(0);

super.setStyleLibelleOption(0x212121, creerPolice_GEN("Roboto", -8.000000, 0));

super.terminerInitialisation();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDCBOX_IP_Option_0 mWD_CBOX_IP_Option_0 = new GWDCBOX_IP_Option_0();
/**
 * Initialise tous les champs de WIN_Bajar.CBOX_IP
 */
public void initialiserSousObjets()
{
////////////////////////////////////////////////////////////////////////////
// Initialisation des champs de WIN_Bajar.CBOX_IP
////////////////////////////////////////////////////////////////////////////
super.initialiserSousObjets();
super.ajouterOption(mWD_CBOX_IP_Option_0);
positionnerOptions();
}
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setRectCompPrincipal(0,0,54,23);
super.setQuid(3147041981192542228l);

super.setChecksum("1105570558");

super.setNom("CBOX_IP");

super.setType(5);

super.setLibelle("Check box");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(180, 8);

super.setTailleInitiale(54, 23);

super.setValeurInitiale(0);

super.setPlan(0);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(4);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setNumTab(1);

super.setLettreAppel(65535);

super.setPersistant(false);

super.setParamOptions(false, 1, true, true, false);

super.setTauxParallaxe(0, 0);

super.setPresenceLibelle(false);

super.setStyleLibelle(0x212121, creerPolice_GEN("Roboto", -8.000000, 0), -1, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xF1000000, 0xF3000000, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

super.setCadreInterne(WDCadreFactory.creerCadre_GEN(1, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 4, 4, 1, 1));


super.setImageCoche("C:\\My Mobile Projects\\QR\\Templates\\WM\\210 Material Design Green\\Material Design Green_CBox@dpi160.png?E12_Radio", 1);

activerEcoute();
initialiserSousObjets();
super.terminerInitialisation();
}

/**
 * Traitement: Whenever modifying CBOX_IP
 */
public void modification()
{
super.modification();

// IF CBOX_IP..Value = 1 THEN
if(this.getValeur().opEgal(1))
{
// 	EDT_IP..Visible = True
mWD_EDT_IP.setVisible(true);

}
else
{
// 	EDT_IP..Visible = False
mWD_EDT_IP.setVisible(false);

// 	EDT_IP = "" 
mWD_EDT_IP.setValeur("");

}

}




// Activation des écouteurs: 
public void activerEcoute()
{
super.activerEcouteurModification();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDCBOX_IP mWD_CBOX_IP;

/**
 * STC_NoName1
 */
class GWDSTC_NoName1 extends WDLibelle
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°5 de WIN_Bajar.STC_NoName1
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(3147042226006325034l);

super.setChecksum("1106216637");

super.setNom("STC_NoName1");

super.setType(3);

super.setTypeSaisie(0);

super.setMasqueSaisie(new WDChaineU("0"));

super.setLibelle("Utilizar dirección local");

super.setNote("", "");

super.setEtatInitial(0);

super.setPositionInitiale(8, 8);

super.setTailleInitiale(164, 21);

super.setPlan(0);

super.setCadrageHorizontal(0);

super.setCadrageVertical(0);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(5);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setEllipse(0);

super.setTauxParallaxe(0, 0);

super.setPresenceLibelle(true);

super.setStyleLibelle(0x222222, 0xFFFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 3, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xE1E1E1, 0x616161, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);


activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDSTC_NoName1 mWD_STC_NoName1;

/**
 * EDT_IP
 */
class GWDEDT_IP extends WDChampSaisieSimple
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°6 de WIN_Bajar.EDT_IP
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setRectLibelle(0,2,112,40);
super.setRectCompPrincipal(112,2,192,40);
super.setQuid(3147042552428764366l);

super.setChecksum("1111141093");

super.setNom("EDT_IP");

super.setType(20001);

super.setLibelle("Direccion IP");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setTaille(0);

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(8, 70);

super.setTailleInitiale(304, 44);

super.setValeurInitiale("");

super.setPlan(0);

super.setCadrageHorizontal(0);

super.setMotDePasse(false);

super.setTypeSaisie(0);

super.setMasqueSaisie(new WDChaineU("0"));

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(false);

super.setAltitude(6);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setEllipse(0);

super.setIndication("");

super.setNumTab(2);

super.setModeAscenseur(2, 2);

super.setEffacementAutomatique(true);

super.setFinSaisieAutomatique(false);

super.setLettreAppel(65535);

super.setSelectionEnAffichage(true);

super.setPersistant(false);

super.setClavierEnSaisie(true);

super.setMasqueAffichage(new WDChaineU(""));

super.setParamBtnActionClavier(0, "");

super.setRetraitGauche(2);

super.setMiseABlancSiZero(true);

super.setVerifieOrthographe(true);

super.setTauxParallaxe(0, 0);

super.setBoutonSuppression(0);

super.setPresenceLibelle(true);

super.setStyleLibelle(0x222222, creerPolice_GEN("Roboto", -8.000000, 0), -2, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xE1E1E1, 0x616161, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

super.setCadreInterne(WDCadreFactory.creerCadre_GEN("C:\\My Mobile Projects\\QR\\Templates\\WM\\210 Material Design Green\\Material Design Green_Edt@dpi160.png?E5_3NP_8_8_8_8", new int[] {1,4,1,2,2,2,1,4,1}, new int[] {8, 8, 8, 8}, 0xFFFFFFFF, 1, 5));

super.setStyleSaisie(0x222222, creerPolice_GEN("Roboto", -8.000000, 0));

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDEDT_IP mWD_EDT_IP;


////////////////////////////////////////////////////////////////////////////
// Procédures utilisateur de WIN_Bajar
////////////////////////////////////////////////////////////////////////////
//  Summary: <specify the procedure action>
//  Syntax:
// [ <Result> = ] Leer_Datos_WS ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	boolean: // 	None
// 
//  For instance:
//  Indicate an example.
// 
public WDObjet fWD_leer_Datos_WS()
{
initExecProcLocale("Leer_Datos_WS");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_j = new WDEntier();

WDObjet vWD_sFiledestino = new WDChaineU();

WDObjet vWD_sBodega = new WDChaineU();



// j is int


// sFiledestino is string


// sBodega is string


// HRead(Usuarios,1)
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("usuarios"),(long)1);

// HReadFirst(Parametros)
WDAPIHF.hLitPremier(WDAPIHF.getFichierSansCasseNiAccent("parametros"));

// sUrl=Parametros.wsutrl 
GWDPQR.ms_Project.vWD_sUrl.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("wsutrl"));

// sservidor=Parametros.servidor
GWDPQR.ms_Project.vWD_sservidor.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("servidor"));

// sInstancia=Parametros.instancia
GWDPQR.ms_Project.vWD_sInstancia.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("instancia"));

// sBasededatos=Parametros.basededatos
GWDPQR.ms_Project.vWD_sBasededatos.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("basededatos"));

// sUsuario =Usuarios.Usuario
GWDPQR.ms_Project.vWD_sUsuario.setValeur(WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("usuario"));

// sClave =Usuarios.Clave
GWDPQR.ms_Project.vWD_sClave.setValeur(WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("clave"));

// sBodega = Usuarios.Bodega
vWD_sBodega.setValeur(WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("bodega"));

// IF CBOX_IP..Value = 1 THEN
if(mWD_CBOX_IP.getValeur().opEgal(1))
{
// 	sUrl = "http://"+EDT_IP+"/wsdatasql/wsdatasqlservice.asmx"
GWDPQR.ms_Project.vWD_sUrl.setValeur(new WDChaineU("http://").opPlus(mWD_EDT_IP).opPlus("/wsdatasql/wsdatasqlservice.asmx"));

}

// sWhere=""  
GWDPQR.ms_Project.vWD_sWhere.setValeur("");

// sorder=""
GWDPQR.ms_Project.vWD_sorder.setValeur("");

// FOR EACH Tabla_interface  where Tabla_interface.direccion="I"
IWDParcours parcours1 = null;
try
{
parcours1 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"), WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("direccion"), new WDChaineU("I"), 1, true);
while(parcours1.testParcours())
{
// 	sfile=Tabla_interface.Bdlocal
GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal"));

// 	ArrayDeleteAll(sCampos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCampos);

// 	ArrayDeleteAll(sCamposExt)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCamposExt);

// 	ArrayDeleteAll(sTipos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTipos);

// 	ArrayDeleteAll(scamposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_scamposlocales);

// 	ArrayDeleteAll(sTiposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTiposlocales);

// 	ArrayDeleteAll(sValoreslocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sValoreslocales);

// 		ArrayDeleteAll(arrSParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSParametros);

// 		ArrayDeleteAll(arrSValParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSValParametros);

// 	ArrayDeleteAll(sFilltabla)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sFilltabla);

// 	ArrayDeleteAll(sFillTipos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sFillTipos);

// 	ArrayDeleteAll(sFillcampobuscar)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sFillcampobuscar);

// 	ArrayDeleteAll(sFillcampollenar)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sFillcampollenar);

// 	ArrayDeleteAll(sFillcampovalor)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sFillcampovalor);

// 	gsTablename=Tabla_interface.Bddestino
GWDPQR.ms_Project.vWD_gsTablename.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bddestino"));

// 	sFiledestino=gsTablename
vWD_sFiledestino.setValeur(GWDPQR.ms_Project.vWD_gsTablename);

// 	sWhere=Tabla_interface.stwhere+"'"+sBodega+"'"
GWDPQR.ms_Project.vWD_sWhere.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("stwhere").opPlus("'").opPlus(vWD_sBodega).opPlus("'"));

// 	sParametros=Tabla_interface.parametros
GWDPQR.ms_Project.vWD_sParametros.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("parametros"));

// 	Procesar_parametros()
GWDCPCOL_GlobalProcedures.fWD_procesar_parametros();

// 	Llenar_campos(sFiledestino)
GWDCPCOL_GlobalProcedures.fWD_llenar_campos(vWD_sFiledestino);

// 	IF ArrayCount(sCampos)=0 THEN
if(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCampos).opEgal(0))
{
// 		RESULT False
return new WDBooleen(false);

}

// 		Multitask(-1)
WDAPIVM.multitache(-1);

// 		Global_Leer_Tabla(sUrl,sservidor,sInstancia,sBasededatos,sUsuario,sClave, gsTablename, sListacampos,sWhere,sorder)
GWDCPCOL_GlobalProcedures.fWD_global_Leer_Tabla(GWDPQR.ms_Project.vWD_sUrl,GWDPQR.ms_Project.vWD_sservidor,GWDPQR.ms_Project.vWD_sInstancia,GWDPQR.ms_Project.vWD_sBasededatos,GWDPQR.ms_Project.vWD_sUsuario,GWDPQR.ms_Project.vWD_sClave,GWDPQR.ms_Project.vWD_gsTablename,GWDPQR.ms_Project.vWD_sListacampos,GWDPQR.ms_Project.vWD_sWhere,GWDPQR.ms_Project.vWD_sorder);

}
}
finally
{
if(parcours1 != null)
{
parcours1.finParcours();
}
}


// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcLocale();
}

}




/**
 * ACTB_ActionBar
 */
class GWDACTB_ActionBar extends WDActionBar
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°1 de WIN_Bajar.ACTB_ActionBar
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setNom("ACTB_ActionBar");

super.setNote("", "");

super.setParamBoutonGauche(true, 1, "", "");

super.setParamBoutonDroit(false, 0, "", "");

super.setStyleActionBar(0xFFFFFF, 0x50AF4C, true);

super.setImageFond("");

super.terminerInitialisation();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDACTB_ActionBar mWD_ACTB_ActionBar;

/**
 * Traitement: Global declarations of WIN_Bajar
 */
public void declarerGlobale(WDObjet[] WD_tabParam)
{
super.declarerGlobale(WD_tabParam);
int WD_ntabParamLen = 0;
if(WD_tabParam!=null) WD_ntabParamLen = WD_tabParam.length;


}




// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
// Création des champs de la fenêtre WIN_Bajar
////////////////////////////////////////////////////////////////////////////
protected void creerChamps()
{
mWD_BTN_Enviar = new GWDBTN_Enviar();
mWD_PROGBAR_NativeCircular = new GWDPROGBAR_NativeCircular();
mWD_BTN_cancelar = new GWDBTN_cancelar();
mWD_CBOX_IP = new GWDCBOX_IP();
mWD_STC_NoName1 = new GWDSTC_NoName1();
mWD_EDT_IP = new GWDEDT_IP();
mWD_ACTB_ActionBar = new GWDACTB_ActionBar();

}
////////////////////////////////////////////////////////////////////////////
// Initialisation de la fenêtre WIN_Bajar
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.setQuid(3124898907790737019l);

super.setChecksum("964722948");

super.setNom("WIN_Bajar");

super.setType(1);

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setCouleur(0x0);

super.setCouleurFond(0xFFFFFF);

super.setPositionInitiale(0, 0);

super.setTailleInitiale(320, 408);

super.setTitre("Cargar datos");

super.setTailleMin(-1, -1);

super.setTailleMax(20000, 20000);

super.setVisibleInitial(true);

super.setPersistant(true);

super.setGFI(true);

super.setAnimationFenetre(0);

super.setImageFond("", 1, 0, 1);

super.setCouleurTexteAutomatique(0xF4000000);

super.setCouleurBarreSysteme(0xFF000001);


activerEcoute();

////////////////////////////////////////////////////////////////////////////
// Initialisation des champs de WIN_Bajar
////////////////////////////////////////////////////////////////////////////
mWD_BTN_Enviar.initialiserObjet();
super.ajouter("BTN_Enviar", mWD_BTN_Enviar);
mWD_PROGBAR_NativeCircular.initialiserObjet();
super.ajouter("PROGBAR_NativeCircular", mWD_PROGBAR_NativeCircular);
mWD_BTN_cancelar.initialiserObjet();
super.ajouter("BTN_cancelar", mWD_BTN_cancelar);
mWD_CBOX_IP.initialiserObjet();
super.ajouter("CBOX_IP", mWD_CBOX_IP);
mWD_STC_NoName1.initialiserObjet();
super.ajouter("STC_NoName1", mWD_STC_NoName1);
mWD_EDT_IP.initialiserObjet();
super.ajouter("EDT_IP", mWD_EDT_IP);
mWD_ACTB_ActionBar.initialiserObjet();
super.ajouterActionBar(mWD_ACTB_ActionBar);

super.terminerInitialisation();
}

////////////////////////////////////////////////////////////////////////////
public boolean isUniteAffichageLogique()
{
return false;
}
/**
* Retourne le mode d'affichage de l'ActionBar de la fenêtre.
*/
public int getModeActionBar()
{
return 1;
}
/**
* Retourne vrai si la fenêtre est maximisée, faux sinon.
*/
public boolean isMaximisee()
{
return true;
}
/**
* Retourne vrai si la fenêtre a une barre de titre, faux sinon.
*/
public boolean isAvecBarreDeTitre()
{
return true;
}
/**
* Retourne le mode d'affichage de la barre système de la fenêtre.
*/
public int getModeBarreSysteme()
{
return 1;
}
/**
* Retourne vrai si la fenêtre est munie d'ascenseurs automatique, faux sinon.
*/
public boolean isAvecAscenseurAuto()
{
return true;
}
/**
* Retourne Vrai si on doit appliquer un theme "dark" (sombre) ou Faux si on doit appliquer "light" (clair) à la fenêtre.
* Ce choix se base sur la couleur du libellé par défaut dans le gabarit de la fenêtre.
*/
public boolean isThemeDark()
{
return false;
}
/**
* Retourne vrai si l'option de masquage automatique de l'ActionBar lorsqu'on scrolle dans un champ de la fenêtre a été activée.
*/
public boolean isMasquageAutomatiqueActionBar()
{
return false;
}
public static class WDActiviteFenetre extends WDActivite
{
protected WDFenetre getFenetre()
{
return GWDPQR.ms_Project.mWD_WIN_Bajar;
}
}
/**
* Retourne le nom du gabarit associée à la fenêtre.
*/
public String getNomGabarit()
{
return "210 MATERIAL DESIGN GREEN#WM";
}
}
