/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Fenêtre
 * Android class: WIN_Cargar_Datos
 * Date: 14/09/2018 02:54:17
 * Version of wdjava.dll: 22.0.106.0
 */


package com.mycompany.qr.wdgen;


import com.mycompany.qr.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.ui.champs.fenetre.*;
import fr.pcsoft.wdjava.ui.champs.jauge.*;
import fr.pcsoft.wdjava.ui.cadre.*;
import fr.pcsoft.wdjava.ui.champs.bouton.*;
import fr.pcsoft.wdjava.api.*;
import fr.pcsoft.wdjava.core.erreur.*;
import fr.pcsoft.wdjava.ui.champs.zr.*;
import fr.pcsoft.wdjava.ui.champs.saisie.*;
import fr.pcsoft.wdjava.ui.champs.groupeoptions.*;
import fr.pcsoft.wdjava.core.parcours.*;
import fr.pcsoft.wdjava.core.parcours.hf.*;
import fr.pcsoft.wdjava.ws.*;
import fr.pcsoft.wdjava.core.poo.*;
import fr.pcsoft.wdjava.ui.actionbar.*;
import fr.pcsoft.wdjava.ui.activite.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/



public class GWDFWIN_Cargar_Datos extends WDFenetre
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs de WIN_Cargar_Datos
////////////////////////////////////////////////////////////////////////////

/**
 * PROGBAR_Subir
 */
class GWDPROGBAR_Subir extends WDJaugeInfinie
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°1 de WIN_Cargar_Datos.PROGBAR_Subir
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(3005148265915527413l);

super.setChecksum("821815466");

super.setNom("PROGBAR_Subir");

super.setType(113);

super.setLibelle("Progress bar");

super.setNote("", "");

super.setEtatInitial(0);

super.setPositionInitiale(140, 206);

super.setTailleInitiale(29, 41);

super.setPlan(0);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(false);

super.setAltitude(1);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setTauxParallaxe(0, 0);

super.setPresenceLibelle(false);

super.setStyleLibelle(0x0, creerPolice_GEN("MS Shell Dlg", -11.000000, 0), -1, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xF1000000, 0xF3000000, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
protected int getTypeJauge()
{
return 1;
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDPROGBAR_Subir mWD_PROGBAR_Subir;

/**
 * BTN_Subir1
 */
class GWDBTN_Subir1 extends WDBouton
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°2 de WIN_Cargar_Datos.BTN_Subir1
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(3005148351815024609l);

super.setChecksum("821917058");

super.setNom("BTN_Subir1");

super.setType(4);

super.setLibelle("Leer datos");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(2, 211);

super.setTailleInitiale(122, 35);

super.setPlan(0);

super.setImageEtat(1);

super.setImageFondEtat(5);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(2);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setNumTab(3);

super.setLettreAppel(65535);

super.setTypeBouton(0);

super.setTypeActionPredefinie(0);

super.setBoutonOnOff(false);

super.setTauxParallaxe(0, 0);

super.setLibelleVAlign(1);

super.setLibelleHAlign(4);

super.setPresenceLibelle(true);

super.setImage("", 0, 2, 1, null, null, null);

super.setStyleLibelleRepos(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleSurvol(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleEnfonce(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setCadreRepos(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xE6E6E6, 4, 4, 1, 1));

super.setCadreSurvol(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xE6E6E6, 4, 4, 1, 1));

super.setCadreEnfonce(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xE6E6E6, 4, 4, 1, 1));

super.setImageFond9Images(new int[] {1,4,1,2,2,2,1,4,1}, 10, 10, 8, 8);

super.setImageFond("", 1, 0, 1, 1);

activerEcoute();
super.terminerInitialisation();
}

/**
 * Traitement: Click BTN_Subir1
 */
public void clicSurBoutonGauche()
// 
// iFont sUserOptions:sServerName ="" then
// 	Error("Debe tener opciones de configuración")
// 	return 
// END
// 
// 
{
super.clicSurBoutonGauche();


////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_bPasos = new WDBooleen();

WDObjet vWD_i = new WDEntier();



// PROGBAR_Subir..Visible = True
mWD_PROGBAR_Subir.setVisible(true);

// bPasos is boolean


// bPasos=Global_Borrar_datos_locales()
vWD_bPasos.setValeur(GWDCPCOL_GlobalProcedures.fWD_global_Borrar_datos_locales());

// IF bPasos=False THEN
if(vWD_bPasos.opEgal(false))
{
// 	IF gnaccesodatos=0 THEN
if(GWDPQR.ms_Project.vWD_gnaccesodatos.opEgal(0))
{
// 		Info("")
WDAPIDialogue.info(WDChaineMultilangue.getString("", "Tiene datos sin Enviar, proceda primero")
);

// 		gnaccesodatos=1
GWDPQR.ms_Project.vWD_gnaccesodatos.setValeur(1);

}

// 	Regresar()
fWD_regresar();

// 	RETURN 
return;

}

// i is int


// gsParzonas=""
GWDPQR.ms_Project.vWD_gsParzonas.setValeur("");

// gsParzonaswhere=""
GWDPQR.ms_Project.vWD_gsParzonaswhere.setValeur("");

// FOR i=1 TO LooperCount(LOOP_Zonas)
for(vWD_i.setValeur(1);vWD_i.opInfEgal(WDAPIZoneRepetee.zoneRepeteeOccurrence(mWD_LOOP_Zonas));vWD_i.opInc())
{
// 	IF LOOP_Zonas[i].cargar=True THEN
if(mWD_LOOP_Zonas.get(vWD_i).get("cargar").opEgal(true))
{
// 		gsParzonas += LOOP_Zonas[i].zona+","
GWDPQR.ms_Project.vWD_gsParzonas.setValeur(GWDPQR.ms_Project.vWD_gsParzonas.opPlus(mWD_LOOP_Zonas.get(vWD_i).get("zona").opPlus(",")));

// 		gsParzonaswhere += "'"+LOOP_Zonas[i].zona+"',"
GWDPQR.ms_Project.vWD_gsParzonaswhere.setValeur(GWDPQR.ms_Project.vWD_gsParzonaswhere.opPlus(new WDChaineU("'").opPlus(mWD_LOOP_Zonas.get(vWD_i).get("zona")).opPlus("',")));

}

}

// gsParzonas=NoRightCharacter(gsParzonas,",")
GWDPQR.ms_Project.vWD_gsParzonas.setValeur(WDAPIChaine.sansCaractereDroite(GWDPQR.ms_Project.vWD_gsParzonas.getString(),","));

// gsParzonaswhere=NoRightCharacter(gsParzonaswhere,",")
GWDPQR.ms_Project.vWD_gsParzonaswhere.setValeur(WDAPIChaine.sansCaractereDroite(GWDPQR.ms_Project.vWD_gsParzonaswhere.getString(),","));

// Erreur sur l'objet: WIN_Cargar_Datos.BTN_Subir1
// 	Traitement : Click BTN_Subir1 (18)
// 	Code: 301
// 	Message: The identifier 'proceso_recibir' is unknown or inaccessible.
// 	Ligne : 46, Colonne : 11
// 
// 
// Erreur sur l'objet: WIN_Cargar_Datos.BTN_Subir1
// 	Traitement : Click BTN_Subir1 (18)
// 	Code: 301
// 	Message: The identifier 'proceso_recibir' is unknown or inaccessible.
// 	Ligne : 46, Colonne : 11
// 
// 
WDErreurManager.erreurGeneration("Erreur sur l'objet: WIN_Cargar_Datos.BTN_Subir1\r\n\tTraitement : Click BTN_Subir1 (18)\r\n\tCode: 301\r\n\tMessage: The identifier 'proceso_recibir' is unknown or inaccessible.\r\n\tLigne : 46, Colonne : 11\r\n\r\n\r\nErreur sur l'objet: WIN_Cargar_Datos.BTN_Subir1\r\n\tTraitement : Click BTN_Subir1 (18)\r\n\tCode: 301\r\n\tMessage: The identifier 'proceso_recibir' is unknown or inaccessible.\r\n\tLigne : 46, Colonne : 11\r\n\r\n");


// // HDeleteAll(proceso_recibir)
// WDAPIHF.hSupprimeTout();
// 

// // bPasos=Leer_Datos_WS()
// vWD_bPasos.setValeur(fWD_leer_Datos_WS());
// 
// // IF bPasos=False THEN
// if(vWD_bPasos.opEgal(false))
// {
// // 	Regresar()
// fWD_regresar();
// 
// // 	RETURN 
// return;
// 
// }
// 
// // Regresar()
// fWD_regresar();
// 
// // ToastDisplay("Proceso finalizado")
// WDAPIToast.toastAffiche("Proceso finalizado");
// 
// // Close()
// WDAPIFenetre.ferme();
// 
}




// Activation des écouteurs: 
public void activerEcoute()
{
super.activerEcouteurClic();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDBTN_Subir1 mWD_BTN_Subir1;

/**
 * BTN_Cancelar
 */
class GWDBTN_Cancelar extends WDBouton
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°3 de WIN_Cargar_Datos.BTN_Cancelar
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(3005961573722063192l);

super.setChecksum("736418456");

super.setNom("BTN_Cancelar");

super.setType(4);

super.setLibelle("Cancelar");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(190, 210);

super.setTailleInitiale(119, 36);

super.setPlan(0);

super.setImageEtat(5);

super.setImageFondEtat(5);

super.setTailleMin(0, 0);

super.setTailleMax(134217727, 134217727);

super.setVisibleInitial(true);

super.setAltitude(3);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setNumTab(2);

super.setLettreAppel(65535);

super.setTypeBouton(3);

super.setTypeActionPredefinie(0);

super.setBoutonOnOff(false);

super.setTauxParallaxe(0, 0);

super.setLibelleVAlign(1);

super.setLibelleHAlign(5);

super.setPresenceLibelle(true);

super.setImage("C:\\My Mobile Projects\\QR\\Templates\\WM\\200 ActivAndroid 5\\ActivAndroid 5_Pict_Cancel_16_5.png?E5", 0, 1, 5, null, null, null);

super.setStyleLibelleRepos(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleSurvol(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setStyleLibelleEnfonce(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), 0, 0x808080);

super.setCadreRepos(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xD4BC00, 4, 4, 1, 1));

super.setCadreSurvol(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xE8C6B0, 4, 4, 1, 1));

super.setCadreEnfonce(WDCadreFactory.creerCadre_GEN(2, 0xFFFFFFFF, 0xBFBFBF, 0xD4BC00, 4, 4, 1, 1));

super.setImageFond9Images(new int[] {1,2,1,2,2,2,1,2,1}, 8, 8, 8, 8);

super.setImageFond("C:\\My Mobile Projects\\QR\\Templates\\WM\\200 ActivAndroid 5\\ActivAndroid 5_BTN_Cancel.png?E5_3NP_8_8_8_8", 1, 0, 1, 1);

activerEcoute();
super.terminerInitialisation();
}

/**
 * Traitement: Click BTN_Cancelar
 */
public void clicSurBoutonGauche()
{
super.clicSurBoutonGauche();

// Close()
WDAPIFenetre.ferme();

}




// Activation des écouteurs: 
public void activerEcoute()
{
super.activerEcouteurClic();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDBTN_Cancelar mWD_BTN_Cancelar;

/**
 * LOOP_Zonas
 */
class GWDLOOP_Zonas extends WDZoneRepeteeFichierAccesDirect
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°4 de WIN_Cargar_Datos.LOOP_Zonas
////////////////////////////////////////////////////////////////////////////

/**
 * zona
 */
class GWDzona extends WDChampSaisieSimple
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°1 de WIN_Cargar_Datos.LOOP_Zonas.zona
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setRectCompPrincipal(0,2,30,27);
super.setQuid(3005969850133178669l);

super.setChecksum("745555556");

super.setNom("zona");

super.setType(20001);

super.setLibelle("");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setTaille(10);

super.setNavigable(true);

super.setEtatInitial(1);

super.setPositionInitiale(8, 8);

super.setTailleInitiale(30, 31);

super.setValeurInitiale("");

super.setPlan(0);

super.setCadrageHorizontal(0);

super.setMotDePasse(false);

super.setLiaisonFichier("zonas", "zona");

super.setTypeSaisie(0);

super.setMasqueSaisie(new WDChaineU("0"));

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(1);

super.setAncrageInitial(8, 1000, 1000, 1000, 1000);

super.setEllipse(0);

super.setIndication("");

super.setNumTab(1);

super.setModeAscenseur(2, 2);

super.setEffacementAutomatique(true);

super.setFinSaisieAutomatique(false);

super.setLettreAppel(65535);

super.setSelectionEnAffichage(true);

super.setPersistant(false);

super.setClavierEnSaisie(true);

super.setMasqueAffichage(new WDChaineU(""));

super.setParamBtnActionClavier(0, "");

super.setRetraitGauche(0);

super.setMiseABlancSiZero(true);

super.setVerifieOrthographe(true);

super.setTauxParallaxe(0, 0);

super.setBoutonSuppression(0);

super.setPresenceLibelle(true);

super.setStyleLibelle(0x333333, creerPolice_GEN("Roboto", -7.000000, 0), -2, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xE6E6E6, 0x666666, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

super.setCadreInterne(WDCadreFactory.creerCadre_GEN("C:\\My Mobile Projects\\QR\\Templates\\WM\\200 ActivAndroid 5\\ActivAndroid 5_Edt.png?E5_3NP_8_8_8_8", new int[] {1,4,1,4,2,4,1,4,1}, new int[] {8, 8, 8, 8}, 0xFFFFFFFF, 3, 5));

super.setStyleSaisie(0x333333, creerPolice_GEN("Roboto", -7.000000, 0));

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDzona mWD_zona = new GWDzona();

/**
 * nombre
 */
class GWDnombre extends WDChampSaisieSimple
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°2 de WIN_Cargar_Datos.LOOP_Zonas.nombre
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setRectCompPrincipal(0,2,175,27);
super.setQuid(3005969850134030700l);

super.setChecksum("746407587");

super.setNom("nombre");

super.setType(20001);

super.setLibelle("");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setTaille(50);

super.setNavigable(true);

super.setEtatInitial(1);

super.setPositionInitiale(46, 8);

super.setTailleInitiale(175, 31);

super.setValeurInitiale("");

super.setPlan(0);

super.setCadrageHorizontal(0);

super.setMotDePasse(false);

super.setLiaisonFichier("zonas", "nombre");

super.setTypeSaisie(0);

super.setMasqueSaisie(new WDChaineU("0"));

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(2);

super.setAncrageInitial(8, 1000, 1000, 1000, 1000);

super.setEllipse(0);

super.setIndication("");

super.setNumTab(2);

super.setModeAscenseur(2, 2);

super.setEffacementAutomatique(true);

super.setFinSaisieAutomatique(false);

super.setLettreAppel(65535);

super.setSelectionEnAffichage(true);

super.setPersistant(false);

super.setClavierEnSaisie(true);

super.setMasqueAffichage(new WDChaineU(""));

super.setParamBtnActionClavier(0, "");

super.setRetraitGauche(0);

super.setMiseABlancSiZero(true);

super.setVerifieOrthographe(true);

super.setTauxParallaxe(0, 0);

super.setBoutonSuppression(0);

super.setPresenceLibelle(true);

super.setStyleLibelle(0x333333, creerPolice_GEN("Roboto", -7.000000, 0), -2, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xE6E6E6, 0x666666, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

super.setCadreInterne(WDCadreFactory.creerCadre_GEN("C:\\My Mobile Projects\\QR\\Templates\\WM\\200 ActivAndroid 5\\ActivAndroid 5_Edt.png?E5_3NP_8_8_8_8", new int[] {1,4,1,4,2,4,1,4,1}, new int[] {8, 8, 8, 8}, 0xFFFFFFFF, 3, 5));

super.setStyleSaisie(0x333333, creerPolice_GEN("Roboto", -7.000000, 0));

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDnombre mWD_nombre = new GWDnombre();

/**
 * cargar
 */
class GWDcargar extends WDInterrupteur
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°3 de WIN_Cargar_Datos.LOOP_Zonas.cargar
////////////////////////////////////////////////////////////////////////////

/**
 * cargar_Option_0
 */
class GWDcargar_Option_0 extends WDCaseACocher
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°1 de WIN_Cargar_Datos.LOOP_Zonas.cargar.cargar_Option_0
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setLibelle("cargar");

super.setHauteurOption(0);

super.setStyleLibelleOption(0x333333, creerPolice_GEN("Roboto", -7.000000, 0));

super.terminerInitialisation();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDcargar_Option_0 mWD_cargar_Option_0 = new GWDcargar_Option_0();
/**
 * Initialise tous les champs de WIN_Cargar_Datos.LOOP_Zonas.cargar
 */
public void initialiserSousObjets()
{
////////////////////////////////////////////////////////////////////////////
// Initialisation des champs de WIN_Cargar_Datos.LOOP_Zonas.cargar
////////////////////////////////////////////////////////////////////////////
super.initialiserSousObjets();
super.ajouterOption(mWD_cargar_Option_0);
positionnerOptions();
}
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setRectCompPrincipal(0,0,92,32);
super.setQuid(3005969850134882746l);

super.setChecksum("747261001");

super.setNom("cargar");

super.setType(5);

super.setLibelle("");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(209, 8);

super.setTailleInitiale(92, 32);

super.setValeurInitiale("0");

super.setPlan(0);

super.setLiaisonFichier("zonas", "cargar");

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(3);

super.setAncrageInitial(8, 1000, 1000, 1000, 1000);

super.setNumTab(3);

super.setLettreAppel(65535);

super.setPersistant(false);

super.setParamOptions(false, 1, true, true, false);

super.setTauxParallaxe(0, 0);

super.setPresenceLibelle(false);

super.setStyleLibelle(0x333333, creerPolice_GEN("Roboto", -7.000000, 0), -1, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xE6E6E6, 0x666666, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

super.setCadreInterne(WDCadreFactory.creerCadre_GEN(1, 0xE6E6E6, 0x666666, 0xFFFFFFFF, 4, 4, 1, 1));

super.setParamAnimationChamp(18, 19, 300);
super.setParamAnimationChamp(19, 20, 300);

super.setImageCoche("C:\\My Mobile Projects\\QR\\Templates\\WM\\200 ActivAndroid 5\\ActivAndroid 5_CBox.png?E12_A1A6A1A6A1A6A1A6A1A6A1A6_Radio", 6);

activerEcoute();
initialiserSousObjets();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDcargar mWD_cargar = new GWDcargar();
/**
 * Initialise tous les champs de WIN_Cargar_Datos.LOOP_Zonas
 */
public void initialiserSousObjets()
{
////////////////////////////////////////////////////////////////////////////
// Initialisation des champs de WIN_Cargar_Datos.LOOP_Zonas
////////////////////////////////////////////////////////////////////////////
super.initialiserSousObjets();
mWD_zona.initialiserObjet();
super.ajouterChamp("zona",mWD_zona);
mWD_nombre.initialiserObjet();
super.ajouterChamp("nombre",mWD_nombre);
mWD_cargar.initialiserObjet();
super.ajouterChamp("cargar",mWD_cargar);
creerAttributAuto();
}
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setRectCompPrincipal(0,0,309,48);
super.setQuid(3005969850132326155l);

super.setChecksum("744715810");

super.setNom("LOOP_Zonas");

super.setType(30);

super.setLibelle("");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(6, 7);

super.setTailleInitiale(309, 196);

super.setValeurInitiale("");

super.setPlan(0);

super.setSourceRemplissage("zonas", "zona", "zona", true, "", false);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(4);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000);

super.setNumTab(1);

super.setModeAscenseur(1, 1);

super.setModeSelection(99);

super.setSaisieEnCascade(false);

super.setLettreAppel(65535);

super.setEnregistrementSortieLigne(true);

super.setPersistant(false);

super.setParamAffichage(0, 1, 306, 48);

super.setBtnEnrouleDeroule(true);

super.setScrollRapide(false, null);

super.setDeplacementParDnd(0);

super.setSwipe(0, "", false, false, "", false, false);

super.setRecyclageChamp(true);

super.setTauxParallaxe(0, 0);

super.setPresenceLibelle(false);

super.setStyleLibelle(0x333333, creerPolice_GEN("Roboto", -9.000000, 0), -1, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xE6E6E6, 0x666666, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

super.setStyleSeparateurVerticaux(true, 0xE6E6E6);

super.setStyleSeparateurHorizontaux(1, 0xE6E6E6);

super.setDessinerLigneVide(false);

super.setCouleurCellule(0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFF, 0xD4BC00);

super.setImagePlusMoins("");

activerEcoute();
initialiserSousObjets();
super.terminerInitialisation();
}

/**
 * Traitement: End of initialization of LOOP_Zonas
 */
public void finInit()
// LOOP_Zonas..Visible=False
{
super.finInit();

// Leer_Datos_Previos()
fWD_leer_Datos_Previos();

// LooperDisplay(LOOP_Zonas)
WDAPIZoneRepetee.zoneRepeteeAffiche(this);

}




// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDLOOP_Zonas mWD_LOOP_Zonas;


////////////////////////////////////////////////////////////////////////////
// Procédures utilisateur de WIN_Cargar_Datos
////////////////////////////////////////////////////////////////////////////
//  Summary: <specify the procedure action>
//  Syntax:
// [ <Result> = ] Borrar_Datos_Locales ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	boolean: // 	None
// 
//  For instance:
//  Indicate an example.
// 
public WDObjet fWD_borrar_Datos_Locales()
{
initExecProcLocale("Borrar_Datos_Locales");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_j = new WDEntier();



// j is int


// FOR j=1 _TO_ HNbRec( Tabla_interface )
// Délimiteur de visibilité pour ne pas étendre la visibilité des variables temporaires _WDExpBorneMax et _WDExpPas
{
WDObjet _WDExpBorneMax0 = new WDEntier8(WDAPIHF.hNbEnr(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface")));
for(vWD_j.setValeur(1);vWD_j.opInfEgal(_WDExpBorneMax0);vWD_j.opInc())
{
// 	HRead(Tabla_interface,j)
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"),vWD_j.getLong());

// 	if Tabla_interface.direccion="I" then
if(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("direccion").opEgal("I"))
{
// 		IF Tabla_interface.borrardatos="S" THEN
if(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("borrardatos").opEgal("S"))
{
// 			sfile=Tabla_interface.Bdlocal
GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal"));

// 			HDeleteAll(sfile)
WDAPIHF.hSupprimeTout(GWDPQR.ms_Project.vWD_sfile);

}

}

}
}

// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcLocale();
}

}



//  Summary: <specify the procedure action>
//  Syntax:
//  Regresar ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	None
// 
//  For instance:
//  Indicate an example.
// 
public void fWD_regresar()
{
initExecProcLocale("Regresar");


try
{
// HDeactivateFilter(Tabla_interface)
WDAPIHF.hDesactiveFiltre(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"));

// HDeactivateFilter(Interface)
WDAPIHF.hDesactiveFiltre(WDAPIHF.getFichierSansCasseNiAccent("interface"));

// PROGBAR_Subir..Visible = False 
mWD_PROGBAR_Subir.setVisible(false);

}
finally
{
finExecProcLocale();
}

}



//  Summary: <specify the procedure action>
//  Syntax:
// [ <Result> = ] Leer_Datos_WS ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	boolean: // 	None
// 
//  For instance:
//  Indicate an example.
// 
public WDObjet fWD_leer_Datos_WS()
{
initExecProcLocale("Leer_Datos_WS");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_j = new WDEntier();

WDObjet vWD_sFiledestino = new WDChaineU();



// 	j is int


// sFiledestino is string


// hread(Usuarios,1)
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("usuarios"),(long)1);

// sUrl=Parametros.wsutrl 
GWDPQR.ms_Project.vWD_sUrl.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("wsutrl"));

// sservidor=Parametros.servidor
GWDPQR.ms_Project.vWD_sservidor.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("servidor"));

// sInstancia=Parametros.instancia
GWDPQR.ms_Project.vWD_sInstancia.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("instancia"));

// sBasededatos=Parametros.basededatos
GWDPQR.ms_Project.vWD_sBasededatos.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("basededatos"));

// sUsuario =Usuarios.usuario
GWDPQR.ms_Project.vWD_sUsuario.setValeur(WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("usuario"));

// sClave =Usuarios.clave
GWDPQR.ms_Project.vWD_sClave.setValeur(WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("clave"));

// sWhere=""  
GWDPQR.ms_Project.vWD_sWhere.setValeur("");

// sorder=""
GWDPQR.ms_Project.vWD_sorder.setValeur("");

// FOR EACH Tabla_interface  WHERE Tabla_interface.direccion="I"
IWDParcours parcours1 = null;
try
{
parcours1 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"), WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("direccion"), new WDChaineU("I"), 1, true);
while(parcours1.testParcours())
{
// 	sfile=Tabla_interface.Bdlocal
GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal"));

// 	ArrayDeleteAll(sCampos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCampos);

// 	ArrayDeleteAll(sCamposExt)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCamposExt);

// 	ArrayDeleteAll(sTipos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTipos);

// 	ArrayDeleteAll(scamposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_scamposlocales);

// 	ArrayDeleteAll(sTiposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTiposlocales);

// 	ArrayDeleteAll(sValoreslocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sValoreslocales);

// 		ArrayDeleteAll(arrSParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSParametros);

// 		ArrayDeleteAll(arrSValParametros)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_arrSValParametros);

// 	ArrayDeleteAll(sFilltabla)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sFilltabla);

// 	ArrayDeleteAll(sFillTipos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sFillTipos);

// 	ArrayDeleteAll(sFillcampobuscar)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sFillcampobuscar);

// 	ArrayDeleteAll(sFillcampollenar)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sFillcampollenar);

// 	ArrayDeleteAll(sFillcampovalor)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sFillcampovalor);

// 	gsTablename=Tabla_interface.Bddestino
GWDPQR.ms_Project.vWD_gsTablename.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bddestino"));

// 	sFiledestino=gsTablename
vWD_sFiledestino.setValeur(GWDPQR.ms_Project.vWD_gsTablename);

// 	sWhere=Tabla_interface.stwhere
GWDPQR.ms_Project.vWD_sWhere.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("stwhere"));

// 	sparametros=Tabla_interface.parametros
GWDPQR.ms_Project.vWD_sParametros.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("parametros"));

// 	Procesar_parametros()
GWDCPCOL_GlobalProcedures.fWD_procesar_parametros();

// 	Llenar_campos(sFiledestino)
GWDCPCOL_GlobalProcedures.fWD_llenar_campos(vWD_sFiledestino);

// 	IF ArrayCount(sCampos)=0 THEN
if(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCampos).opEgal(0))
{
// 		RESULT False
return new WDBooleen(false);

}

// 		Multitask(-1)
WDAPIVM.multitache(-1);

// 		Global_Leer_Tabla(sUrl,sservidor,sInstancia,sBasededatos,sUsuario,sClave, gsTablename, sListacampos,sWhere,sorder)
GWDCPCOL_GlobalProcedures.fWD_global_Leer_Tabla(GWDPQR.ms_Project.vWD_sUrl,GWDPQR.ms_Project.vWD_sservidor,GWDPQR.ms_Project.vWD_sInstancia,GWDPQR.ms_Project.vWD_sBasededatos,GWDPQR.ms_Project.vWD_sUsuario,GWDPQR.ms_Project.vWD_sClave,GWDPQR.ms_Project.vWD_gsTablename,GWDPQR.ms_Project.vWD_sListacampos,GWDPQR.ms_Project.vWD_sWhere,GWDPQR.ms_Project.vWD_sorder);

}
}
finally
{
if(parcours1 != null)
{
parcours1.finParcours();
}
}


// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcLocale();
}

}



//  Summary: <specify the procedure action>
//  Syntax:
//  Leer_Tabla ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	None
// 
//  For instance:
//  Indicate an example.
// 
public void fWD_leer_Tabla()
{
initExecProcLocale("Leer_Tabla");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_v1 = WDVarNonAllouee.ref;
WDObjet vWD_v2 = WDVarNonAllouee.ref;
WDObjet vWD_sRESULTADO = new WDChaineU();



// IF InAndroidSimulatorMode()=False 
if(WDAPIVM.enModeSimulateurAndroid().opEgal(false))
{
}

// v1 is LeerTabla
vWD_v1 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "LeerTabla") );


// v2 is LeerTablaResponse
vWD_v2 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "LeerTablaResponse") );


// sRESULTADO IS string


// v1.tabla=Tabla_interface.Bddestino
vWD_v1.get("tabla").setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bddestino"));

// v1.campos=NoRightCharacter(sListacampos,",")
vWD_v1.get("campos").setValeur(WDAPIChaine.sansCaractereDroite(GWDPQR.ms_Project.vWD_sListacampos.getString(),","));

// v1.where=swhere
vWD_v1.get("where").setValeur(GWDPQR.ms_Project.vWD_sWhere);

// v2=LeerTabla(v1)
vWD_v2.setValeur(WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").invoquerMethode("LeerTabla", new WDObjet[] {vWD_v1} ));

// sResultado=v2.LeerTablaResult
vWD_sRESULTADO.setValeur(vWD_v2.get("LeerTablaResult"));

// IF sResultado<>"" THEN
if(vWD_sRESULTADO.opDiff(""))
{
}

// RETURN 
return;

}
finally
{
finExecProcLocale();
}

}



//  Summary: <specify the procedure action>
//  Syntax:
// [ <Result> = ] Leer_Datos_Previos ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	boolean: // 	None
// 
//  For instance:
//  Indicate an example.
// 
public WDObjet fWD_leer_Datos_Previos()
{
initExecProcLocale("Leer_Datos_Previos");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_j = new WDEntier();

WDObjet vWD_i = new WDEntier();

WDObjet vWD_res = new WDBooleen();



// j is int


// i is int 


// res is boolean


// hread(Usuarios,1)
WDAPIHF.hLit(WDAPIHF.getFichierSansCasseNiAccent("usuarios"),(long)1);

// sUrl=Parametros.wsutrl //EDT_Wsutrl
GWDPQR.ms_Project.vWD_sUrl.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("wsutrl"));

// sservidor=Parametros.servidor
GWDPQR.ms_Project.vWD_sservidor.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("servidor"));

// sInstancia=Parametros.instancia
GWDPQR.ms_Project.vWD_sInstancia.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("instancia"));

// sBasededatos=Parametros.basededatos
GWDPQR.ms_Project.vWD_sBasededatos.setValeur(WDAPIHF.getFichierSansCasseNiAccent("parametros").getRubriqueSansCasseNiAccent("basededatos"));

// sUsuario =usuarios.usuario
GWDPQR.ms_Project.vWD_sUsuario.setValeur(WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("usuario"));

// sClave =Usuarios.clave
GWDPQR.ms_Project.vWD_sClave.setValeur(WDAPIHF.getFichierSansCasseNiAccent("usuarios").getRubriqueSansCasseNiAccent("clave"));

// sWhere=""  //" usuario='"+sUsuario+"'"
GWDPQR.ms_Project.vWD_sWhere.setValeur("");

// sorder=""
GWDPQR.ms_Project.vWD_sorder.setValeur("");

// FOR EACH Tabla_interface  WHERE Tabla_interface.direccion="P"
IWDParcours parcours2 = null;
try
{
parcours2 = WDParcoursFichier.pourTout(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface"), WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("direccion"), new WDChaineU("P"), 1, true);
while(parcours2.testParcours())
{
// 		sfile=Tabla_interface.Bdlocal
GWDPQR.ms_Project.vWD_sfile.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bdlocal"));

// 		res=HDeleteAll(sfile)
vWD_res.setValeur(WDAPIHF.hSupprimeTout(GWDPQR.ms_Project.vWD_sfile));

// 		i=Hnbrec(sfile)
vWD_i.setValeur(WDAPIHF.hNbEnr(GWDPQR.ms_Project.vWD_sfile));

// 		ArrayDeleteAll(sCampos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCampos);

// 		ArrayDeleteAll(sCamposExt)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sCamposExt);

// 		ArrayDeleteAll(sTipos)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTipos);

// 		ArrayDeleteAll(scamposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_scamposlocales);

// 		ArrayDeleteAll(sTiposlocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sTiposlocales);

// 		ArrayDeleteAll(sValoreslocales)
WDAPITableau.tableauSupprimeTout(GWDPQR.ms_Project.vWD_sValoreslocales);

// 		sListacampos=""
GWDPQR.ms_Project.vWD_sListacampos.setValeur("");

// 		sWhere=Tabla_interface.stwhere
GWDPQR.ms_Project.vWD_sWhere.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("stwhere"));

// 		sParametros=Tabla_interface.parametros
GWDPQR.ms_Project.vWD_sParametros.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("parametros"));

// 		gsTablename=Tabla_interface.Bddestino
GWDPQR.ms_Project.vWD_gsTablename.setValeur(WDAPIHF.getFichierSansCasseNiAccent("tabla_interface").getRubriqueSansCasseNiAccent("bddestino"));

// 		Procesar_parametros()
GWDCPCOL_GlobalProcedures.fWD_procesar_parametros();

// 		Llenar_campos(gsTablename)
GWDCPCOL_GlobalProcedures.fWD_llenar_campos(GWDPQR.ms_Project.vWD_gsTablename);

// 		IF ArrayCount(sCampos)=0 THEN
if(WDAPITableau.tableauOccurrence(GWDPQR.ms_Project.vWD_sCampos).opEgal(0))
{
// 			RESULT False
return new WDBooleen(false);

}

// 			Multitask(-1)
WDAPIVM.multitache(-1);

// 			Global_Leer_Tabla(sUrl,sservidor,sInstancia,sBasededatos,sUsuario,sClave, gsTablename, sListacampos,sWhere,sorder)
GWDCPCOL_GlobalProcedures.fWD_global_Leer_Tabla(GWDPQR.ms_Project.vWD_sUrl,GWDPQR.ms_Project.vWD_sservidor,GWDPQR.ms_Project.vWD_sInstancia,GWDPQR.ms_Project.vWD_sBasededatos,GWDPQR.ms_Project.vWD_sUsuario,GWDPQR.ms_Project.vWD_sClave,GWDPQR.ms_Project.vWD_gsTablename,GWDPQR.ms_Project.vWD_sListacampos,GWDPQR.ms_Project.vWD_sWhere,GWDPQR.ms_Project.vWD_sorder);

}
}
finally
{
if(parcours2 != null)
{
parcours2.finParcours();
}
}


// RESULT True
return new WDBooleen(true);

}
finally
{
finExecProcLocale();
}

}



//  Summary: <specify the procedure action>
//  Syntax:
// Leer_Tablacomp ()
// 
//  Parameters:
// 	None
//  Return Value:
//  	None
// 
//  For instance:
//  Indicate an example.
// 
public void fWD_leer_Tablacomp()
{
initExecProcLocale("Leer_Tablacomp");


try
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_v1 = WDVarNonAllouee.ref;
WDObjet vWD_v2 = WDVarNonAllouee.ref;
WDObjet vWD_v11 = WDVarNonAllouee.ref;
WDObjet vWD_v12 = WDVarNonAllouee.ref;
WDObjet vWD_sRESULTADO = new WDChaineU();

WDObjet vWD_sResultadoparcial = new WDChaineU();

WDObjet vWD_sName = new WDChaineU();

WDObjet vWD_sNamein = new WDChaineU();

WDObjet vWD_ssize = new WDChaineU();

WDObjet vWD_n = new WDEntier();

WDObjet vWD_m = new WDEntier();



// v1 is LeerTablacomp
vWD_v1 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "LeerTablacomp") );


// v2 is LeerTablacompResponse
vWD_v2 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "LeerTablacompResponse") );


// v11 is DownloadFile
vWD_v11 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "DownloadFile") );


// v12 is DownloadFileResponse
vWD_v12 = new WDInstance( new WDWSEntiteXSD("WSDataSQLService", "DownloadFileResponse") );


// sRESULTADO IS string


// sResultadoparcial is string 


// sName is string


// sNamein is string


// ssize is string 


// v1.servidor="" //ALFREDO-PC\\SQLEXPRESS" //sServername
vWD_v1.get("servidor").setValeur("");

// v1.basededatos="scin"
vWD_v1.get("basededatos").setValeur("scin");

// v1.tabla=gsTablename
vWD_v1.get("tabla").setValeur(GWDPQR.ms_Project.vWD_gsTablename);

// v1.campos=NoRightCharacter(sListacampos,",")
vWD_v1.get("campos").setValeur(WDAPIChaine.sansCaractereDroite(GWDPQR.ms_Project.vWD_sListacampos.getString(),","));

// v1.where=sWhere
vWD_v1.get("where").setValeur(GWDPQR.ms_Project.vWD_sWhere);

// v2=LeerTablacomp(v1)
vWD_v2.setValeur(WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").invoquerMethode("LeerTablacomp", new WDObjet[] {vWD_v1} ));

// n is int


// m is int


// sResultado=v2.LeerTablacompResult
vWD_sRESULTADO.setValeur(vWD_v2.get("LeerTablacompResult"));

// IF sResultado<>"" THEN
if(vWD_sRESULTADO.opDiff(""))
{
// 	n = Position(sResultado, "<filename>", 1, FromBeginning)
vWD_n.setValeur(WDAPIChaine.position(vWD_sRESULTADO,new WDChaineU("<filename>"),1,0));

// 	if n>0 then
if(vWD_n.opSup(0))
{
// 		m = Position(sResultado, "</filename>", 1, FromBeginning)
vWD_m.setValeur(WDAPIChaine.position(vWD_sRESULTADO,new WDChaineU("</filename>"),1,0));

// 		sName=middle(sResultado,n + 10, m - (n + 10))
vWD_sName.setValeur(WDAPIChaine.milieu(vWD_sRESULTADO,vWD_n.opPlus(10).getInt(),vWD_m.opMoins(vWD_n.opPlus(10)).getInt()));

// 		v11.FName=sName
vWD_v11.get("FName").setValeur(vWD_sName);

// 		f is int
WDObjet vWD_f = new WDEntier();



// 		IF InAndroidSimulatorMode()=True THEN
if(WDAPIVM.enModeSimulateurAndroid().opEgal(true))
{
// 			sNamein = "c:\\sistemas\\wsin\\"+DateSys() + TimeSys() + ".txt"
vWD_sNamein.setValeur(new WDChaineU("c:\\sistemas\\wsin\\").opPlus(WDAPIDate.dateSys()).opPlus(WDAPIDate.heureSys()).opPlus(".txt"));

// 			f=fOpen(sNamein, foCreate)
vWD_f.setValeur(WDAPIFichier.fOuvre(vWD_sNamein.getString(),512));

}
else
{
// 			sNamein = "/sdcard/recibos/"+DateSys() + TimeSys() + ".txt"
vWD_sNamein.setValeur(new WDChaineU("/sdcard/recibos/").opPlus(WDAPIDate.dateSys()).opPlus(WDAPIDate.heureSys()).opPlus(".txt"));

// 			f=fOpen(sNamein, foCreate)
vWD_f.setValeur(WDAPIFichier.fOuvre(vWD_sNamein.getString(),512));

}

// 		IF f=-1 THEN
if(vWD_f.opEgal(-1))
{
// 			 RETURN 
return;

}

// 		n = Position(sResultado, "<size>", 1, FromBeginning)
vWD_n.setValeur(WDAPIChaine.position(vWD_sRESULTADO,new WDChaineU("<size>"),1,0));

// 		m = Position(sResultado, "</size>", 1, FromBeginning)
vWD_m.setValeur(WDAPIChaine.position(vWD_sRESULTADO,new WDChaineU("</size>"),1,0));

// 		ssize=Middle(sResultado,n + 6, m - (n + 6))
vWD_ssize.setValeur(WDAPIChaine.milieu(vWD_sRESULTADO,vWD_n.opPlus(6).getInt(),vWD_m.opMoins(vWD_n.opPlus(6)).getInt()));

// 		m=((val(ssize) +40000) / 40000) +1
vWD_m.setValeur(WDAPIChaine.val(vWD_ssize).opPlus(40000).opDiv(40000).opPlus(1));

// 		m=((fsize(sName) +  40000)/40000) + 1
vWD_m.setValeur(WDAPIFichier.fTaille(vWD_sName.getString()).opPlus(40000).opDiv(40000).opPlus(1));

// 		sResultado=""
vWD_sRESULTADO.setValeur("");

// 		for n=1 to m
for(vWD_n.setValeur(1);vWD_n.opInfEgal(vWD_m);vWD_n.opInc())
{
// 			v11.parte=NumToString(n)
vWD_v11.get("parte").setValeur(WDAPINum.numeriqueVersChaine(vWD_n));

// 			v12=DownloadFile(v11)	
vWD_v12.setValeur(WDWSManager.getClientWS("WSDataSQLService", "WSDataSQLService").invoquerMethode("DownloadFile", new WDObjet[] {vWD_v11} ));

// 			sResultadoparcial = v12.DownloadFileResult
vWD_sResultadoparcial.setValeur(vWD_v12.get("DownloadFileResult"));

// 			IF fWrite(f,sResultadoparcial  )=-1 THEN RETURN 
if(WDAPIFichier.fEcrit(vWD_f.getInt(),vWD_sResultadoparcial).opEgal(-1))
{
// 			IF fWrite(f,sResultadoparcial  )=-1 THEN RETURN 
return;

}

}

// 		IF fClose(f)=-1 THEN RETURN
if(WDAPIFichier.fFerme(vWD_f.getInt()).opEgal(-1))
{
// 		IF fClose(f)=-1 THEN RETURN
return;

}

// 		fDelete(sNamein)
WDAPIFichier.fSupprime(vWD_sNamein.getString());

}

}
else
{
}

// RETURN    
return;

}
finally
{
finExecProcLocale();
}

}




/**
 * ACTB_ActionBar
 */
class GWDACTB_ActionBar extends WDActionBar
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°1 de WIN_Cargar_Datos.ACTB_ActionBar
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setNom("ACTB_ActionBar");

super.setNote("", "");

super.setParamBoutonGauche(true, 1, "", "C:\\My Mobile Projects\\QR\\LOGOEVA.jpg");

super.setParamBoutonDroit(false, 0, "", "");

super.setStyleActionBar(0xFF000001, 0xFF000001, true);

super.setImageFond("");

super.terminerInitialisation();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDACTB_ActionBar mWD_ACTB_ActionBar;

/**
 * Traitement: Global declarations of WIN_Cargar_Datos
 */
public void declarerGlobale(WDObjet[] WD_tabParam)
{
super.declarerGlobale(WD_tabParam);
int WD_ntabParamLen = 0;
if(WD_tabParam!=null) WD_ntabParamLen = WD_tabParam.length;


}




// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
// Création des champs de la fenêtre WIN_Cargar_Datos
////////////////////////////////////////////////////////////////////////////
protected void creerChamps()
{
mWD_PROGBAR_Subir = new GWDPROGBAR_Subir();
mWD_BTN_Subir1 = new GWDBTN_Subir1();
mWD_BTN_Cancelar = new GWDBTN_Cancelar();
mWD_LOOP_Zonas = new GWDLOOP_Zonas();
mWD_ACTB_ActionBar = new GWDACTB_ActionBar();

}
////////////////////////////////////////////////////////////////////////////
// Initialisation de la fenêtre WIN_Cargar_Datos
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.setQuid(3005130742448681009l);

super.setChecksum("825881143");

super.setNom("WIN_Cargar_Datos");

super.setType(1);

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setCouleur(0x0);

super.setCouleurFond(0xFFFFFF);

super.setPositionInitiale(0, 0);

super.setTailleInitiale(320, 408);

super.setTitre("Cargar Datos");

super.setTailleMin(-1, -1);

super.setTailleMax(20000, 20000);

super.setVisibleInitial(true);

super.setPersistant(true);

super.setGFI(true);

super.setAnimationFenetre(0);

super.setImageFond("", 327683, 0, 1);

super.setCouleurTexteAutomatique(0xF4000000);

super.setCouleurBarreSysteme(0xFF000001);


activerEcoute();

////////////////////////////////////////////////////////////////////////////
// Initialisation des champs de WIN_Cargar_Datos
////////////////////////////////////////////////////////////////////////////
mWD_PROGBAR_Subir.initialiserObjet();
super.ajouter("PROGBAR_Subir", mWD_PROGBAR_Subir);
mWD_BTN_Subir1.initialiserObjet();
super.ajouter("BTN_Subir1", mWD_BTN_Subir1);
mWD_BTN_Cancelar.initialiserObjet();
super.ajouter("BTN_Cancelar", mWD_BTN_Cancelar);
mWD_LOOP_Zonas.initialiserObjet();
super.ajouter("LOOP_Zonas", mWD_LOOP_Zonas);
mWD_ACTB_ActionBar.initialiserObjet();
super.ajouterActionBar(mWD_ACTB_ActionBar);

super.terminerInitialisation();
}

////////////////////////////////////////////////////////////////////////////
public boolean isUniteAffichageLogique()
{
return false;
}
/**
* Retourne le mode d'affichage de l'ActionBar de la fenêtre.
*/
public int getModeActionBar()
{
return 1;
}
/**
* Retourne vrai si la fenêtre est maximisée, faux sinon.
*/
public boolean isMaximisee()
{
return true;
}
/**
* Retourne vrai si la fenêtre a une barre de titre, faux sinon.
*/
public boolean isAvecBarreDeTitre()
{
return true;
}
/**
* Retourne le mode d'affichage de la barre système de la fenêtre.
*/
public int getModeBarreSysteme()
{
return 1;
}
/**
* Retourne vrai si la fenêtre est munie d'ascenseurs automatique, faux sinon.
*/
public boolean isAvecAscenseurAuto()
{
return false;
}
/**
* Retourne Vrai si on doit appliquer un theme "dark" (sombre) ou Faux si on doit appliquer "light" (clair) à la fenêtre.
* Ce choix se base sur la couleur du libellé par défaut dans le gabarit de la fenêtre.
*/
public boolean isThemeDark()
{
return false;
}
/**
* Retourne vrai si l'option de masquage automatique de l'ActionBar lorsqu'on scrolle dans un champ de la fenêtre a été activée.
*/
public boolean isMasquageAutomatiqueActionBar()
{
return false;
}
public static class WDActiviteFenetre extends WDActivite
{
protected WDFenetre getFenetre()
{
return GWDPQR.ms_Project.mWD_WIN_Cargar_Datos;
}
}
/**
* Retourne le nom du gabarit associée à la fenêtre.
*/
public String getNomGabarit()
{
return "200 ACTIVANDROID 5#WM";
}
}
