/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Requête
 * Android class: QRY_Login
 * Date: 14/09/2018 02:54:17
 * Version of wdjava.dll: 22.0.106.0
 */


package com.mycompany.qr.wdgen;


import com.mycompany.qr.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.database.hf.requete.parsing.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/



public class GWDRQRY_Login extends WDDescRequeteWDR
{
public String getNomLogique()
{
return "QRY_Login";
}
public String getCodeSQLOriginal()
{
return "SELECT Parametros.Password FROM parametros WHERE parametros.NombreUsuario = {Param1#0}\r\n\r\n";
}
public Requete initArbre() throws WDInvalidSQLException
{
throw new WDInvalidSQLException("PASSWORD item unknown in parametros file. Check whether query is consistent with file description.");
}
public String getNomFichier(int nIndex)
{
switch(nIndex)
{
default: return null;
}
}
public String getAliasFichier(int nIndex)
{
switch(nIndex)
{
default: return null;
}
}


}
