/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Requête
 * Android class: QRY_Filtro_Inventario
 * Date: 27/09/2018 02:59:08
 * Version of wdjava.dll: 22.0.106.0
 */


package com.mycompany.qr.wdgen;


import com.mycompany.qr.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.database.hf.requete.parsing.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/



public class GWDRQRY_Filtro_Inventario extends WDDescRequeteWDR
{
public String getNomLogique()
{
return "QRY_Filtro_Inventario";
}
public String getCodeSQLOriginal()
{
return "SELECT \r\nInventario.InventarioID,\r\nInventario.Tipo, \r\nInventario.Documento, \r\nInventario.Partida, \r\nInventario.Sacos, \r\nInventario.PesoNeto,\r\nInventario.Fecha, \r\nInventario.Sacos, \r\nInventario.Tipocafe, \r\ninventario.Calidad, \r\nInventario.Tipocafe \r\nFROM Inventario WHERE Inventario.Partida LIKE %{pPartida#0}% ";
}
public Requete initArbre() throws WDInvalidSQLException
{
Select varSelect = new Select();
varSelect.setType(1);
Rubrique rub_InventarioID = new Rubrique();
rub_InventarioID.setNom("InventarioID");
rub_InventarioID.setAlias("InventarioID");
rub_InventarioID.setNomFichier("Inventario");
rub_InventarioID.setAliasFichier("Inventario");
varSelect.ajouterElement(rub_InventarioID);
Rubrique rub_Tipo = new Rubrique();
rub_Tipo.setNom("Tipo");
rub_Tipo.setAlias("Tipo");
rub_Tipo.setNomFichier("Inventario");
rub_Tipo.setAliasFichier("Inventario");
varSelect.ajouterElement(rub_Tipo);
Rubrique rub_Documento = new Rubrique();
rub_Documento.setNom("Documento");
rub_Documento.setAlias("Documento");
rub_Documento.setNomFichier("Inventario");
rub_Documento.setAliasFichier("Inventario");
varSelect.ajouterElement(rub_Documento);
Rubrique rub_Partida = new Rubrique();
rub_Partida.setNom("Partida");
rub_Partida.setAlias("Partida");
rub_Partida.setNomFichier("Inventario");
rub_Partida.setAliasFichier("Inventario");
varSelect.ajouterElement(rub_Partida);
Rubrique rub_Sacos = new Rubrique();
rub_Sacos.setNom("Sacos");
rub_Sacos.setAlias("Sacos");
rub_Sacos.setNomFichier("Inventario");
rub_Sacos.setAliasFichier("Inventario");
varSelect.ajouterElement(rub_Sacos);
Rubrique rub_PesoNeto = new Rubrique();
rub_PesoNeto.setNom("PesoNeto");
rub_PesoNeto.setAlias("PesoNeto");
rub_PesoNeto.setNomFichier("Inventario");
rub_PesoNeto.setAliasFichier("Inventario");
varSelect.ajouterElement(rub_PesoNeto);
Rubrique rub_Fecha = new Rubrique();
rub_Fecha.setNom("Fecha");
rub_Fecha.setAlias("Fecha");
rub_Fecha.setNomFichier("Inventario");
rub_Fecha.setAliasFichier("Inventario");
varSelect.ajouterElement(rub_Fecha);
Rubrique rub_Expr1 = new Rubrique();
rub_Expr1.setNom("Sacos");
rub_Expr1.setAlias("Expr1");
rub_Expr1.setNomFichier("Inventario");
rub_Expr1.setAliasFichier("Inventario");
varSelect.ajouterElement(rub_Expr1);
Rubrique rub_Tipocafe = new Rubrique();
rub_Tipocafe.setNom("Tipocafe");
rub_Tipocafe.setAlias("Tipocafe");
rub_Tipocafe.setNomFichier("Inventario");
rub_Tipocafe.setAliasFichier("Inventario");
varSelect.ajouterElement(rub_Tipocafe);
Rubrique rub_Calidad = new Rubrique();
rub_Calidad.setNom("Calidad");
rub_Calidad.setAlias("Calidad");
rub_Calidad.setNomFichier("Inventario");
rub_Calidad.setAliasFichier("inventario");
varSelect.ajouterElement(rub_Calidad);
Rubrique rub_Expr2 = new Rubrique();
rub_Expr2.setNom("Tipocafe");
rub_Expr2.setAlias("Expr2");
rub_Expr2.setNomFichier("Inventario");
rub_Expr2.setAliasFichier("Inventario");
varSelect.ajouterElement(rub_Expr2);
From varFrom = new From();
Fichier fic_Inventario = new Fichier();
fic_Inventario.setNom("Inventario");
fic_Inventario.setAlias("Inventario");
varFrom.ajouterElement(fic_Inventario);
Requete varReqSelect = new Requete(1);
varReqSelect.ajouterClause(varSelect);
varReqSelect.ajouterClause(varFrom);
Expression expr_LIKE = new Expression(32, "LIKE", "");
expr_LIKE.ajouterOption(EWDOptionRequete.LIKE_CASE_SENSITIVE, "0");
expr_LIKE.ajouterOption(EWDOptionRequete.LIKE_COMMENCE_PAR, "0");
expr_LIKE.ajouterOption(EWDOptionRequete.LIKE_CONTIENT, "1");
expr_LIKE.ajouterOption(EWDOptionRequete.LIKE_FINI_PAR, "0");
expr_LIKE.ajouterOption(EWDOptionRequete.NOT_LIKE, "0");
expr_LIKE.ajouterOption(EWDOptionRequete.LIKE_CARACT_ECHAP, "92");
Rubrique rub_Partida_1 = new Rubrique();
rub_Partida_1.setNom("Inventario.Partida");
rub_Partida_1.setAlias("Partida");
rub_Partida_1.setNomFichier("Inventario");
rub_Partida_1.setAliasFichier("Inventario");
expr_LIKE.ajouterElement(rub_Partida_1);
Parametre param_pPartida = new Parametre();
param_pPartida.setNom("pPartida");
expr_LIKE.ajouterElement(param_pPartida);
Where varWhere = new Where();
varWhere.ajouterElement(expr_LIKE);
varReqSelect.ajouterClause(varWhere);
Limit varLimit = new Limit();
varLimit.setType(0);
varLimit.setNbEnregs(0);
varLimit.setOffset(0);
varReqSelect.ajouterClause(varLimit);
return varReqSelect;
}
public String getNomFichier(int nIndex)
{
switch(nIndex)
{
case 0 : return "Inventario";
default: return null;
}
}
public String getAliasFichier(int nIndex)
{
switch(nIndex)
{
case 0 : return "Inventario";
default: return null;
}
}


}
